/**
 * Ordered list of fixture tables for Fixted.populate().
 * Order matters — tables with foreign keys must come after their dependencies.
 *
 * Shared between test/bootstrap.test.js and scripts/snapshot-test-db.js
 * to keep the template in sync with the test bootstrap.
 */
module.exports = [
  'tlanguage',
  'tidentifiertype',
  'tsubject',
  'ttype',
  'tcountry',
  'tiso31662',
  'tgroup',
  'tnotificationtype',
  'ttokenblacklist',
  'tcaver',
  'tdevice',
  // tunit before tquantitykind: t_quantity_kind.id_display_unit is an FK into
  // t_unit (t_quantity_kind_t_unit_fk).
  'tunit',
  'tquantitykind',
  'tmedium',
  'tobservationtype',
  'thumanactivitytype',
  'tcontaminanttype',
  'tsubstance',
  'tsensorconfiguration',
  'tname',
  'tgrotto',
  'tdocument',
  'tdescription',
  'tlocation',
  'tcave',
  'tentrance',
  'jcavercaveexplorer',
  'jcaverentranceexplorer',
  'jcaverregionsubscription',
  'tmassif',
  'thistory',
  'tfileformat',
  'tlicense',
  'toption',
  'tcomment',
  'tguideline',
  'jguidelinecountry',
  'jguidelineregion',
  'jguidelinemassif',
  'tfile',
  'trigging',
  'tnotification',
  'tcrs',
  'jcountrycrs',
  'jorganizationcountry',
  'jorganizationregion',
  'jorganizationmassif',
  'hlocation',
  'hdescription',
  'hentrance',
  'hname',
  'hguideline',
  'vcaverroles',
  'vbibliographicmetadata',
  'vcountryinfo',
  'vregioninfo',
  'vmassifinfo',
  'vdataqualitycomputeentrance',
];
