module.exports = {
  // See this issue for more info: https://github.com/GrottoCenter/Grottocenter3/issues/416
  '@context': 'https://ontology.uis-speleo.org/grottocenter.org_context.jsonld',
  '@id': undefined,
  '@type': 'https://ontology.uis-speleo.org/ontology/#UndergroundCavity',
  author: undefined,
  dateInscription: undefined,
  dateReviewed: undefined,
  depth: undefined,
  descriptions: [],
  documents: [],
  entrances: [],
  histories: [],
  id: undefined,
  isDeleted: undefined,
  isDiving: undefined,
  length: undefined,
  massif: undefined,
  name: undefined,
  names: [],
  reviewer: undefined,
  temperature: undefined,
};
