module.exports = {
  id: undefined,
  author: undefined,
  title: undefined,
  body: undefined,
  dateInscription: undefined,
  dateReviewed: undefined,
  language: undefined,
  cave: undefined,
  entrance: undefined,
  relevance: undefined,
  reviewer: undefined,
  eTUnderground: undefined,
  eTTrail: undefined,
  aestheticism: undefined,
  caving: undefined,
  approach: undefined,
  isDeleted: undefined,
};
