module.exports = {
  author: undefined,
  body: undefined,
  cave: undefined,
  dateInscription: undefined,
  dateReviewed: undefined,
  document: undefined,
  entrance: undefined,
  exit: undefined,
  id: undefined,
  language: undefined,
  massif: undefined,
  point: undefined,
  relevance: undefined,
  reviewer: undefined,
  title: undefined,
};
