module.exports = {
  // See this issue for more info: https://github.com/GrottoCenter/Grottocenter3/issues/416
  '@context': 'https://ontology.uis-speleo.org/grottocenter.org_context.jsonld',
  '@id': undefined,
  '@type': 'dct:BibliographicResource',
  author: undefined,
  authorComment: undefined,
  cave: undefined,
  country: undefined,
  dateInscription: undefined,
  datePublication: undefined,
  dateValidation: undefined,
  descriptions: [],
  editor: undefined,
  entrance: undefined,
  files: [],
  identifierType: undefined,
  languages: [],
  library: undefined,
  license: undefined,
  mainLanguage: undefined,
  massif: undefined,
  pages: undefined,
  refBbs: undefined,
  regions: undefined,
  reviewer: undefined,
  subjects: undefined,
  theme: undefined,
  title: undefined,
  titles: [],
  type: undefined,
};
