module.exports = {
  // See this issue for more info: https://github.com/GrottoCenter/Grottocenter3/issues/416
  '@context': 'https://ontology.uis-speleo.org/grottocenter.org_context.jsonld',
  '@base': 'entrances/',
  '@id': undefined,
  '@type': 'https://ontology.uis-speleo.org/ontology/#UndergroundCavity',
  id: undefined,
  name: undefined,
  names: undefined,
  descriptions: [],
  country: undefined,
  countryCode: undefined,
  county: undefined,
  region: undefined,
  city: undefined,
  postalCode: undefined,
  latitude: undefined,
  longitude: undefined,
  altitude: undefined,
  cave: undefined,
  massif: undefined,
  aestheticism: undefined,
  caving: undefined,
  approach: undefined,
  documents: [],
  stats: undefined,
  timeInfo: undefined,
  locations: [],
  documents: [],
  riggings: [],
  comments: [],
};
