module.exports = {
  // See this issue for more info: https://github.com/GrottoCenter/Grottocenter3/issues/429
  '@context': 'https://ontology.uis-speleo.org/grottocenter.org_context.jsonld',
  '@id': undefined,
  '@type': 'http://purl.org/dc/terms/Location',
  address: undefined,
  cavers: [],
  city: undefined,
  contact: undefined,
  country: undefined,
  countryCode: undefined,
  county: undefined,
  customMessage: undefined,
  documentary: undefined,
  exploredCaves: [],
  id: undefined,
  isOfficialPartner: undefined,
  latitude: undefined,
  longitude: undefined,
  name: undefined,
  partneredCaves: [],
  pictureFileName: undefined,
  postalCode: undefined,
  region: undefined,
  URL: undefined,
  village: undefined,
  yearBirth: undefined,
};
