env:
  es6: true
  node: true
  mocha: true
rules:
  # strict: [error, global]
  indent: [error, 2, {SwitchCase: 1}]
  # linebreak-style: [error, unix]
  comma-dangle: [error, only-multiline]
  quotes: [error, single, {avoidEscape: true}]
  semi: [error, always]
  eqeqeq: error
  camelcase: error
  curly: [error, multi-line]
  brace-style: error
  radix: error
  yoda: error
  no-const-assign: error
  no-console: [error, {allow: [warn, error]}]
  no-var: error
  require-yield: off
extends:
  - 'eslint:recommended'
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
