root: true
env:
  es6: true
  node: true
  mocha: true
  browser: false
  jquery: false
rules:
  # strict: [error, global]
  indent: [error, 2, {SwitchCase: 1}]
  linebreak-style: [error, unix]
  comma-dangle: [error, only-multiline]
  quotes: [error, single, {avoidEscape: true}]
  semi: [error, always]
  eqeqeq: error
  camelcase: error
  curly: [error, multi-line]
  brace-style: error
  radix: error
  yoda: error
  no-const-assign: error
  no-console: [error, {allow: [warn, error]}]
  no-var: error
  no-unused-vars: error
  require-yield: off
globals:
  sails: true
  TEntry: true
  EntryService: true
  TComment: true
  CommonService: true
  CommentService: true
  TCave: true
  TGrotto: true
  TCaver: true
  TTopography: true
  TokenAuthService: true
  ControllerService: true
  MappingV1Service: true
  L: true
  GeoLocService: true
  SettingsService: true
extends: [ 'eslint:recommended' ]
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    globalReturn: false
