module.exports = {
  id: undefined,
  dateInscription: undefined,
  dateReadAt: undefined,
  notified: undefined,
  notifier: undefined,
  cave: undefined,
  comment: undefined,
  description: undefined,
  document: undefined,
  entrance: undefined,
  history: undefined,
  location: undefined,
  massif: undefined,
  organization: undefined,
  rigging: undefined,
};
