const DOCUMENT_PROPERTIES = [
  '@context',
  '@id',
  '@type',
  'id',
  'dateInscription',
  'datePublication',
  'dateValidation',
  'isValidated',
  'validatorComment',
  'isDeleted',
  'redirectTo',
  'creator',
  'creatorComment',
  'authors',
  'authorsOrganization',
  'reviewer',
  'validator',
  'editor',
  'library',
  'type',
  'description',
  'subjects',
  'issue',
  'pages',
  'license',
  'languages',
  'files',
  'iso3166',
  'entrance',
  'cave',
  'massifs',
  'parent',
  'authorizationDocument',
];

module.exports = DOCUMENT_PROPERTIES;
