database_name: Grottocenter PostgreSQL
sqlalchemy_uri: postgresql+psycopg2://USERNAME:PASSWORD@dbserver:5432/grottoce
cache_timeout: null
expose_in_sqllab: true
allow_run_async: false
allow_ctas: false
allow_cvas: false
allow_dml: false
allow_file_upload: false
extra:
  allows_virtual_table_explore: true
impersonate_user: false
configuration_method: dynamic_form
uuid: fe17d436-4c72-475f-9db4-871ed305b379
version: 1.0.0
