-- phpMyAdmin SQL Dump
-- version 4.7.8
-- https://www.phpmyadmin.net/
--
-- Hôte : db
-- Généré le :  mer. 09 jan. 2019 à 11:12
-- Version du serveur :  5.7.18
-- Version de PHP :  7.2.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `grottoce`
--

-- --------------------------------------------------------

--
-- Structure de la table `t_bbs`
--

CREATE TABLE `t_bbs` (
  `XrefNumeriqueFinal` int(100) DEFAULT NULL,
  `ArticleTitle` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ArticleYear` int(5) DEFAULT NULL,
  `publication_export` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Abstract` varchar(10000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ChapterCode` float(20,3) DEFAULT NULL,
  `cros_chap_rebuilt` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CountryCode` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cros_country_rebuilt` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ref_` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `cAuthorsFull` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (ref_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Set XrefNumeriqueFinal as primary key and unique
ALTER TABLE `t_bbs` ADD PRIMARY KEY( `XrefNumeriqueFinal`); 
ALTER TABLE `t_bbs` ADD UNIQUE( `XrefNumeriqueFinal`); 

--
-- Exemples de données de la table `t_bbs`
--

INSERT INTO `t_bbs` (`ArticleTitle`, `ArticleYear`, `publication_export`, `Abstract`, `ChapterCode`, `cros_chap_rebuilt`, `CountryCode`, `cros_country_rebuilt`, `ref_`, `XrefNumeriqueFinal`, `cAuthorsFull`) VALUES
('The effect of pressure on aragonite dissolution rates in seawater', 1987, 'Geochim. et Cosmochim. Acta vol. 51 : 2171-2175.', NULL, 1.110, '1.13    ', NULL, NULL, '1988.0001', 198800010, 'J. G. ACKER;R. H. BYRNE;S. BEN-YAKOOV;R. A. FEELY;P. R. Betzer; ; ; ; ; '),
('Calcite dissolution kinetics in the system H20-CO2-CaCO3 with participation of foreign ions', 1987, 'Chemical geology 64 : 90-102.', 'Although foreign ions displace the calcite solution equilibria, by the effect of ion-strength, ion-pairing and the commonion effect, the kinetics of the dissolution process are hardly changed. Additional experiments with different limestones show that the effect of lithology on calcite dissolution kinetics is smali, even for rather impure limestones', 1.110, NULL, NULL, NULL, '1988.0002', 198800020, 'Dieter BUHMANN;Wolfgang DREYBRODT; ; ; ; ; ; ; ; '),
('(Balancing rocks)', 1988, 'Föld és ég 1988/1 : 6-9 (photos, figs. (hungar.)', 'The article informs about the origin and the typical occurence of balancing rocks, also mentioning that they can come into being by tropical karstification as well', 1.110, '1.15    ', NULL, 'H         ', '1988.0003', 198800030, 'Denes BALAZS; ; ; ; ; ; ; ; ; '),
('Les rapports entre formes de fond et formes de surface dans les paysages karstiques. \"Actes des Journées Felix Trombe, 1987\", t. 1', 1988, 'Mémoires S. C. Paris (14) : 37-42 (3 fig.).', 'La compréhension de ces rapports exige une égale connaissance des deux types de formes. L\'auteur se propose de rechercher une classification des différentes relations entre les formes et leurs divers rapports de \"causalité (interaction ?, évolution séparée ?). Ont été distingués, en prenant appui sur des exemples pris dans le Doubs, les rapports de causalité commune et les rapports de causalité directe : communication reprise des Trav. Inst. Géog. Reims, n°17, 1974', 1.110, NULL, NULL, NULL, '1988.0004', 198800040, 'Y. CALLOT; ; ; ; ; ; ; ; ; '),
('Le facteur lithologique - 2° partie : Roches solubles non carbonatées et karstification', 1988, 'Phénomènes karstiques, Série 41, éd. compte d\'auteur, vente S. C. Paris, 78 pp., 47 fig., 3 pl., ph.', 'Fait suite à \"Roches carbonatées et karstification\" (BBS nr. 87.0005). Rassemble les connaissances (littérature en langue non-française pour la plupart) sur les karsts en roche magmatique (granits, basaltes), en roche siliceuse (grès, quartzite), sur les karsts de gypse, de sel gemme, distinguant karst superficiel et karst profond. Reproduit de nombreux plans, bloc-diagrammes, cartes. Une table alphabétique (pp. 63-64) et une bibliographie abondante (pp. 67-73) complètent l\'ouvrage', 1.110, '1.21 8.3   ', NULL, NULL, '1988.0005', 198800050, 'J. CHOPPY; ; ; ; ; ; ; ; ; '),
('Surface stability considerations related to abstraction of ground water from dolomite', 1988, 'PWV Area 1988 : 80-85.', 'Workshop on dolomitic groundwater of the The effects of water level lowering by 5-10 m in different karst morphological zones (sinkholes, subsidences) are examined', 1.110, '6.2    ', NULL, NULL, '1988.0006\n', 198800060, 'J. H. DE BEER; ; ; ; ; ; ; ; ; '),
('Genèse des magasins karstiques. Analyse comparative des valeurs actuelles de la dissolution naturelle des roches carbonatées d\'après des exemples en Chine et dans d\'autres parties du monde', 1987, 'Carsologia sinica vol. 6, Nr. 2 : 127-130.', 'Discussion sur la genèse des magasins karstiques, sur les modes de calcul de la dissolution, sur les valeurs de la dissolution actuelle', 1.110, '1.21    ', NULL, NULL, '1988.0007', 198800070, 'Claude DROGUE;Daoxian YUAN; ; ; ; ; ; ; ; '),
('[Formation of karst cavities and comparison between carbonate rock dissolution rates in China and some other part of the world]', 1987, 'Carsologia sinica vol. 6 Nr. 2 : 131-136 (chines. ; engl. summ. )(5 fig.).', 'It is shown that climate conditions cast clear influence on carbonate dissolution rate', 1.110, NULL, NULL, NULL, '1988.0008', 198800080, 'Claude DROGUE;Daoxian YUAN; ; ; ; ; ; ; ; '),
('Experiments on kluftkarren and related lapies forms', 1988, 'Z. Geormoph. N. F. 32 (l) : 1-16, 4 fig. : 9 photos.', 'Experiments with fractured plaster-of-paris model blocks, the top surface of which is acted upon by artificial rain, yield close replicas of natural kluftkarren and derivative positive lapies forms. With progressing dissolution, the fractures are transformed into V-shaped lapies crevices, and the positive forms are seen to pass through a sequence of transformations which correspond closely to specific lapies forms observed in nature. -- It is suggested that the transformations and the resulting sequences of forms observed in experiments may also correspond to much larger karst landforms such as crevice karst, pinnacled karst of arète-and-pinnacle karst', 1.110, NULL, NULL, NULL, '1988.0009', 198800090, 'S. DZULYNSKI;E. GIL;J. RUDNICKI; ; ; ; ; ; ; '),
('A review of dissolution rills in limestone and other soluble rocks', 1987, 'Catena suppl. 8 : 119-140.', 'Solutional rills are classified and discussed by size, form and supposed mode of origin. The emphases is on hydraulics of flow, the basic distinction being between channels parallel to the direction of flow (the most common) and those which are transverse to flow (transverse ripples and flutëd scallops). The first group are further divided : (1) Microrills, controlled by capillary forces, (2) Gravitomorphic rills are subdivided into (a) those which head at the crest and extinguish downslope (Rillenkarren); (b) the Hortonian type which head below a belt of no channelled erosion and enlarge downslope (Rinnenkarren develop on bare rock, Rundkarren develop under a cover); (c) decantation forms which reduce in width and/or depth downslope : a point source produces Wzindkarren, a diffuse source produces a suite of parallel decantation flutings. In nature few rills have had a sample history. Many must be classified as polygenetic forms', 1.110, NULL, NULL, NULL, '1988.0010', 198800100, 'D. C. FORD;J. LUNDBERG; ; ; ; ; ; ; ; '),
('Tropical caves in retrospect and prospect', 1987, 'Progress in physical geography 11 (4) : 511-532, (4 fig., 2 tab.).', 'This article gives an overlook over recent studies in limestone caves of the humid tropics (with large bibliography). The author discusses specially the questions : are tropical caves significantly different in morphology and process to other limestone caves; what is their contribution to speleogenetic theory; can we use them to infer rates of surface landform development; and is their study of relevance to tropical countries, or is it a pursuit for adventurous dilettantes ?', 1.110, '1.21    ', NULL, NULL, '1988.0011', 198800110, 'David GILLIESON; ; ; ; ; ; ; ; ; '),
('[The corrosion of carbonates and environment temperaturel', 1987, 'Carsologia sinica vol. 6 (nr. 4) : 287-296 (chines. ; engl. summ.) (3 tabl., 13 fig.).', 'Tue dissolution speed of carbonates (limestone, dolomite) was studied. Low (0, 5°C) and high (80°C) temperature are unfavourable for dissolution of carbonates', 1.110, NULL, NULL, NULL, '1988.0012', 198800120, 'Shangyu HUANG;Huanrong SONG; ; ; ; ; ; ; ; '),
('Distribution coefficient of Mg++ ions between calcite and solutions at 10-15\'C', 1987, 'Marine Chemistry 20 : 327-336.', NULL, 1.110, NULL, NULL, NULL, '1988.0013', 198800130, 'Tamotsu OOMORI;Hiroshi KANESHIMA;Yoko MAEZATO; ; ; ; ; ; ; '),
('Modelle der Kalk-Auflösung und 13C/12C-Entwicklung von Karbonat-Grundwässern', 1987, 'Z. Wasser-Abwasser-Forsch. 20 : 69-81.', 'The subsurface dissolution of carbonate rocks is essentially controlled by dissolved biogenic C02, and occurs in hydrogeochemical systems which stand between two limiting cases. In industrial areas an additional dissolution by dissolved sulfur oxides from atmospheric pollution may occur. A model consideration of these processes requires data on the composition of groundwater with respect to the major components as well as data on the stable carbon isotopes of the dissolved carbonate, the carbonate rocks, and the soil-CO2 in the recharge area. It is further necessary to determine the quantities of the dissolved sulfate of geogenic and anthropogenic origin. The formal treatment of quantitative model considerations for various hydrogeochemical situations is deduced using the system CaCO3-CO2-SO3-H20', 1.110, '1.12    ', NULL, NULL, '1988.0014', 198800140, 'Karl Wolfram SCHAEFER;Eberhard USDOWSKI; ; ; ; ; ; ; ; '),
('Réflexions sur la dénomination de \"karst tropical\"', 1988, 'Regards 3 : 12-13, 2 ph. n-b.', 'Qu\'est, au juste, un karst tropical : tentative de définition. Interviennent des facteurs climatiques, mais aussi des facteurs autres, géologiques et tectoniques', 1.110, NULL, NULL, NULL, '1988.0015', 198800150, 'A. SLAGMOLEN; ; ; ; ; ; ; ; ; '),
('A deductive model of karst evolution based on hydrological probability', 1988, 'Earth surface processes and landforms 12 (3) : 271-288. 8 Fig., 6 Tab.', 'Combination of a conduit flow law with the exceedance probability of water levels higher than available relief is interpreted as the probability of surface as opposed to underground runoff. Very high probability of surface runoff implies a fluvial environment, whereas very low probabilities define a mature karst or \"holokarst\". Intermediate probabilities identify \"fluvio-karst\"', 1.110, '1.12    ', NULL, NULL, '1988.0016', 198800160, 'C. C. SMART; ; ; ; ; ; ; ; ; '),
('Ueber den tropischen Karst', 1988, 'Jahresber. Höhlenforschergr. Rhein-Main, 9 (für 1987) : 11-21, 5 Abb., 6 Phot.', 'Kurze Charakterisierung der 11 wichtigsten Regionen tropischen Karstes (dargestellt auf einer Karte, Abb. 1) mit Anmerkungen zum Erforschungsstand', 1.110, NULL, NULL, NULL, '1988.0017', 198800170, 'Georg SZENTES; ; ; ; ; ; ; ; ; '),
('Etch and intracutaneous landforms and their implications', 1987, 'Australian J. Earth Sci. 34 : 367-386.', 'Many landforms are formed by differential moisture attack, either controlled, or strongly influenced, by bedrock structure. Such landforms of subsurface derivatioii may be differentiated into etch or subcutaneous features that were initiated at the base of the regolitii, and intracutaneous forms that had their origin within the weathering zone', 1.110, '1.13    ', NULL, NULL, '1988.0018', 198800180, 'C. R. TWIDALE; ; ; ; ; ; ; ; ; '),
('[Dynamic simulation of carbonate rock dissolution]', 1988, 'Carsologia sinica vol. 7 (Nr. 1) : 63-72 (chines. ; engl. summ.) (6 fig.).', 'A new technique for study of the dissolution process of calcite resp. dolomite - H20-CO2 is presented', 1.110, NULL, NULL, NULL, '1988.0019', 198800190, 'Hongtao WANG;Yilin CAO; ; ; ; ; ; ; ; '),
('[The principle of karstification simulation in fissured-cavern carbonate rock region]', 1987, 'Carsologia sinica vol. 6 (nr. 4) : 275-285 (chines. ; engl. summ.) (2 fig.).', 'The modelling and calculating of karstification, the collecting and studying of basic data, the processing of the results are discussed', 1.110, NULL, NULL, NULL, '1988.0020', 198800200, 'Fengjun ZHU; ; ; ; ; ; ; ; ; '),
('Novo metodo para resoluçao da equaçao dos rebaixamentos em ensaios a caudal variavel', 1987, 'Geolis nr. 1- 100-103 (engl. summ.).', 'A new method for the computation of step-drawdown equation, useful in assessing well efficiency, is presented', 1.120, NULL, NULL, NULL, '1988.0021', 198800210, 'Carlos ALMEIDY; ; ; ; ; ; ; ; ; '),
('Selection of locations and intensity of level measurement of karst underground watercourses', 1987, 'Nas krs, Sarajevo, 13 (22) : 17-26 (6 figs.) (bilingual, serbo-croate - anglais).', 'Geological analysis enables definition of the underground flow zones while the selection of location conditions the utilization concept. In the first step the measurements are very intensive to define the system characteristics and in the second step the regime characteristics is determined', 1.120, NULL, NULL, NULL, '1988.0022', 198800220, 'I. AVDAGIC; ; ; ; ; ; ; ; ; '),
('Precipitation-runoff model for karstic regions', 1987, 'Nas krs, Sarajevo, 13 (22) : 5-12 (4 Figs.) (bilingual, serbo-croate - anglais).', 'Systematic measurements on calibrated sections, per segments with constant characteristics, enable determination of both runoff and water regime', 1.120, NULL, NULL, NULL, '1988.0023', 198800230, 'I. AVDAGIC;M. CIGANOVIC; ; ; ; ; ; ; ; '),
('Karst hydrology with special reference to the Dinaric karst', 1987, '210 pp., 114 figs., 19 tables.', 'Describes and locates numerous caves, resurgences, ponors, including brackish karst springs and fresh coastal springs. Contains a particular study of the hydrology of ponors and their water absorption capacity', 1.120, NULL, NULL, NULL, '1988.0024', 198800240, 'O. BONACCI; ; ; ; ; ; ; ; ; '),
('[Kernel fonction method and its application to karst water system]', 1988, 'Carsologia sinica vol. 7 nr. 2 : 89-99 (chines.; engl. summ.) (4 fig. 2 tabl.).', 'Only the linear program technique can be used to identify the correct kernel fonctions for obtaining the optimum forcasting equation. A case history is given', 1.120, NULL, NULL, 'China         ', '1988.0025', 198800250, 'Yilin CAO;Xiuhui XIE;Deyin XI; ; ; ; ; ; ; '),
('Expression de la dispersivité et équations stochastiques du transfert de masse en milieu fissuré théorique', 1988, 'Quatrième Coll. Hydro. en pays calcaire, Besançon, 29 sept. - 1 oct. 1988 - Ann. Sc. Univ. Besançon, géologie, Mémoire h. s., n°6, t. 1, p. 49-56.', 'Le modèle utilisé est constitué de fractures horizontales distribuées selon deux lois de répartition, l\'une étant une distribution exponentielle de l\'ouverture des fractures à largeur constante, l\'autre étant une distribution exponentielle de la section perpendiculaire à l\'écoulement. Pour chaque cas envisagé, l\'expression de la dispersivité a été établié; celle-ci montre, en plus d\'une dépendance des paramètres structuraux, une influence spatio-temporelle selon la première loi de répartition, et seulement spatiale selon la deuxième loi.', 1.120, '1.11    ', NULL, NULL, '1988.0026', 198800260, 'E. CARLIER; ; ; ; ; ; ; ; ; '),
('Aspects de la genèse des aquifères karstiques d\'après les taux actuels de la dégradation des roches carbonatées relevés sur un bassin témoin et en diverses régions du monde', 1987, 'Geolis nr. 1 : 115-123 (4 fig.).', 'Un bassin-témoin du Sud de la France est étudié et comparé aux taux de dissolution dans le monde (20 valeurs) La dégradation de la roche D (en m3 par km2 de bassin par an) est : log D = 0,783 log P - 1,766 (où P est la hauteur annuelle de pluie en mm). On montre que la mise en place d\'un magasin karstique peut être très rapide, le bassin-témoin perd annuellement par dissolution 9,47 m3 soit 0,00013% de son volume', 1.120, '1.11    ', NULL, 'F         ', '1988.0027', 198800270, 'Claude DROGUE; ; ; ; ; ; ; ; ; '),
('Hydrochimie et traitement informatique', 1987, 'D. E. A. de géologie, Univ. Aix-Marseille II, Inst.Géog., option géomorphologie, 7 p., note présentée en annexe au mémoire principal.', 'Présentation des calculs et d\'un programme', 1.120, NULL, NULL, NULL, '1988.0028', 198800280, 'P. DUREPAIRE; ; ; ; ; ; ; ; ; '),
('Gli acquiferi carsici', 1987, 'Speleologia n. 16 (S. S. I.), pagg. 28-30 (5 figures).', 'Revisione del concetto di acquifero carsico e sue caratteristiche principali; comportamento idrodinamico, diffusione degli inquinamenti e misure di protezione.', 1.120, NULL, NULL, NULL, '1988.0029', 198800290, 'Paolo FORTI; ; ; ; ; ; ; ; ; '),
('A device of fluorescent dye detection', 1987, 'J. speleol. Soc. Japan 12 : 50-51 (japan.; engl. summ.).', 'Fluorescence can be easily recognized by naked eyes in yellow dyed extract solutions from charcoal, by adding some grains of potassium hydroxide', 1.120, NULL, NULL, NULL, '1988.0030', 198800300, 'Atsushi FUJII; ; ; ; ; ; ; ; ; '),
('Lexique trilingue de l\'eau', 1988, 'Ed. P. Johanet et fils, 7, av. F. -D. Roosevelt 75008 Paris; 230p.', 'Equivalence des termes présentée en 3 parties : 1)- Français-Allemand-Anglais : p. 2 - 75. 2) - Anglais-Français-Allemand : p. 75 - 152. 3) - Allemand-Français-Anglais : p. 153 - 230. Pas de définition du terme cité, une abréviation permet de situer dans quelle discipline ce terme est plus usité. Précision sur son emploi grammatical', 1.120, '8.2    ', NULL, NULL, '1988.0031', 198800310, 'V. JOHANET; ; ; ; ; ; ; ; ; '),
('CHEN, Chongxi (1988) : [Analytic models of groundwater flows to karst springs]. ', 1988, 'Carsologia sinica vol. 7 (nr. 3) : 247-252 (chines.; engl. summ.).', 'Four conceptional analytic models, which describe the laminar or turbulent groundwater flow to karstic springs have been established respectively. The first two models show one dimentional flow and radial flow in accordance with the Darcy (linear) flow. The other two give the expression of one dimensional, resp. radial flow following non linear law', 1.120, NULL, NULL, 'China         ', '1988.0032', 198800320, 'Min LIN;Chongxi CHEN; ; ; ; ; ; ; ; '),
('(Some possibilities of collection of qualitative and quantitative hydrogeological elements in speleological objects)', 1988, 'Nas krs, Sarajevo, 14 (24-25) : 39-45 (en serbo-croate, résumé en anglais).', NULL, 1.120, NULL, NULL, NULL, '1988.0033', 198800330, 'M. MANDIC; ; ; ; ; ; ; ; ; '),
('Infiltration et environnement souterrain, le rôle de l\'eau sur les paramètres climatiques', 1988, '\"Actes des Journées Félix Trombe. 1987\", Mémoires S. C. Paris (14) : 78-98, 13 fig.', 'L\'étude quantitative de l\'environnement souterrain a pris son essor à partir des travaux de Trombe. Dans l\'approche traditionnel de la climatologie souterraine, la grotte est considérée comme le lieu privilégié des échanges liés aux facteurs physiques en jeu. Cette démarche a conduit à distinguer les grotte descendantes, ascendantes et à plusieurs ouvertures. Conjointement aux études de climatologie souterraine, l\'approche hydrogéologique des karsts s\'est développée et a été introduite la notion d\'aquifère. Il est apparu que l\'environnement souterrain ne pouvait se comprendre que dans le cadre du fonctionnement de la zone d\'infiltration de cet aquifère. A partir de ce constat une nouvelle approche des échanges (hydriques, gazeux ou thermiques) avec le milieu extérieur est proposée', 1.120, '1.24    ', NULL, NULL, '1988.0034', 198800340, 'A. MANGIN;C. ANDRIEUX; ; ; ; ; ; ; ; '),
('Guide pratique pour l\'usage des traceurs artificiels en hydrogéologie. Leitfaden für den Gebrauch kanstlicher Tracer in der Hydrogeologie', 1988, 'Ed. Société Géologique Suisse, groupe Hydrogéologues. Geolep EPFL Lausanne, Mai 1988 : 51 pages, 49 Seiten (bilingue).', 'Présentation des traceurs : produits courants (fluorescéine, rhodamine B etc.), moins courants (Tinopal, Borax etc.). et exceptionnels (radio-isotopes artificiels, activation neutronique, lycopodium etc.). Conseils pour l\'organisation des essais : choix des préparations et transport des traceurs; prise d\'échantillons; détermination de la quantité de traceurs; analyse et interprétation', 1.120, NULL, NULL, NULL, '1988.0035', 198800350, 'A. PARRIAUX;M, LISZKAY;I. MUELLER;G. DELLA VALLE; ; ; ; ; ; '),
('(The experiment results with ebb and flow spring models)', 1987, 'Acta carsologica, Ljubljana, 16 : 143-165 (9 Figs.) (en slovène, résumé en anglais).', 'Accessible in literature and on the base of his own ideas the author tested the ebb and flow springs activity, differing among height, pumping, passive and swinging manner of flowing. At all the tested ways the fonction of air plays an essential role. Several terms are introduced', 1.120, NULL, NULL, NULL, '1988.0036', 198800360, 'R. PODOBNIK; ; ; ; ; ; ; ; ; '),
('(The intermittent springs - never completely explained)', 1987, 'Idrijski razgledi, Idrija, 32 (2) : 55-58 (4 Figs.) (en slovène, pas de résumé).', 'Models for explaining the ebb and flow springs', 1.120, NULL, NULL, NULL, '1988.0037', 198800370, 'R. PODOBNIK; ; ; ; ; ; ; ; ; '),
('(A new knowledge on intermittent springs)', 1988, 'Proteus, Ljubljana, 50 (4) : 178-180 (3 Figs.) (en slovène, pas de résumé).', 'Although the first explanations date 300 years ago a lot is not yet solved. With different models the author tried to explain the fonction of ebb and flow springs', 1.120, NULL, NULL, NULL, '1988.0038', 198800380, 'R. PODOBNIK; ; ; ; ; ; ; ; ; '),
('Aproximaciones metodologicas al estudio del functionamiento hidrogeologico del karst', 1987, 'Geolis nr. 1 : 18-23 (rés. franç.).', 'On passe en revue les différentes méthodes d\'approximation à l\'étude de l\'hydrodynamique du karst. A partir de l\'étude de l\'hydrogramme on indique quelques critères qui permettent parfois de simuler les aquifères karstiques avec des méthodologies usuelles développées pour le milieu poreux', 1.120, NULL, NULL, NULL, '1988.0039', 198800390, 'Antonio PULIDO BOSCH; ; ; ; ; ; ; ; ; '),
('[The use of fluoresceine in tracing subterranean watercourses]', 1988, 'Speleo Nederland Pierk nr. 2/88 : 38-45 (dutch, engl. summ.).', 'The techniques of tracing, calculations and interpretation are exposed', 1.120, NULL, NULL, NULL, '1988.0040', 198800400, 'Theo A. M. VAN ES; ; ; ; ; ; ; ; ; '),
('[Study on the photochemical stability and adsorption of two major dye tracers]', 1987, 'Carsologia sinica vol. 6 (nr. 3) : 233-244 (chines.; engl. summ.) (11 fig., 4 tabl.).', 'Limestone, sand and organic matter will make a serious loss of the dye tracers, the adsorption of clay and quartz sand is negligible. The fluorescence of Tinopal CBS is decayed, the one of DY 96 increased by sunshine. The detector of untreated calico is more favourable than raw cotton', 1.120, NULL, NULL, NULL, '1988.0041', 198800410, 'Linhua SONG;P. L. SMART; ; ; ; ; ; ; ; '),
('Le piene', 1987, 'Grotte Torina nr. 95 : 42-46.', 'Tipi di piene : di scioglimento nivale; nivo-pluviali; pluviali. Idrogrammi tipici alle sorgenti delle Vene, alla grotta di Bossea', 1.120, NULL, NULL, 'IT         ', '1988.0042', 198800420, 'Meo VIGNA; ; ; ; ; ; ; ; ; '),
('[Application of microcomputer in analysing parameters of water-bearing formation : a method of common standard curve]', 1987, 'Carsologia sinica vol. 6, Nr. 2 : 101-110 (chines. ; engl. summ.).', 'Basic program annexed', 1.120, NULL, NULL, NULL, '1988.0043', 198800430, 'Xiangfeng XIAO; ; ; ; ; ; ; ; ; '),
('Iniciaçao à la geologia : Classificaçao e nomenclatura das rochas carbonatadas', 1987, 'Algarocho nr. 9 : 11-12.', NULL, 1.130, '7.6    ', NULL, NULL, '1988.0044', 198800440, 'Costa ALMEIDA; ; ; ; ; ; ; ; ; '),
('La formation des travertins : aspects géochimiques, essai de synthèse et discussion', 1988, 'Travaux n°XVII, UA n° 903 du CNRS et ATP-PIREN \"Histoire de l\'environnement et des phénomènes naturels\" : p. 261-268.', 'Les différentes études réalisées dans le cadre de ce travail pluridisciplinaire permettent de mieux comprendre la mise en place des travertins dans le Midi de la France. L\'auteur propose un protocole d\'étude des eaux incrustantes et des dépôts carbonatés associés (tufs et travertins) afin de maîtriser la signification paléoenvironnementale et historique de ces formations continentales. Description des processus en présence : physico-chimiques, physiques, biologiques…', 1.130, NULL, NULL, NULL, '1988.0045', 198800450, 'M. BAKALOWICZ; ; ; ; ; ; ; ; ; '),
('Les calcaires à crinoides', 1986, 'Persos 1 : 3-7, 2 croquis.', 'Que sont les crinoides, leur influence sur la karstification, quelques types de l\'ère primaire, biblio', 1.130, NULL, NULL, NULL, '1988.0046', 198800460, 'E. BERTRAND; ; ; ; ; ; ; ; ; '),
('[Tapes and features of tectonites in carbonate rocksj', 1987, 'Carsologia sinica vol. 6 (nr. 3) : 179-188 (chines.; engl. summ.) (8 fig.).', 'The carbonate-rock tectonites may be classified into fractured rocks (milled) breccias, cataclasited, mylonites and recrystallized tectonites', 1.130, NULL, NULL, NULL, '1988.0047', 198800470, 'Gongyu et al. LIU; ; ; ; ; ; ; ; ; '),
('Paleokarst. Publ', 1988, 'Springer Verlag New York Inc. 1988; 416 pp., figs. ISBN 0-387-96563-7 / 3-540-96563-7.', 'The book is devoted to the documentation and interpretation of karst in the geologic record. Part I consists of 7 papers dealing with general karst features and processes. Part II consists of Il papers documenting examples of paleokarst at scales ranging from Proterozoic to Cretaceous in age, documenting the kind of stratigraphic and sedimentological detail preserved in the rock record. Contents : (1) Characteristics of dissolutional cave systems in carbonate rocks (D. FORD); (2) Geochemical patterns in carbonate rocks (D. FORD); (2) Geochemical patterns of meteoric diagenetic systems and their application to studies of paleokarst (K. C. LOHMANN); (3) Controls on mineralogy and composition of spelean carbonates : Carlsbad caverns, New Mexico (L. A. GONZALES, K. C. LOHMANN); (4) Breccia-hosted lead-zinc deposits in carbonate rocks (D. F. SANGSTER); (5) Blackened limestone peebles : fire at subaerial unconformities (E. A. SHINN; B. H. LIDZ); (6) Holocene overprints of pleistocene paleokarst; Bight of Abaco, Bahamas (K. A. RASMUSSEN; A. C. NEUMANN); (7) Neptunian dikes and fissure fills : an overview and account of some modern examples (P. L. SMART; R. J. PALMER; F. WHITAKER; V. P. WRIGHT); (8) Proterozoic paleokarst profile, Dismal Lakes Group, N. W. T. Canada (C. KERANS; J. A. DONALDSON); (9) Early Paleozoic surface and subsurface paleokarst : Middle Ordovician carbonates, Mingan Islands, Quebec (A. DESROCHES; N. P. JAMES); (10) Ordovician Knox paleokarst unconformities, Appalachians (W. J. MUSSMAN; I. P. MONTANEZ; J. F. READ); (11) Surface and subsurface paleokarst, Silurian Lockport and Peebles Dolomites, Western Ohio (C. F. KAHLE); (12) Madison limestone (Mississippian) paleokarst : a geologic synthesis (W. J. SANDO); (13) Late Mississippian paleokarst and related mineral deposits, Leadville formation, Central Colorado (R. H. DE VOTO); (14) Paleokarstic features on Mississippian limestones, New Mexico (W. J. MEYERS); (15) Paleokarst and paleosols as indicators of paleoclimate and porosity evolution : a case study from the Carboniferous of South Wales (V. P. WRIGHT); (16) Caves and other features of Permian karst in San Andres dolomite, Yates Field reservoir, West Texas) (D. H. CRAIG); (17) Paleokarst and related pelagic sediments in the Jurassic of the Subbetic zone, southern Spain (J. A. VERA, P. A. RUIZ-ORTIZ, M. GARCIAHERNANDEZ, J. M. MOLINA); (18) Sedimentation and diagenesis along an island-sheltered platform margin, El Abra formation, Cretaceous of Mexico (C. J. MINERO)', 1.150, NULL, NULL, 'E UK USA CDN Mexico     ', '1988.0048', 198800480, 'N. P. JAMES;P. W. CHOQUETTE; ; ; ; ; ; ; ; '),
('(Karstification in klastites, evaporites and other stones)', 1987, 'Nas krs, Sarajevo, 13 (22) : 55-57 (en serbo-croate, résumé en anglais).', 'Basic principles of origin of caves in dolomites, clastites, evaporites and marls', 1.210, '1.4 1.5   ', NULL, NULL, '1988.0049', 198800490, 'M. BUTORAC; ; ; ; ; ; ; ; ; '),
('Oblitération d\'un conduit par néotectonique', 1987, 'Karstologia, n°9, p. 59, 1 ph.', 'Complément à l\'article publié par E. Gilli (Karstologia n°8/1986, p. 50-52). Choppy donne plusieurs exemples qui étayent la note de Gilli', 1.210, NULL, NULL, NULL, '1988.0050', 198800500, 'J. CHOPPY; ; ; ; ; ; ; ; ; '),
('Statistiques de directions de fractures et de conduits', 1988, '\"Actes des Journées Félix Trombe. 1987\", t. 1 Mémoires S. C. Paris, (14) : 123-130, 8 fig.', 'Critique de la méthode des corrélations statistiques entre directions de fractures mesurées en surface et directions des conduits, portant d\'abord sur la fiabilité des statistiques... puis sur la valeur de la méthode alors qu\'une pétition de principe camoufle parfois une non-corrélation de fait. En réalité, la fracturation ne peut être considérée comme déterminant les directions de conduits. Les écoulements souterrains sont généralement déterminés par des facteurs régionaux et non locaux, ils utilisent les fractures dans la mesure où elles permettent à l\'eau de parvenir à l\'émergence avec la perte de charge minimum. La pratique des corrélations entre directions de fractures et directions de conduits n\'est pas l\'outil permettant d\'expliquer le karst profond que l\'on a pu croire', 1.210, NULL, NULL, NULL, '1988.0051', 198800510, 'Jacques CHOPPY; ; ; ; ; ; ; ; ; '),
('Chemical dissolution of a porous medium by a reactive fluid', 1987, 'Physical Review Letters vol. 58 (nr. 5) : 479.', 'Chemical dissolution of a two-dimensional porous medium by a reactive fluid whicli produces fractal patterns is studied. A new model is proposed that introduces a cumkilative erosion process which broadens the bran c hes of the cluster and gives structures very similar to the evolution of the injection pressure with time which yields the fractal dimension is also presented, and agrees witli the experimental results', 1.210, NULL, NULL, NULL, '1988.0052', 198800520, 'Gérard DACCORD; ; ; ; ; ; ; ; ; '),
('Fractal patterns from chemical dissolution', 1987, 'Nature vol. 323 nr. 6099 : 41-43.', 'The dissolution patterns obtained experimentally by injecting water through pure plaster are fractal. These results should be of interest in nature (the formation of caves) and in the oil industry', 1.210, NULL, NULL, NULL, '1988.0053', 198800530, 'Gérard DACCORD;Roland LENORMAND; ; ; ; ; ; ; ; '),
('The kinetics of calcite dissolution and its consequences to karst evolution from the initial to the mature state', 1987, 'NSS Buil. 49 (nr. 2) : 31-49 (16 fig. and diagr., 2 tabl.).', 'The dissolution rates of calcite in the system CaCO3H20-CO2 are determined by three processes : (a) surface controlled dissolution at the solid-liquid interface, (b) diffusion of the molecular and ionic species, (c) slow conversion of C02 to H+ and HCO3-. A theory is presented, which taking these processes into consideration, predicts dissolution rates of calcite for (a) the case of a water-layer flowing on plane calcite surface with the 0ther surface in contact to a C02-containing atmo sphere (open system); and (b)for a water layer flowing between two parallel planar calcite surfaces (closed system). Both laminar and turbulent flow conditions have been considered. In the case of turbulent flow, the dissolution rates are higher by a factor of ten compared to laminer flow', 1.210, '1.11    ', NULL, NULL, '1988.0054', 198800540, 'Wolfang DREYBRODT; ; ; ; ; ; ; ; ; '),
('Some problems of karst morphometry', 1987, 'Studies in speleology vol. 7 : 17-22 (2 fig., 2 tabl.).The nature and applicability of a variety of morphometic indices capable of summarising aspects of cave systems, is reviewed. A list of morphometrie indices of 20 caves in the USSR is given (RB).88.0055', 'The nature and applicability of a variety of morphometic indices capable of summarising aspects of cave systems, is reviewed. A list of morphometrie indices of 20 caves in the USSR is given', 1.210, '8.1    ', NULL, 'RUSS         ', '1988.0055', 198800550, 'V. N. DUBLYANSKY;V. V. ILYUKHIN;Y. E. LOBANOV; ; ; ; ; ; ; '),
('A theory for the origin of Carlsbad Caverns', 1987, 'NSS Bull. 49 (nr. 2) : 73-76 (2 fig.).', 'According to a speleogenesis model for some caves in the Big Horn Basin, Wyoming, it is proposed that Carlsbad Caverns (New Mexico) were formed by ascending hydrogen sulfide waters and oxidation of H2S to sulfuric acid, reacting with the limestone and producing gypsum', 1.210, NULL, NULL, 'USA         ', '1988.0056', 198800560, 'Stephen J. ECEMEIER; ; ; ; ; ; ; ; ; '),
('L\'élargissement des conduits karstiques sous l\'action d\'eaux saturées', 1988, 'Actes des Coll. Sc. du XVI\' Cong. nat. Spéléol. 1985; in Spelunca Mémoires n°14, p. 100 (2 croquis).La régularisation des conduits noyés résulte aussi de réactions chimiques qui s\'équilibrent (RD).88.0057', 'La régularisation des conduits noyés résulte aussi de réactions chimiques qui s\'équilibrent', 1.210, NULL, NULL, NULL, '1988.0057', 198800570, 'Camille EK;Albert & GEWELT, Michel BRIFFOZ; ; ; ; ; ; ; ; '),
('La morfologia carsica ipogea : problemi relativi al suo utilizzo in speleogenesi. ', 1987, 'Geolis nr. 1 : 24-36 (7 fig.) (engl. summ.).', 'On démontre que des processus génétiques bien différents peuvent produire des morphologies karstiques hypogées convergentes identiques. Exemples : conduite forcée sous une crète; formation d\'un canyon (par évolution paragénétique antigravitationnelle ou par évolution singénétique gravitationnelle); formation de coupoles de vocite (formation phréatique; formation par bulles d\'air; formation par l\'eau de condensation); formation d\'une cavité en apparence tectonique', 1.210, NULL, NULL, NULL, '1988.0058', 198800580, 'Paolo FORTI; ; ; ; ; ; ; ; ; '),
('Defesa do papel dos factores dinamicos e da evoluçao na zona vadosa na espeleogenese (cont.) (Trad. C. Guerra)', 1987, 'Algarocho nr. 9 : 13-15.', NULL, 1.210, NULL, NULL, NULL, '1988.0059', 198800590, 'Bernard GEZE; ; ; ; ; ; ; ; ; '),
('Recherches sur le creusement et la stabilité des grands volumes karstiques souterrains (suite)', 1987, 'Spéléologie n° 138, p. 22-26, 2 cartes.', 'Localisation géographique des cavités françaises étudiées, hydrogéologie. Extrait de sa thèse, voir BBS 24/1985 : 85. 0256', 1.210, NULL, NULL, 'F         ', '1988.0060', 198800600, 'E. GILLI; ; ; ; ; ; ; ; ; '),
('Recherches sur le creusement et la stabilité des grands volumes karstiques souterrains (suite). - Les remplissages', 1987, 'Spéléologie n° 139, p. 11-14, 2 fig.', 'Types et évolution. Extrait de sa thèse; voir BBS 24/1985 : 85. 0256', 1.210, NULL, NULL, NULL, '1988.0061', 198800610, 'Eric GILLI; ; ; ; ; ; ; ; ; '),
('Recherches sur le creusement et la stabilité des grands volumes karstiques souterrains (suite) : Formes des cavités', 1988, 'Spéléologie n° 143, p. 6-9 (6 croquis). ', 'Conditions d\'observations et comparaison entre les formes observées. Extrait de sa thèse, voir BBS 24/1985 : 85. 0256', 1.210, NULL, NULL, NULL, '1988.0062', 198800620, 'Eric GILLI; ; ; ; ; ; ; ; ; '),
('Les vagues d\'érosion', 1987, 'Karstologia, n°10, P. 33-38, 7 fig, 2 ph.', 'Présentation des travaux de Cul, de Ph. Renault sur le sujet. Etudes hydrodynamique, hydrochimique. Considérations et interprétations mécaniques. Présentation de ces formes', 1.210, NULL, NULL, NULL, '1988.0063', 198800630, 'B. LISMONDE;A. LAGMADI; ; ; ; ; ; ; ; '),
('Field evidence of the minimum time for speleogenesis', 1987, 'NSS Bull. 49 (nr. 2) : 67-72 (6 fig.).', 'The data available (glacial field data, Bahamas data) strongly suggest that macroscopic solution conduits (r ˜lm) can develop in limestone in the time span of about 10\'000 years', 1.210, NULL, NULL, NULL, '1988.0064', 198800640, 'John E. MYLROIE;James L. CAREW; ; ; ; ; ; ; ; '),
('The formation and transformation mechanism of calcium carbonate in water', 1987, 'Geochimica et Cosmochimica Acta vol. 51 : 2757-2767.', 'Precipitated amorphous CaCO3 is transformed in crystalline polymorphs : vaterite + calcite at 14°-30°C and aragonite + calcite at 60°-80°C. Metastable polymorphs are gradually transformed to calcite : at 50°C vaterite is transformed to aragonite within 60 min and then the aragonite is transformed to calcite in 900 min. The polymorphic transformation is suggested to take place through dissolution of the metastable phase and growth of the stable phase (calcite)', 1.210, NULL, NULL, NULL, '1988.0065', 198800650, 'Takeshi OGINO;Toshio SUZUKI;Kiyoshi SAWADA; ; ; ; ; ; ; '),
('Cave levels and their interpretation', 1987, 'NSS Bull. 49 (nr. 2) : 50-66 (14 fig. and phot., 2 tabl.).', 'It is usually assumed that solution caves levels are controlled by fluvial base level, although stratigraphic influence must also be considered. Sharply defined cave levels with narrov vertical ranges appear to have formed in response to intermittent épisodes of rapid valley entrenchment, followed by a lenghtly period of vertually static base level. Some USA caves examples are commented', 1.210, NULL, NULL, 'USA         ', '1988.0066', 198800660, 'Arthur N. PALMER; ; ; ; ; ; ; ; ; '),
('(Some Considerations about the Fourrier Analyses and the Theory of the Cave-Passage Winding)', 1987, 'Nag krg, Sarajevo, 13 (22) : 27-37 (5 Figs.) (en slovène, résumé en anglais).', 'As cave passage meandring is not random, expressing the water course hydraulic properties as well as the geological parameters the author used the mathematical techniques based upon the trigonometrical polynomial as the best fitting tool. Different methods are discussed', 1.210, NULL, NULL, NULL, '1988.0067', 198800670, 'F. SUSTERSIC; ; ; ; ; ; ; ; ; '),
('Introduction to speleogenesis', 1987, 'NSS Bull. 49 (nr. 2) : 29-30.', 'Historical aspects and examples of contemporary research dealing with the origin of caves', 1.210, NULL, NULL, NULL, '1988.0068', 198800680, 'William B. WHITE; ; ; ; ; ; ; ; ; '),
('Thermoluminescence and radioluminescence in aragonite', 1988, 'Mineralogy and Petrology 39 : 39-53.', 'Thermoluminescence and radioluminescence wavenlength spectra of aragonite have been investigated and common luminescence features defined', 1.230, NULL, NULL, NULL, '1988.0069', 198800690, 'R. COY-YLL;T. CALDERON;M. AGUILAR; ; ; ; ; ; ; '),
('Thepiezoelectricity of the calcite', 1987, 'Trav. Inst. spéol. E. Racovitza t. 26 : 87-93 (2 tabl., 7 fig.).', 'Experimental data concerning the test of the phenomenon of piezoelectricity in calcite, marble and micritic limestone are given; the results are argued theoretically', 1.230, NULL, NULL, NULL, '1988.0070', 198800700, 'Gabriel DIACONU;Corina HADAREANU;Irina RUSU; ; ; ; ; ; ; '),
('The influence of grinding on the dissolution kinetics of calcite', 1987, 'Phys. Chem. Minerais 15 : 163-170.', NULL, 1.230, NULL, NULL, NULL, '1988.0071', 198800710, 'J. FERRET;R. GOUT;Y. KIHN;J. SEVELY; ; ; ; ; ; '),
('Untersuchungen an der Mondmilch aus dem Mondmilchloch (Pilatus und Modell der MondmilchGenese/Etudes sur le mondmilch présent au Mondmilchloch (Pilate) et modèle de la formation du mondmilch', 1987, 'Stalactite, 37 (1) : 3-10 (9 photos, 3 fig., 1 tabl.).', 'Discussion du terme mondmilch et des investigations (analyses chimiques, microscope électronique à balayage, lames minces) des échantillons du lieu-type Mondmilchloch (Suisse centrale). Proposition d\'un modèle de genèse : 1. Accumulation des cristaux de calcite en aiguilles et en bandes, 2. Formation d\'une pellicule d\'argile qui couvre la première couche de mondmilch. 3. Formation d\'une nouvelle génération de cristaux au dessus de l\'argile etc.', 1.230, NULL, NULL, 'SCH/A         ', '1988.0072', 198800720, 'Hans FISCHER; ; ; ; ; ; ; ; ; '),
('Morphologie der Mondmilch-Ablagerungen aus der Höhle Mondmilchloch', 1987, 'Stalactite, 37 (1) : 10-12 (3 fig., 1 photo).', 'Description morphologique du gisement de mondmilch au lieu-type (Suisse centrale). En couches sur les parois verticales et en \"choux-fleurs\" sur les plafonds. Par le changement des chemins d\'eau, quelques parties de la mondmilch sont fossilisées', 1.230, NULL, NULL, 'SCH/A         ', '1988.0073', 198800730, 'Hans FISCHER; ; ; ; ; ; ; ; ; '),
('Modell der Mondmilch-Genese', 1988, 'Actes 8e Congr. natl. SSS, 1987 : 85-86 (1 fig.).', 'Samples of moonmilk (Mondmilch) from the type locality Mondmilchloch (Central Switzerland) were analysed by chemical, optical (thin-sections) and x-ray-diffraction methods. A model of genesis is proposed : Accumulation of calcite crystals (needles, ledges) in layers which are separated by clay films', 1.230, NULL, NULL, 'SCH/A         ', '1988.0074', 198800740, 'Hans FISCHER; ; ; ; ; ; ; ; ; '),
('Rippled speleothems', 1988, 'Cave Science vol. 15, nr. 2 : 86-87.', 'Some critical observations about rippled speleothems, 4 phot.', 1.230, NULL, NULL, NULL, '1988.0075', 198800750, 'Trevor D. FORD; ; ; ; ; ; ; ; ; '),
('The calcite-aragonite transition : mechanism and microstructures induced by the transformation stresses and strain', 1987, 'Bull. Minéral. 110 : 481-496 (rés. franç.).', 'La transition calcite-aragonite est étudiée expérimentalement en conditions hydrostatiques et en présence de contraintes déviatoriques. La similitude de la morphologie des interfaces entre polymorphes ainsi que l\'existence de relations épitaxiales entre plans de faibles indices cristallographiques suggèrent que, quels que soient les conditions expérimentales et le sens de réaction, la transition se fait par le mouvement d\'interfaces cohérentes', 1.230, NULL, NULL, NULL, '1988.0076', 198800760, 'Philippe GILLET;Yves GERARD;Christian WILLAIME; ; ; ; ; ; ; '),
('Synthesis and distribution coefficient of low-magnesium calcites', 1987, 'Chemical Geology 64 : 79-87.', 'Low-Mg calcites of composition between 0, 5 and 3 mole% Mg-carbonate and equilibrium distribution coefficients interpretation', 1.230, NULL, NULL, NULL, '1988.0077', 198800770, 'M. R. HOWSON;A. D. PETHYBRIDGE;W. A. HOUSE; ; ; ; ; ; ; '),
('Salpetre in four European caves : chemical, historical and mineralogical aspects', 1988, 'J. Spelean History vol. 22 : 23 (only abstr. : NSS Convention, Hot Springs 1988).', 'Chemical evidence confirms salpetre in 4 known salpetre caves in Spain, France, West Germany, and probably the highly deliquescent nitrocalcite. Niter and nitromagnesite were obtained from leachates from cave sédiments of Sophienhöhle', 1.230, '6.2    ', NULL, 'D E F       ', '1988.0078', 198800780, 'David A. HUBBARD;Janet S. HERMAN;Richard S. MITCHELL;Elmar HAMMERSCHMIDT; ; ; ; ; ; '),
('Cristallisation des abîmes', 1987, 'Monde et Minéraux 81 : 8-11 (phot.).', 'Genèse et formes des concrétions calcitiques souterraines', 1.230, NULL, NULL, NULL, '1988.0079', 198800790, 'Jacques JOLFRE; ; ; ; ; ; ; ; ; '),
('Analyses de sections de stalactites par méthode d\'images numériques', 1988, 'Coll. : karst et quaternaire de la Basse-Seine Actes du Muséum de Rouen, 1988-I : 107-112, 4 fig.', 'Le système d\'acquisition vidéo d\'images numériques. Méthode de saisie et numérisation; traitement des résultats', 1.230, '7.3    ', NULL, NULL, '1988.0080', 198800800, 'Frédéric MAURY; ; ; ; ; ; ; ; ; '),
('Perle di roccia', 1988, 'Magazine ed., Milano, n.7, pp. 84?88, foto.', 'Articolo divulgativo sulla struttura delle pisoliti', 1.230, NULL, NULL, NULL, '1988.0081', 198800810, 'Riccardo SCIAKY; ; ; ; ; ; ; ; ; '),
('Perle di roccia', 1988, 'Magazine ed., Milano, n. 7, pp. 84-88, fato.', 'Articolo divulgativo sulla struttura delle pisoliti (EB). 88\' 0081 KIRCHMAYER, Martin (1987) : Universal stage grain fabric statistics on dendrites of mine cave pearl.Carbonates and evaporites vol. 2 (nr. 1) : 59-65. The symmetry elements of the causes of the growth and the symmetry elements of the effects (= the dendrites) are connected by the symmetry elements of the medium the calcite crystal). The main factor that trigger dendritic growth are the presence of supersaturated solutions. Cave-pearl dendrites (D) occur in three fabric types : nuclear D.; body D. (2-dimensional) and surface D. (3-dimensional)', 1.230, NULL, NULL, NULL, '1988.0082', 198800820, 'Riccardo SCIAKY; ; ; ; ; ; ; ; ; '),
('Wenn Tropfsteine aus dem Lot geraten', 1988, 'Höhlenpost, Nr. 77 : 30 (1 photo, 1 fig.).', 'Copie d\'un article de journal (1986) concernant la structure et la genèse des excentriques (capillaire central, vitesse et rhytme de croissance, quantité nécessaire de l\'eau etc.)', 1.230, NULL, NULL, NULL, '1988.0083', 198800830, 'André LAMBERT; ; ; ; ; ; ; ; ; '),
('Influence of temperature on the composition of magnesian calcite overgrowths precipitated from seawater', 1987, 'Geochimica et Cosmochimica Acta vol. 51 : 1977-1984.', NULL, 1.230, NULL, NULL, NULL, '1988.0084', 198800840, 'Alfonso MUCCI; ; ; ; ; ; ; ; ; '),
('Growth kinetics of epsomite MgSO4. 7H20', 1987, 'J. Crystal Growth 83 : 523-527.', NULL, 1.230, NULL, NULL, NULL, '1988.0085', 198800850, 'G. SGUALDINO;G. VACCARI; ; ; ; ; ; ; ; '),
('Zur Genese rezenter Karbonatbildungen in Dolomithbhlen Frankens. -', 1988, 'Karst u. Höhle, 1988 : 7-79, 37 Abb., 35 Tab., 18 Taf.', 'This article is focussed on the formation of recent carbonate speleothems collected from caves in dolomitic host rock. From June 1976 to May 1978 more than 3000 water samples were collected weekly in 8 caves of the Northern Franconian Alb. Some parameters, like temperature, pH, and conductivity, were measured on location. The concentration of Ca2+, mg2+, and HCO3 were analyzed later using standard methods. C02 partial pressure, ionic strength and saturation indices for calcite and dolomite were calculated by means of a computer program for data calculation. The interpretation of these data in relation to the composition of relevant speleothems revealed a complex model of carbonate formation in caves within dolomitic host rock : The main water supply for all investigated caves is limited to a few weeks before spring when the final thaw coincides with extended rainfalls. At the latest in May, highly concentrated karst waters reach the caves passing through the roof area. These waters obtained their high values in C02 during winter when the waters became snow or ice. With the increasing temperatures of the waters, highly aggressive solutions attack and dissolve dolomite along the soil-dolomite contact. Such solutions are characterized by a high C02 partial pressure contrary to a much smaller C02 concentration within the cave atmosphere. A rapid C02-diffusion into this atmosphere will develop immediately after the solution enters the cave system. Generally culminating in June, this C02diffusion will decrease until October/November when the C02 partial pressure in both, karst-waters and cave atmosphere, balance. In general, the precipitation/formation of carbonate speleothems is controlled by C02-diffusion from karst waters into the cave atmosphere; but the mineralogical composition of speleothems is dominated by the ratio of C02-diffusion to evaporation. The intensity of evaporation strongly relates to cave ventilation that is best developed in sack-caves close to the entrance area. Therefore, the most complex CaMg-carbonates are restricted to this area.', 1.230, NULL, NULL, 'D         ', '1988.0086', 198800860, 'Gerd F. TIETZ; ; ; ; ; ; ; ; ; '),
('Influence de l\'homme sur l\'environnement climatique souterrain', 1988, '\"Actes des Journées Félix Trombe 1987\", Mémoires t. 1 - Mémoires S. C. Paris, (14) : 96-122, 12 fig., 5 tab.', 'L\'homme produit de l\'énergie par sa surface corporelle et son appareil respiratoire. La peau émet de la chaleur et de l\'eau qui s\'évapore; les poumons produisent également de la chaleur et de la vapeur d\'eau mais aussi du gaz carbonique et de nombreux autres éléments d\'origine métabolique; ils consomment de l\'oxygène. Ces productions et consommations, évaluées en flux, augmentent considérablement avec le nombre de visiteurs. Si la galerie visitée, par son volume et son régime naturel d\'aération, ne peut pas éliminer l\'énergie fournie et les produits d\'origine métabolique, le climat et l\'environnement de cette galerie peuvent être profondément perturbés. A partir d\'exemples obtenus en grotte, il a été possible de quantifier les productions et consommations énergétiques humaines et de préciser le temps nécessaire à leur élimination. Une réglementation des visites, fondée sur les résultats obtenus, a été appliquée avec succès dans la grotte de Niaux (Ariège) depuis plusieurs années', 1.240, '6.4    ', NULL, 'F         ', '1988.0087', 198800870, 'Claude ANDRIEUX; ; ; ; ; ; ; ; ; '),
('Les états thermodynamiques de l\'atmosphère dans les cavités souterraines en milieu karstique (la condensation, l\'évaporation)', 1988, 'Bull. Liaison Soc. Biospéol., n°12, p. 3-9, 6 tb.', 'Avec une note p. 2 de M. J. Turquin : les condensations occultes…', 1.240, NULL, NULL, NULL, '1988.0088', 198800880, 'Cl. ANDRIEUX; ; ; ; ; ; ; ; ; '),
('Measurements of small changes in pressure of cave air using an air barometer', 1988, 'Helictite vol. 26 (nr. 1) : 32-38.', 'The construction and use of a simple barometer is described (2 tabl.; 2 fig.).', 1.240, NULL, NULL, NULL, '1988.0089', 198800890, 'Erik RALBERT; ; ; ; ; ; ; ; ; '),
('Evolution du C02 dans l\'endokarst exploré par les spéléologues - Relations fond-surface', 1988, 'Actes des Journées Félix Trombe 1987, t. 1 - Mémoires S. C. Paris, n°14, p. 74-77, 5 fig.', 'Seul le résumé a été publié, cette communication concerne les zones tempérées et tropicales', 1.240, NULL, NULL, NULL, '1988.0090', 198800900, 'R. MAIRE; ; ; ; ; ; ; ; ; '),
('Infiltration et environnement souterrain, le rôle de l\'eau sur les paramètres climatiques', 1988, '\"Actes des Journées Félix Trombe. 1987\", Mémoires S. C. Paris, 1988 (14) : 78-98, 13 fig.', 'L\'étude quantitative de l\'environnement souterrain a pris son essor à partir des travaux de Trombe. Dans l\'approche traditionnel de la climatologie souterraine, la grotte est considérée comme le lieu privilégié des échanges liés aux facteurs physiques en jeu… Cette démarche a conduit à distinguer les grottes descendantes, ascendantes et à plusieurs ouvertures. Conjointement aux études de climatologie souterraine, l\'appproche hydrogéologique des karsts s\'est développée et a été introduite la notion d\'aquifère. Il est apparu que l\'environnement souterrain ne pouvait se comprendre que dans le cadre du fonctionnem, nt de la zone d\'infiltration de cet aquifère. A partir de ce constat une nouvelle approche des échanges (hydriques, gazeux ou thermiques) avec le milieu extérieur est proposée.', 1.240, NULL, NULL, 'F         ', '1988.0091', 198800910, 'A. MANGIN;C. ANDRIEUX; ; ; ; ; ; ; ; '),
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
