\c grottoce;

INSERT INTO t_file_format ("extension","comment",mime_type,softwares) VALUES
	 (NULL,NULL,'application/activemessage',NULL),
	 ('ez          ',NULL,'application/andrew-inset',NULL),
	 ('anx         ',NULL,'application/annodex',NULL),
	 (NULL,NULL,'application/applefile',NULL),
	 ('atom        ',NULL,'application/atom+xml',NULL),
	 (NULL,NULL,'application/atomicmail',NULL),
	 (NULL,NULL,'application/batch-SMTP',NULL),
	 ('lin         ',NULL,'application/bbolin',NULL),
	 (NULL,NULL,'application/beep+xml',NULL),
	 (NULL,NULL,'application/cals-1840',NULL),
	 (NULL,NULL,'application/commonground',NULL),
	 ('cu          ',NULL,'application/cu-seeme',NULL),
	 (NULL,NULL,'application/cybercash',NULL),
	 (NULL,NULL,'application/dca-rft',NULL),
	 (NULL,NULL,'application/dec-dx',NULL),
	 ('dcm         ',NULL,'application/dicom',NULL),
	 (NULL,NULL,'application/docbook+xml',NULL),
	 ('tsp         ',NULL,'application/dsptype',NULL),
	 (NULL,NULL,'application/dvcs',NULL),
	 ('es          ',NULL,'application/ecmascript',NULL),
	 (NULL,NULL,'application/edi-consent',NULL),
	 (NULL,NULL,'application/edi-x12',NULL),
	 (NULL,NULL,'application/edifact',NULL),
	 ('epub        ',NULL,'application/epub+zip',NULL),
	 (NULL,NULL,'application/eshop',NULL),
	 ('otf         ',NULL,'application/font-sfnt',NULL),
	 ('pfr         ',NULL,'application/font-tdpfr',NULL),
	 ('woff        ',NULL,'application/font-woff',NULL),
	 ('spl         ',NULL,'application/futuresplash',NULL),
	 (NULL,NULL,'application/ghostview',NULL),
	 ('gz          ',NULL,'application/gzip',NULL),
	 ('hta         ',NULL,'application/hta',NULL),
	 (NULL,NULL,'application/http',NULL),
	 (NULL,NULL,'application/hyperstudio',NULL),
	 (NULL,NULL,'application/iges',NULL),
	 (NULL,NULL,'application/index',NULL),
	 (NULL,NULL,'application/index.cmd',NULL),
	 (NULL,NULL,'application/index.obj',NULL),
	 (NULL,NULL,'application/index.response',NULL),
	 (NULL,NULL,'application/index.vnd',NULL),
	 (NULL,NULL,'application/iotp',NULL),
	 (NULL,NULL,'application/ipp',NULL),
	 (NULL,NULL,'application/isup',NULL),
	 ('jar         ',NULL,'application/java-archive',NULL),
	 ('ser         ',NULL,'application/java-serialized-object',NULL),
	 ('class       ',NULL,'application/java-vm',NULL),
	 ('js          ',NULL,'application/javascript',NULL),
	 ('json        ',NULL,'application/json',NULL),
	 ('m3g         ',NULL,'application/m3g',NULL),
	 ('hqx         ',NULL,'application/mac-binhex40',NULL),
	 ('cpt         ',NULL,'application/mac-compactpro',NULL),
	 (NULL,NULL,'application/macwriteii',NULL),
	 (NULL,NULL,'application/marc',NULL),
	 ('nb          ',NULL,'application/mathematica',NULL),
	 ('mbox        ',NULL,'application/mbox',NULL),
	 (NULL,NULL,'application/ms-tnef',NULL),
	 ('mdb         ',NULL,'application/msaccess',NULL),
	 ('doc         ',NULL,'application/msword',NULL),
	 (NULL,NULL,'application/mxf',NULL),
	 (NULL,NULL,'application/news-message-id',NULL),
	 (NULL,NULL,'application/news-transmission',NULL),
	 (NULL,NULL,'application/ocsp-request',NULL),
	 (NULL,NULL,'application/ocsp-response',NULL),
	 ('bin         ',NULL,'application/octet-stream',NULL),
	 ('oda         ',NULL,'application/oda',NULL),
	 ('opf         ',NULL,'application/oebps-package+xml',NULL),
	 ('ogx         ',NULL,'application/ogg',NULL),
	 ('one         ',NULL,'application/onenote',NULL),
	 (NULL,NULL,'application/parityfec',NULL),
	 ('pdf         ',NULL,'application/pdf',NULL),
	 ('pgp         ',NULL,'application/pgp-encrypted',NULL),
	 ('key         ',NULL,'application/pgp-keys',NULL),
	 ('sig         ',NULL,'application/pgp-signature',NULL),
	 ('prf         ',NULL,'application/pics-rules',NULL),
	 (NULL,NULL,'application/pkcs10',NULL),
	 (NULL,NULL,'application/pkcs7-mime',NULL),
	 (NULL,NULL,'application/pkcs7-signature',NULL),
	 (NULL,NULL,'application/pkix-cert',NULL),
	 (NULL,NULL,'application/pkix-crl',NULL),
	 (NULL,NULL,'application/pkixcmp',NULL),
	 ('ps          ',NULL,'application/postscript',NULL),
	 (NULL,NULL,'application/prs.alvestrand.titrax-sheet',NULL),
	 (NULL,NULL,'application/prs.cww',NULL),
	 (NULL,NULL,'application/prs.nprend',NULL),
	 (NULL,NULL,'application/qsig',NULL),
	 ('rar         ',NULL,'application/rar',NULL),
	 ('rdf         ',NULL,'application/rdf+xml',NULL),
	 (NULL,NULL,'application/remote-printing',NULL),
	 (NULL,NULL,'application/riscos',NULL),
	 ('rtf         ',NULL,'application/rtf',NULL),
	 (NULL,NULL,'application/sdp',NULL),
	 (NULL,NULL,'application/set-payment',NULL),
	 (NULL,NULL,'application/set-payment-initiation',NULL),
	 (NULL,NULL,'application/set-registration',NULL),
	 (NULL,NULL,'application/set-registration-initiation',NULL),
	 (NULL,NULL,'application/sgml',NULL),
	 (NULL,NULL,'application/sgml-open-catalog',NULL),
	 (NULL,NULL,'application/sieve',NULL),
	 ('stl         ',NULL,'application/sla',NULL),
	 (NULL,NULL,'application/slate',NULL),
	 ('smi         ',NULL,'application/smil+xml',NULL),
	 (NULL,NULL,'application/timestamp-query',NULL),
	 (NULL,NULL,'application/timestamp-reply',NULL),
	 (NULL,NULL,'application/vemmi',NULL),
	 ('wasm        ',NULL,'application/wasm',NULL),
	 (NULL,NULL,'application/whoispp-query',NULL),
	 (NULL,NULL,'application/whoispp-response',NULL),
	 (NULL,NULL,'application/wita',NULL),
	 (NULL,NULL,'application/x400-bp',NULL),
	 ('xhtml       ',NULL,'application/xhtml+xml',NULL),
	 ('xml         ',NULL,'application/xml',NULL),
	 (NULL,NULL,'application/xml-dtd',NULL),
	 (NULL,NULL,'application/xml-external-parsed-entity',NULL),
	 ('xsl         ',NULL,'application/xslt+xml',NULL),
	 ('xspf        ',NULL,'application/xspf+xml',NULL),
	 ('zip         ',NULL,'application/zip',NULL),
	 (NULL,NULL,'application/vnd.3M.Post-it-Notes',NULL),
	 (NULL,NULL,'application/vnd.accpac.simply.aso',NULL),
	 (NULL,NULL,'application/vnd.accpac.simply.imp',NULL),
	 (NULL,NULL,'application/vnd.acucobol',NULL),
	 (NULL,NULL,'application/vnd.aether.imp',NULL),
	 ('apk         ',NULL,'application/vnd.android.package-archive',NULL),
	 (NULL,NULL,'application/vnd.anser-web-certificate-issue-initiation',NULL),
	 (NULL,NULL,'application/vnd.anser-web-funds-transfer-initiation',NULL),
	 (NULL,NULL,'application/vnd.audiograph',NULL),
	 (NULL,NULL,'application/vnd.bmi',NULL),
	 (NULL,NULL,'application/vnd.businessobjects',NULL),
	 (NULL,NULL,'application/vnd.canon-cpdl',NULL),
	 (NULL,NULL,'application/vnd.canon-lips',NULL),
	 ('cdy         ',NULL,'application/vnd.cinderella',NULL),
	 (NULL,NULL,'application/vnd.claymore',NULL),
	 (NULL,NULL,'application/vnd.commerce-battelle',NULL),
	 (NULL,NULL,'application/vnd.commonspace',NULL),
	 (NULL,NULL,'application/vnd.comsocaller',NULL),
	 (NULL,NULL,'application/vnd.contact.cmsg',NULL),
	 (NULL,NULL,'application/vnd.cosmocaller',NULL),
	 (NULL,NULL,'application/vnd.ctc-posml',NULL),
	 (NULL,NULL,'application/vnd.cups-postscript',NULL),
	 (NULL,NULL,'application/vnd.cups-raster',NULL),
	 (NULL,NULL,'application/vnd.cups-raw',NULL),
	 (NULL,NULL,'application/vnd.cybank',NULL),
	 ('deb         ',NULL,'application/vnd.debian.binary-package',NULL),
	 (NULL,NULL,'application/vnd.dna',NULL),
	 (NULL,NULL,'application/vnd.dpgraph',NULL),
	 (NULL,NULL,'application/vnd.dxr',NULL),
	 (NULL,NULL,'application/vnd.ecdis-update',NULL),
	 (NULL,NULL,'application/vnd.ecowin.chart',NULL),
	 (NULL,NULL,'application/vnd.ecowin.filerequest',NULL),
	 (NULL,NULL,'application/vnd.ecowin.fileupdate',NULL),
	 (NULL,NULL,'application/vnd.ecowin.series',NULL),
	 (NULL,NULL,'application/vnd.ecowin.seriesrequest',NULL),
	 (NULL,NULL,'application/vnd.ecowin.seriesupdate',NULL),
	 (NULL,NULL,'application/vnd.enliven',NULL),
	 (NULL,NULL,'application/vnd.epson.esf',NULL),
	 (NULL,NULL,'application/vnd.epson.msf',NULL),
	 (NULL,NULL,'application/vnd.epson.quickanime',NULL),
	 (NULL,NULL,'application/vnd.epson.salt',NULL),
	 (NULL,NULL,'application/vnd.epson.ssf',NULL),
	 (NULL,NULL,'application/vnd.ericsson.quickcall',NULL),
	 (NULL,NULL,'application/vnd.eudora.data',NULL),
	 (NULL,NULL,'application/vnd.fdf',NULL),
	 (NULL,NULL,'application/vnd.ffsns',NULL),
	 (NULL,NULL,'application/vnd.flographit',NULL),
	 ('sfd         ',NULL,'application/vnd.font-fontforge-sfd',NULL),
	 (NULL,NULL,'application/vnd.framemaker',NULL),
	 (NULL,NULL,'application/vnd.fsc.weblaunch',NULL),
	 (NULL,NULL,'application/vnd.fujitsu.oasys',NULL),
	 (NULL,NULL,'application/vnd.fujitsu.oasys2',NULL),
	 (NULL,NULL,'application/vnd.fujitsu.oasys3',NULL),
	 (NULL,NULL,'application/vnd.fujitsu.oasysgp',NULL),
	 (NULL,NULL,'application/vnd.fujitsu.oasysprs',NULL),
	 (NULL,NULL,'application/vnd.fujixerox.ddd',NULL),
	 (NULL,NULL,'application/vnd.fujixerox.docuworks',NULL),
	 (NULL,NULL,'application/vnd.fujixerox.docuworks.binder',NULL),
	 (NULL,NULL,'application/vnd.fut-misnet',NULL),
	 ('kml         ',NULL,'application/vnd.google-earth.kml+xml',NULL),
	 ('kmz         ',NULL,'application/vnd.google-earth.kmz',NULL),
	 (NULL,NULL,'application/vnd.grafeq',NULL),
	 (NULL,NULL,'application/vnd.groove-account',NULL),
	 (NULL,NULL,'application/vnd.groove-identity-message',NULL),
	 (NULL,NULL,'application/vnd.groove-injector',NULL),
	 (NULL,NULL,'application/vnd.groove-tool-message',NULL),
	 (NULL,NULL,'application/vnd.groove-tool-template',NULL),
	 (NULL,NULL,'application/vnd.groove-vcard',NULL),
	 (NULL,NULL,'application/vnd.hhe.lesson-player',NULL),
	 (NULL,NULL,'application/vnd.hp-HPGL',NULL),
	 (NULL,NULL,'application/vnd.hp-PCL',NULL),
	 (NULL,NULL,'application/vnd.hp-PCLXL',NULL),
	 (NULL,NULL,'application/vnd.hp-hpid',NULL),
	 (NULL,NULL,'application/vnd.hp-hps',NULL),
	 (NULL,NULL,'application/vnd.httphone',NULL),
	 (NULL,NULL,'application/vnd.hzn-3d-crossword',NULL),
	 (NULL,NULL,'application/vnd.ibm.MiniPay',NULL),
	 (NULL,NULL,'application/vnd.ibm.afplinedata',NULL),
	 (NULL,NULL,'application/vnd.ibm.modcap',NULL),
	 (NULL,NULL,'application/vnd.informix-visionary',NULL),
	 (NULL,NULL,'application/vnd.intercon.formnet',NULL),
	 (NULL,NULL,'application/vnd.intertrust.digibox',NULL),
	 (NULL,NULL,'application/vnd.intertrust.nncp',NULL),
	 (NULL,NULL,'application/vnd.intu.qbo',NULL),
	 (NULL,NULL,'application/vnd.intu.qfx',NULL),
	 (NULL,NULL,'application/vnd.irepository.package+xml',NULL),
	 (NULL,NULL,'application/vnd.is-xpr',NULL),
	 (NULL,NULL,'application/vnd.japannet-directory-service',NULL),
	 (NULL,NULL,'application/vnd.japannet-jpnstore-wakeup',NULL),
	 (NULL,NULL,'application/vnd.japannet-payment-wakeup',NULL),
	 (NULL,NULL,'application/vnd.japannet-registration',NULL),
	 (NULL,NULL,'application/vnd.japannet-registration-wakeup',NULL),
	 (NULL,NULL,'application/vnd.japannet-setstore-wakeup',NULL),
	 (NULL,NULL,'application/vnd.japannet-verification',NULL),
	 (NULL,NULL,'application/vnd.japannet-verification-wakeup',NULL),
	 (NULL,NULL,'application/vnd.koan',NULL),
	 (NULL,NULL,'application/vnd.lotus-1-2-3',NULL),
	 (NULL,NULL,'application/vnd.lotus-approach',NULL),
	 (NULL,NULL,'application/vnd.lotus-freelance',NULL),
	 (NULL,NULL,'application/vnd.lotus-notes',NULL),
	 (NULL,NULL,'application/vnd.lotus-organizer',NULL),
	 (NULL,NULL,'application/vnd.lotus-screencam',NULL),
	 (NULL,NULL,'application/vnd.lotus-wordpro',NULL),
	 (NULL,NULL,'application/vnd.mcd',NULL),
	 (NULL,NULL,'application/vnd.mediastation.cdkey',NULL),
	 (NULL,NULL,'application/vnd.meridian-slingshot',NULL),
	 (NULL,NULL,'application/vnd.mif',NULL),
	 (NULL,NULL,'application/vnd.minisoft-hp3000-save',NULL),
	 (NULL,NULL,'application/vnd.mitsubishi.misty-guard.trustweb',NULL),
	 (NULL,NULL,'application/vnd.mobius.daf',NULL),
	 (NULL,NULL,'application/vnd.mobius.dis',NULL),
	 (NULL,NULL,'application/vnd.mobius.msl',NULL),
	 (NULL,NULL,'application/vnd.mobius.plc',NULL),
	 (NULL,NULL,'application/vnd.mobius.txf',NULL),
	 (NULL,NULL,'application/vnd.motorola.flexsuite',NULL),
	 (NULL,NULL,'application/vnd.motorola.flexsuite.adsi',NULL),
	 (NULL,NULL,'application/vnd.motorola.flexsuite.fis',NULL),
	 (NULL,NULL,'application/vnd.motorola.flexsuite.gotap',NULL),
	 (NULL,NULL,'application/vnd.motorola.flexsuite.kmr',NULL),
	 (NULL,NULL,'application/vnd.motorola.flexsuite.ttc',NULL),
	 (NULL,NULL,'application/vnd.motorola.flexsuite.wem',NULL),
	 ('xul         ',NULL,'application/vnd.mozilla.xul+xml',NULL),
	 (NULL,NULL,'application/vnd.ms-artgalry',NULL),
	 (NULL,NULL,'application/vnd.ms-asf',NULL),
	 ('xls         ',NULL,'application/vnd.ms-excel',NULL),
	 ('xlam        ',NULL,'application/vnd.ms-excel.addin.macroEnabled.12',NULL),
	 ('xlsb        ',NULL,'application/vnd.ms-excel.sheet.binary.macroEnabled.12',NULL),
	 ('xlsm        ',NULL,'application/vnd.ms-excel.sheet.macroEnabled.12',NULL),
	 ('xltm        ',NULL,'application/vnd.ms-excel.template.macroEnabled.12',NULL),
	 ('eot         ',NULL,'application/vnd.ms-fontobject',NULL),
	 (NULL,NULL,'application/vnd.ms-lrm',NULL),
	 ('thmx        ',NULL,'application/vnd.ms-officetheme',NULL),
	 ('cat         ',NULL,'application/vnd.ms-pki.seccat',NULL),
	 ('stl         ',NULL,'#application/vnd.ms-pki.stl',NULL),
	 ('ppt         ',NULL,'application/vnd.ms-powerpoint',NULL),
	 ('ppam        ',NULL,'application/vnd.ms-powerpoint.addin.macroEnabled.12',NULL),
	 ('pptm        ',NULL,'application/vnd.ms-powerpoint.presentation.macroEnabled.12',NULL),
	 ('sldm        ',NULL,'application/vnd.ms-powerpoint.slide.macroEnabled.12',NULL),
	 ('ppsm        ',NULL,'application/vnd.ms-powerpoint.slideshow.macroEnabled.12',NULL),
	 ('potm        ',NULL,'application/vnd.ms-powerpoint.template.macroEnabled.12',NULL),
	 (NULL,NULL,'application/vnd.ms-project',NULL),
	 (NULL,NULL,'application/vnd.ms-tnef',NULL),
	 ('docm        ',NULL,'application/vnd.ms-word.document.macroEnabled.12',NULL),
	 ('dotm        ',NULL,'application/vnd.ms-word.template.macroEnabled.12',NULL),
	 (NULL,NULL,'application/vnd.ms-works',NULL),
	 (NULL,NULL,'application/vnd.mseq',NULL),
	 (NULL,NULL,'application/vnd.msign',NULL),
	 (NULL,NULL,'application/vnd.music-niff',NULL),
	 (NULL,NULL,'application/vnd.musician',NULL),
	 (NULL,NULL,'application/vnd.netfpx',NULL),
	 (NULL,NULL,'application/vnd.noblenet-directory',NULL),
	 (NULL,NULL,'application/vnd.noblenet-sealer',NULL),
	 (NULL,NULL,'application/vnd.noblenet-web',NULL),
	 (NULL,NULL,'application/vnd.novadigm.EDM',NULL),
	 (NULL,NULL,'application/vnd.novadigm.EDX',NULL),
	 (NULL,NULL,'application/vnd.novadigm.EXT',NULL),
	 ('pptx        ',NULL,'application/vnd.openxmlformats-officedocument.presentationml.presentation',NULL),
	 ('sldx        ',NULL,'application/vnd.openxmlformats-officedocument.presentationml.slide',NULL),
	 ('ppsx        ',NULL,'application/vnd.openxmlformats-officedocument.presentationml.slideshow',NULL),
	 ('potx        ',NULL,'application/vnd.openxmlformats-officedocument.presentationml.template',NULL),
	 ('xlsx        ',NULL,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',NULL),
	 ('xltx        ',NULL,'application/vnd.openxmlformats-officedocument.spreadsheetml.template',NULL),
	 ('docx        ',NULL,'application/vnd.openxmlformats-officedocument.wordprocessingml.document',NULL),
	 ('dotx        ',NULL,'application/vnd.openxmlformats-officedocument.wordprocessingml.template',NULL),
	 (NULL,NULL,'application/vnd.osa.netdeploy',NULL),
	 (NULL,NULL,'application/vnd.palm',NULL),
	 (NULL,NULL,'application/vnd.pg.format',NULL),
	 (NULL,NULL,'application/vnd.pg.osasli',NULL),
	 (NULL,NULL,'application/vnd.powerbuilder6',NULL),
	 (NULL,NULL,'application/vnd.powerbuilder6-s',NULL),
	 (NULL,NULL,'application/vnd.powerbuilder7',NULL),
	 (NULL,NULL,'application/vnd.powerbuilder7-s',NULL),
	 (NULL,NULL,'application/vnd.powerbuilder75',NULL),
	 (NULL,NULL,'application/vnd.powerbuilder75-s',NULL),
	 (NULL,NULL,'application/vnd.previewsystems.box',NULL),
	 (NULL,NULL,'application/vnd.publishare-delta-tree',NULL),
	 (NULL,NULL,'application/vnd.pvi.ptid1',NULL),
	 (NULL,NULL,'application/vnd.pwg-xhtml-print+xml',NULL),
	 (NULL,NULL,'application/vnd.rapid',NULL),
	 ('cod         ',NULL,'application/vnd.rim.cod',NULL),
	 (NULL,NULL,'application/vnd.s3sms',NULL),
	 (NULL,NULL,'application/vnd.seemail',NULL),
	 (NULL,NULL,'application/vnd.shana.informed.formdata',NULL),
	 (NULL,NULL,'application/vnd.shana.informed.formtemplate',NULL),
	 (NULL,NULL,'application/vnd.shana.informed.interchange',NULL),
	 (NULL,NULL,'application/vnd.shana.informed.package',NULL),
	 ('mmf         ',NULL,'application/vnd.smaf',NULL),
	 (NULL,NULL,'application/vnd.sss-cod',NULL),
	 (NULL,NULL,'application/vnd.sss-dtf',NULL),
	 (NULL,NULL,'application/vnd.sss-ntf',NULL),
	 (NULL,NULL,'application/vnd.street-stream',NULL),
	 (NULL,NULL,'application/vnd.svd',NULL),
	 (NULL,NULL,'application/vnd.swiftview-ics',NULL),
	 ('sis         ',NULL,'application/vnd.symbian.install',NULL),
	 (NULL,NULL,'application/vnd.triscape.mxs',NULL),
	 (NULL,NULL,'application/vnd.trueapp',NULL),
	 (NULL,NULL,'application/vnd.truedoc',NULL),
	 (NULL,NULL,'application/vnd.tve-trigger',NULL),
	 (NULL,NULL,'application/vnd.ufdl',NULL),
	 (NULL,NULL,'application/vnd.uplanet.alert',NULL),
	 (NULL,NULL,'application/vnd.uplanet.alert-wbxml',NULL),
	 (NULL,NULL,'application/vnd.uplanet.bearer-choice',NULL),
	 (NULL,NULL,'application/vnd.uplanet.bearer-choice-wbxml',NULL),
	 (NULL,NULL,'application/vnd.uplanet.cacheop',NULL),
	 (NULL,NULL,'application/vnd.uplanet.cacheop-wbxml',NULL),
	 (NULL,NULL,'application/vnd.uplanet.channel',NULL),
	 (NULL,NULL,'application/vnd.uplanet.channel-wbxml',NULL),
	 (NULL,NULL,'application/vnd.uplanet.list',NULL),
	 (NULL,NULL,'application/vnd.uplanet.list-wbxml',NULL),
	 (NULL,NULL,'application/vnd.uplanet.listcmd',NULL),
	 (NULL,NULL,'application/vnd.uplanet.listcmd-wbxml',NULL),
	 (NULL,NULL,'application/vnd.uplanet.signal',NULL),
	 (NULL,NULL,'application/vnd.vcx',NULL),
	 (NULL,NULL,'application/vnd.vectorworks',NULL),
	 (NULL,NULL,'application/vnd.vidsoft.vidconference',NULL),
	 ('vsd         ',NULL,'application/vnd.visio',NULL),
	 (NULL,NULL,'application/vnd.vividence.scriptfile',NULL),
	 (NULL,NULL,'application/vnd.wap.sic',NULL),
	 (NULL,NULL,'application/vnd.wap.slc',NULL),
	 ('wbxml       ',NULL,'application/vnd.wap.wbxml',NULL),
	 ('wmlc        ',NULL,'application/vnd.wap.wmlc',NULL),
	 ('wmlsc       ',NULL,'application/vnd.wap.wmlscriptc',NULL),
	 (NULL,NULL,'application/vnd.webturbo',NULL),
	 ('wpd         ',NULL,'application/vnd.wordperfect',NULL),
	 ('wp5         ',NULL,'application/vnd.wordperfect5.1',NULL),
	 (NULL,NULL,'application/vnd.wrq-hp3000-labelled',NULL),
	 (NULL,NULL,'application/vnd.wt.stf',NULL),
	 (NULL,NULL,'application/vnd.xara',NULL),
	 (NULL,NULL,'application/vnd.xfdl',NULL),
	 (NULL,NULL,'application/vnd.yellowriver-custom-menu',NULL),
	 (NULL,NULL,'application/zlib',NULL),
	 ('wk          ',NULL,'application/x-123',NULL),
	 ('7z          ',NULL,'application/x-7z-compressed',NULL),
	 ('abw         ',NULL,'application/x-abiword',NULL),
	 ('dmg         ',NULL,'application/x-apple-diskimage',NULL),
	 ('bcpio       ',NULL,'application/x-bcpio',NULL),
	 ('torrent     ',NULL,'application/x-bittorrent',NULL),
	 ('cab         ',NULL,'application/x-cab',NULL),
	 ('cbr         ',NULL,'application/x-cbr',NULL),
	 ('cbz         ',NULL,'application/x-cbz',NULL),
	 ('cdf         ',NULL,'application/x-cdf',NULL),
	 ('vcd         ',NULL,'application/x-cdlink',NULL),
	 ('pgn         ',NULL,'application/x-chess-pgn',NULL),
	 ('mph         ',NULL,'application/x-comsol',NULL),
	 (NULL,NULL,'application/x-core',NULL),
	 ('cpio        ',NULL,'application/x-cpio',NULL),
	 ('csh         ',NULL,'application/x-csh',NULL),
	 ('deb         ',NULL,'application/x-debian-package',NULL),
	 ('dcr         ',NULL,'application/x-director',NULL),
	 ('dms         ',NULL,'application/x-dms',NULL),
	 ('wad         ',NULL,'application/x-doom',NULL),
	 ('dvi         ',NULL,'application/x-dvi',NULL),
	 (NULL,NULL,'application/x-executable',NULL),
	 ('pfa         ',NULL,'application/x-font',NULL),
	 ('pcf         ',NULL,'application/x-font-pcf',NULL),
	 ('mm          ',NULL,'application/x-freemind',NULL),
	 ('spl         ',NULL,'application/x-futuresplash',NULL),
	 ('gan         ',NULL,'application/x-ganttproject',NULL),
	 ('gnumeric    ',NULL,'application/x-gnumeric',NULL),
	 ('sgf         ',NULL,'application/x-go-sgf',NULL),
	 ('gcf         ',NULL,'application/x-graphing-calculator',NULL),
	 ('gtar        ',NULL,'application/x-gtar',NULL),
	 ('tgz         ',NULL,'application/x-gtar-compressed',NULL),
	 (NULL,NULL,'application/x-hdf',NULL),
	 ('rhtml       ',NULL,'#application/x-httpd-eruby',NULL),
	 ('phtml       ',NULL,'#application/x-httpd-php',NULL),
	 ('phps        ',NULL,'#application/x-httpd-php-source',NULL),
	 ('php3        ',NULL,'#application/x-httpd-php3',NULL),
	 ('php3p       ',NULL,'#application/x-httpd-php3-preprocessed',NULL),
	 ('php4        ',NULL,'#application/x-httpd-php4',NULL),
	 ('php5        ',NULL,'#application/x-httpd-php5',NULL),
	 ('hwp         ',NULL,'application/x-hwp',NULL),
	 ('ica         ',NULL,'application/x-ica',NULL),
	 ('info        ',NULL,'application/x-info',NULL),
	 ('ins         ',NULL,'application/x-internet-signup',NULL),
	 ('iii         ',NULL,'application/x-iphone',NULL),
	 ('iso         ',NULL,'application/x-iso9660-image',NULL),
	 ('jam         ',NULL,'application/x-jam',NULL),
	 (NULL,NULL,'application/x-java-applet',NULL),
	 (NULL,NULL,'application/x-java-bean',NULL),
	 ('jnlp        ',NULL,'application/x-java-jnlp-file',NULL),
	 ('jmz         ',NULL,'application/x-jmol',NULL),
	 ('chrt        ',NULL,'application/x-kchart',NULL),
	 (NULL,NULL,'application/x-kdelnk',NULL),
	 ('kil         ',NULL,'application/x-killustrator',NULL),
	 ('skp         ',NULL,'application/x-koan',NULL),
	 ('kpr         ',NULL,'application/x-kpresenter',NULL),
	 ('ksp         ',NULL,'application/x-kspread',NULL),
	 ('kwd         ',NULL,'application/x-kword',NULL),
	 ('latex       ',NULL,'application/x-latex',NULL),
	 ('lha         ',NULL,'application/x-lha',NULL),
	 ('lyx         ',NULL,'application/x-lyx',NULL),
	 ('lzh         ',NULL,'application/x-lzh',NULL),
	 ('lzx         ',NULL,'application/x-lzx',NULL),
	 ('frm         ',NULL,'application/x-maker',NULL),
	 ('mif         ',NULL,'application/x-mif',NULL),
	 ('m3u8        ',NULL,'application/x-mpegURL',NULL),
	 ('application ',NULL,'application/x-ms-application',NULL),
	 ('manifest    ',NULL,'application/x-ms-manifest',NULL),
	 ('wmd         ',NULL,'application/x-ms-wmd',NULL),
	 ('wmz         ',NULL,'application/x-ms-wmz',NULL),
	 ('com         ',NULL,'application/x-msdos-program',NULL),
	 ('msi         ',NULL,'application/x-msi',NULL),
	 ('nc          ',NULL,'application/x-netcdf',NULL),
	 ('pac         ',NULL,'application/x-ns-proxy-autoconfig',NULL),
	 ('nwc         ',NULL,'application/x-nwc',NULL),
	 ('o           ',NULL,'application/x-object',NULL),
	 ('oza         ',NULL,'application/x-oz-application',NULL),
	 ('p7r         ',NULL,'application/x-pkcs7-certreqresp',NULL),
	 ('crl         ',NULL,'application/x-pkcs7-crl',NULL),
	 ('pyc         ',NULL,'application/x-python-code',NULL),
	 ('qgs         ',NULL,'application/x-qgis',NULL),
	 ('qtl         ',NULL,'application/x-quicktimeplayer',NULL),
	 ('rdp         ',NULL,'application/x-rdp',NULL),
	 ('rpm         ',NULL,'application/x-redhat-package-manager',NULL),
	 ('rss         ',NULL,'application/x-rss+xml',NULL),
	 ('rb          ',NULL,'application/x-ruby',NULL),
	 (NULL,NULL,'application/x-rx',NULL),
	 ('sci         ',NULL,'application/x-scilab',NULL),
	 ('xcos        ',NULL,'application/x-scilab-xcos',NULL),
	 ('sh          ',NULL,'application/x-sh',NULL),
	 ('shar        ',NULL,'application/x-shar',NULL),
	 (NULL,NULL,'application/x-shellscript',NULL),
	 ('swf         ',NULL,'application/x-shockwave-flash',NULL),
	 ('scr         ',NULL,'application/x-silverlight',NULL),
	 ('sql         ',NULL,'application/x-sql',NULL),
	 ('sit         ',NULL,'application/x-stuffit',NULL),
	 ('sv4cpio     ',NULL,'application/x-sv4cpio',NULL),
	 ('sv4crc      ',NULL,'application/x-sv4crc',NULL),
	 ('tar         ',NULL,'application/x-tar',NULL),
	 ('tcl         ',NULL,'application/x-tcl',NULL),
	 ('gf          ',NULL,'application/x-tex-gf',NULL),
	 ('pk          ',NULL,'application/x-tex-pk',NULL),
	 ('texinfo     ',NULL,'application/x-texinfo',NULL),
	 ('~           ',NULL,'application/x-trash',NULL),
	 ('t           ',NULL,'application/x-troff',NULL),
	 ('man         ',NULL,'application/x-troff-man',NULL),
	 ('me          ',NULL,'application/x-troff-me',NULL),
	 ('ms          ',NULL,'application/x-troff-ms',NULL),
	 ('ustar       ',NULL,'application/x-ustar',NULL),
	 (NULL,NULL,'application/x-videolan',NULL),
	 ('src         ',NULL,'application/x-wais-source',NULL),
	 ('wz          ',NULL,'application/x-wingz',NULL),
	 ('crt         ',NULL,'application/x-x509-ca-cert',NULL),
	 ('xcf         ',NULL,'application/x-xcf',NULL),
	 ('fig         ',NULL,'application/x-xfig',NULL),
	 ('xpi         ',NULL,'application/x-xpinstall',NULL),
	 ('xz          ',NULL,'application/x-xz',NULL),
	 (NULL,NULL,'audio/32kadpcm',NULL),
	 (NULL,NULL,'audio/3gpp',NULL),
	 ('amr         ',NULL,'audio/amr',NULL),
	 ('awb         ',NULL,'audio/amr-wb',NULL),
	 ('axa         ',NULL,'audio/annodex',NULL),
	 ('au          ',NULL,'audio/basic',NULL),
	 ('csd         ',NULL,'audio/csound',NULL),
	 ('flac        ',NULL,'audio/flac',NULL),
	 (NULL,NULL,'audio/g.722.1',NULL),
	 (NULL,NULL,'audio/l16',NULL),
	 ('mid         ',NULL,'audio/midi',NULL),
	 (NULL,NULL,'audio/mp4a-latm',NULL),
	 (NULL,NULL,'audio/mpa-robust',NULL),
	 ('mpga        ',NULL,'audio/mpeg',NULL),
	 ('m3u         ',NULL,'audio/mpegurl',NULL),
	 ('oga         ',NULL,'audio/ogg',NULL),
	 (NULL,NULL,'audio/parityfec',NULL),
	 ('sid         ',NULL,'audio/prs.sid',NULL),
	 (NULL,NULL,'audio/telephone-event',NULL),
	 (NULL,NULL,'audio/tone',NULL),
	 (NULL,NULL,'audio/vnd.cisco.nse',NULL),
	 (NULL,NULL,'audio/vnd.cns.anp1',NULL),
	 (NULL,NULL,'audio/vnd.cns.inf1',NULL),
	 (NULL,NULL,'audio/vnd.digital-winds',NULL),
	 (NULL,NULL,'audio/vnd.everad.plj',NULL),
	 (NULL,NULL,'audio/vnd.lucent.voice',NULL),
	 (NULL,NULL,'audio/vnd.nortel.vbk',NULL),
	 (NULL,NULL,'audio/vnd.nuera.ecelp4800',NULL),
	 (NULL,NULL,'audio/vnd.nuera.ecelp7470',NULL),
	 (NULL,NULL,'audio/vnd.nuera.ecelp9600',NULL),
	 (NULL,NULL,'audio/vnd.octel.sbc',NULL),
	 (NULL,NULL,'audio/vnd.qcelp',NULL),
	 (NULL,NULL,'audio/vnd.rhetorex.32kadpcm',NULL),
	 (NULL,NULL,'audio/vnd.vmx.cvsd',NULL),
	 ('aif         ',NULL,'audio/x-aiff',NULL),
	 ('gsm         ',NULL,'audio/x-gsm',NULL),
	 ('m3u         ',NULL,'audio/x-mpegurl',NULL),
	 ('wma         ',NULL,'audio/x-ms-wma',NULL),
	 ('wax         ',NULL,'audio/x-ms-wax',NULL),
	 (NULL,NULL,'audio/x-pn-realaudio-plugin',NULL),
	 ('ra          ',NULL,'audio/x-pn-realaudio',NULL),
	 ('ra          ',NULL,'audio/x-realaudio',NULL),
	 ('pls         ',NULL,'audio/x-scpls',NULL),
	 ('sd2         ',NULL,'audio/x-sd2',NULL),
	 ('wav         ',NULL,'audio/x-wav',NULL),
	 ('alc         ',NULL,'chemical/x-alchemy',NULL),
	 ('cac         ',NULL,'chemical/x-cache',NULL),
	 ('csf         ',NULL,'chemical/x-cache-csf',NULL),
	 ('cbin        ',NULL,'chemical/x-cactvs-binary',NULL),
	 ('cdx         ',NULL,'chemical/x-cdx',NULL),
	 ('cer         ',NULL,'chemical/x-cerius',NULL),
	 ('c3d         ',NULL,'chemical/x-chem3d',NULL),
	 ('chm         ',NULL,'chemical/x-chemdraw',NULL),
	 ('cif         ',NULL,'chemical/x-cif',NULL),
	 ('cmdf        ',NULL,'chemical/x-cmdf',NULL),
	 ('cml         ',NULL,'chemical/x-cml',NULL),
	 ('cpa         ',NULL,'chemical/x-compass',NULL),
	 ('bsd         ',NULL,'chemical/x-crossfire',NULL),
	 ('csml        ',NULL,'chemical/x-csml',NULL),
	 ('ctx         ',NULL,'chemical/x-ctx',NULL),
	 ('cxf         ',NULL,'chemical/x-cxf',NULL),
	 ('smi         ',NULL,'#chemical/x-daylight-smiles',NULL),
	 ('emb         ',NULL,'chemical/x-embl-dl-nucleotide',NULL),
	 ('spc         ',NULL,'chemical/x-galactic-spc',NULL),
	 ('inp         ',NULL,'chemical/x-gamess-input',NULL),
	 ('fch         ',NULL,'chemical/x-gaussian-checkpoint',NULL),
	 ('cub         ',NULL,'chemical/x-gaussian-cube',NULL),
	 ('gau         ',NULL,'chemical/x-gaussian-input',NULL),
	 ('gal         ',NULL,'chemical/x-gaussian-log',NULL),
	 ('gcg         ',NULL,'chemical/x-gcg8-sequence',NULL),
	 ('gen         ',NULL,'chemical/x-genbank',NULL),
	 ('hin         ',NULL,'chemical/x-hin',NULL),
	 ('istr        ',NULL,'chemical/x-isostar',NULL),
	 ('jdx         ',NULL,'chemical/x-jcamp-dx',NULL),
	 ('kin         ',NULL,'chemical/x-kinemage',NULL),
	 ('mcm         ',NULL,'chemical/x-macmolecule',NULL),
	 ('mmd         ',NULL,'chemical/x-macromodel-input',NULL),
	 ('mol         ',NULL,'chemical/x-mdl-molfile',NULL),
	 ('rd          ',NULL,'chemical/x-mdl-rdfile',NULL),
	 ('rxn         ',NULL,'chemical/x-mdl-rxnfile',NULL),
	 ('sd          ',NULL,'chemical/x-mdl-sdfile',NULL),
	 ('tgf         ',NULL,'chemical/x-mdl-tgf',NULL),
	 (NULL,NULL,'#chemical/x-mif',NULL),
	 ('mcif        ',NULL,'chemical/x-mmcif',NULL),
	 (NULL,NULL,'chemical/x-mol2',NULL),
	 ('b           ',NULL,'chemical/x-molconn-Z',NULL),
	 ('gpt         ',NULL,'chemical/x-mopac-graph',NULL),
	 ('mop         ',NULL,'chemical/x-mopac-input',NULL),
	 ('moo         ',NULL,'chemical/x-mopac-out',NULL),
	 ('mvb         ',NULL,'chemical/x-mopac-vib',NULL),
	 ('asn         ',NULL,'chemical/x-ncbi-asn1',NULL),
	 ('prt         ',NULL,'chemical/x-ncbi-asn1-ascii',NULL),
	 ('val         ',NULL,'chemical/x-ncbi-asn1-binary',NULL),
	 ('asn         ',NULL,'chemical/x-ncbi-asn1-spec',NULL),
	 ('pdb         ',NULL,'chemical/x-pdb',NULL),
	 ('ros         ',NULL,'chemical/x-rosdal',NULL),
	 ('sw          ',NULL,'chemical/x-swissprot',NULL),
	 ('vms         ',NULL,'chemical/x-vamas-iso14976',NULL),
	 ('vmd         ',NULL,'chemical/x-vmd',NULL),
	 ('xtel        ',NULL,'chemical/x-xtel',NULL),
	 ('xyz         ',NULL,'chemical/x-xyz',NULL),
	 ('ttc         ',NULL,'font/collection',NULL),
	 ('ttf         ',NULL,'font/otf',NULL),
	 ('ttf         ',NULL,'font/sfnt',NULL),
	 ('ttf         ',NULL,'font/ttf',NULL),
	 ('woff        ',NULL,'font/woff',NULL),
	 ('woff2       ',NULL,'font/woff2',NULL),
	 (NULL,NULL,'image/cgm',NULL),
	 (NULL,NULL,'image/g3fax',NULL),
	 ('gif         ',NULL,'image/gif',NULL),
	 ('ief         ',NULL,'image/ief',NULL),
	 ('jp2         ',NULL,'image/jp2',NULL),
	 ('jpeg        ',NULL,'image/jpeg',NULL),
	 ('jpm         ',NULL,'image/jpm',NULL),
	 ('jpx         ',NULL,'image/jpx',NULL),
	 (NULL,NULL,'image/naplps',NULL),
	 ('pcx         ',NULL,'image/pcx',NULL),
	 ('png         ',NULL,'image/png',NULL),
	 (NULL,NULL,'image/prs.btif',NULL),
	 (NULL,NULL,'image/prs.pti',NULL),
	 ('svg         ',NULL,'image/svg+xml',NULL),
	 ('tiff        ',NULL,'image/tiff',NULL),
	 (NULL,NULL,'image/vnd.cns.inf2',NULL),
	 ('djvu        ',NULL,'image/vnd.djvu',NULL),
	 (NULL,NULL,'image/vnd.dwg',NULL),
	 ('dxf         ',NULL,'image/vnd.dxf',NULL),
	 (NULL,NULL,'image/vnd.fastbidsheet',NULL),
	 (NULL,NULL,'image/vnd.fpx',NULL),
	 (NULL,NULL,'image/vnd.fst',NULL),
	 (NULL,NULL,'image/vnd.fujixerox.edmics-mmr',NULL),
	 (NULL,NULL,'image/vnd.fujixerox.edmics-rlc',NULL),
	 ('ico         ',NULL,'image/vnd.microsoft.icon',NULL),
	 (NULL,NULL,'image/vnd.mix',NULL),
	 (NULL,NULL,'image/vnd.net-fpx',NULL),
	 (NULL,NULL,'image/vnd.svf',NULL),
	 ('wbmp        ',NULL,'image/vnd.wap.wbmp',NULL),
	 (NULL,NULL,'image/vnd.xiff',NULL),
	 ('cr2         ',NULL,'image/x-canon-cr2',NULL),
	 ('crw         ',NULL,'image/x-canon-crw',NULL),
	 ('ras         ',NULL,'image/x-cmu-raster',NULL),
	 ('cdr         ',NULL,'image/x-coreldraw',NULL),
	 ('pat         ',NULL,'image/x-coreldrawpattern',NULL),
	 ('cdt         ',NULL,'image/x-coreldrawtemplate',NULL),
	 ('cpt         ',NULL,'image/x-corelphotopaint',NULL),
	 ('erf         ',NULL,'image/x-epson-erf',NULL),
	 (NULL,NULL,'image/x-icon',NULL),
	 ('art         ',NULL,'image/x-jg',NULL),
	 ('jng         ',NULL,'image/x-jng',NULL),
	 ('bmp         ',NULL,'image/x-ms-bmp',NULL),
	 ('nef         ',NULL,'image/x-nikon-nef',NULL),
	 ('orf         ',NULL,'image/x-olympus-orf',NULL),
	 ('psd         ',NULL,'image/x-photoshop',NULL),
	 ('pnm         ',NULL,'image/x-portable-anymap',NULL),
	 ('pbm         ',NULL,'image/x-portable-bitmap',NULL),
	 ('pgm         ',NULL,'image/x-portable-graymap',NULL),
	 ('ppm         ',NULL,'image/x-portable-pixmap',NULL),
	 ('rgb         ',NULL,'image/x-rgb',NULL),
	 ('xbm         ',NULL,'image/x-xbitmap',NULL),
	 ('xpm         ',NULL,'image/x-xpixmap',NULL),
	 ('xwd         ',NULL,'image/x-xwindowdump',NULL),
	 (NULL,NULL,'message/delivery-status',NULL),
	 (NULL,NULL,'message/disposition-notification',NULL),
	 (NULL,NULL,'message/external-body',NULL),
	 (NULL,NULL,'message/http',NULL),
	 (NULL,NULL,'message/s-http',NULL),
	 (NULL,NULL,'message/news',NULL),
	 (NULL,NULL,'message/partial',NULL),
	 ('eml         ',NULL,'message/rfc822',NULL),
	 ('igs         ',NULL,'model/iges',NULL),
	 ('msh         ',NULL,'model/mesh',NULL),
	 (NULL,NULL,'model/vnd.dwf',NULL),
	 (NULL,NULL,'model/vnd.flatland.3dml',NULL),
	 (NULL,NULL,'model/vnd.gdl',NULL),
	 (NULL,NULL,'model/vnd.gs-gdl',NULL),
	 (NULL,NULL,'model/vnd.gtw',NULL),
	 (NULL,NULL,'model/vnd.mts',NULL),
	 (NULL,NULL,'model/vnd.vtu',NULL),
	 ('wrl         ',NULL,'model/vrml',NULL),
	 ('x3dv        ',NULL,'model/x3d+vrml',NULL),
	 ('x3d         ',NULL,'model/x3d+xml',NULL),
	 ('x3db        ',NULL,'model/x3d+binary',NULL),
	 (NULL,NULL,'multipart/alternative',NULL),
	 (NULL,NULL,'multipart/appledouble',NULL),
	 (NULL,NULL,'multipart/byteranges',NULL),
	 (NULL,NULL,'multipart/digest',NULL),
	 (NULL,NULL,'multipart/encrypted',NULL),
	 (NULL,NULL,'multipart/form-data',NULL),
	 (NULL,NULL,'multipart/header-set',NULL),
	 (NULL,NULL,'multipart/mixed',NULL),
	 (NULL,NULL,'multipart/parallel',NULL),
	 (NULL,NULL,'multipart/related',NULL),
	 (NULL,NULL,'multipart/report',NULL),
	 (NULL,NULL,'multipart/signed',NULL),
	 (NULL,NULL,'multipart/voice-message',NULL),
	 ('appcache    ',NULL,'text/cache-manifest',NULL),
	 ('ics         ',NULL,'text/calendar',NULL),
	 ('css         ',NULL,'text/css',NULL),
	 ('csv         ',NULL,'text/csv',NULL),
	 (NULL,NULL,'text/directory',NULL),
	 (NULL,NULL,'text/english',NULL),
	 (NULL,NULL,'text/enriched',NULL),
	 ('323         ',NULL,'text/h323',NULL),
	 ('html        ',NULL,'text/html',NULL),
	 ('uls         ',NULL,'text/iuls',NULL),
	 ('mml         ',NULL,'text/mathml',NULL),
	 ('md          ',NULL,'text/markdown',NULL),
	 (NULL,NULL,'text/parityfec',NULL),
	 ('asc         ',NULL,'text/plain',NULL),
	 (NULL,NULL,'text/prs.lines.tag',NULL),
	 (NULL,NULL,'text/rfc822-headers',NULL),
	 ('rtx         ',NULL,'text/richtext',NULL),
	 (NULL,NULL,'text/rtf',NULL),
	 ('sct         ',NULL,'text/scriptlet',NULL),
	 (NULL,NULL,'text/t140',NULL),
	 ('tm          ',NULL,'text/texmacs',NULL),
	 ('tsv         ',NULL,'text/tab-separated-values',NULL),
	 ('ttl         ',NULL,'text/turtle',NULL),
	 (NULL,NULL,'text/uri-list',NULL),
	 ('vcf         ',NULL,'text/vcard',NULL),
	 (NULL,NULL,'text/vnd.abc',NULL),
	 (NULL,NULL,'text/vnd.curl',NULL),
	 (NULL,NULL,'text/vnd.debian.copyright',NULL),
	 (NULL,NULL,'text/vnd.DMClientScript',NULL),
	 (NULL,NULL,'text/vnd.flatland.3dml',NULL),
	 (NULL,NULL,'text/vnd.fly',NULL),
	 (NULL,NULL,'text/vnd.fmi.flexstor',NULL),
	 (NULL,NULL,'text/vnd.in3d.3dml',NULL),
	 (NULL,NULL,'text/vnd.in3d.spot',NULL),
	 (NULL,NULL,'text/vnd.IPTC.NewsML',NULL),
	 (NULL,NULL,'text/vnd.IPTC.NITF',NULL),
	 (NULL,NULL,'text/vnd.latex-z',NULL),
	 (NULL,NULL,'text/vnd.motorola.reflex',NULL),
	 (NULL,NULL,'text/vnd.ms-mediapackage',NULL),
	 ('jad         ',NULL,'text/vnd.sun.j2me.app-descriptor',NULL),
	 (NULL,NULL,'text/vnd.wap.si',NULL),
	 (NULL,NULL,'text/vnd.wap.sl',NULL),
	 ('wml         ',NULL,'text/vnd.wap.wml',NULL),
	 ('wmls        ',NULL,'text/vnd.wap.wmlscript',NULL),
	 ('bib         ',NULL,'text/x-bibtex',NULL),
	 ('boo         ',NULL,'text/x-boo',NULL),
	 ('h++         ',NULL,'text/x-c++hdr',NULL),
	 ('c++         ',NULL,'text/x-c++src',NULL),
	 (NULL,NULL,'text/x-chdr',NULL),
	 ('htc         ',NULL,'text/x-component',NULL),
	 (NULL,NULL,'text/x-crontab',NULL),
	 ('csh         ',NULL,'text/x-csh',NULL),
	 ('c           ',NULL,'text/x-csrc',NULL),
	 ('d           ',NULL,'text/x-dsrc',NULL),
	 ('diff        ',NULL,'text/x-diff',NULL),
	 ('hs          ',NULL,'text/x-haskell',NULL),
	 ('java        ',NULL,'text/x-java',NULL),
	 ('ly          ',NULL,'text/x-lilypond',NULL),
	 ('lhs         ',NULL,'text/x-literate-haskell',NULL),
	 (NULL,NULL,'text/x-makefile',NULL),
	 ('moc         ',NULL,'text/x-moc',NULL),
	 ('p           ',NULL,'text/x-pascal',NULL),
	 ('gcd         ',NULL,'text/x-pcs-gcd',NULL),
	 ('pl          ',NULL,'text/x-perl',NULL),
	 ('py          ',NULL,'text/x-python',NULL),
	 ('scala       ',NULL,'text/x-scala',NULL),
	 (NULL,NULL,'text/x-server-parsed-html',NULL),
	 ('etx         ',NULL,'text/x-setext',NULL),
	 ('sfv         ',NULL,'text/x-sfv',NULL),
	 ('sh          ',NULL,'text/x-sh',NULL),
	 ('tcl         ',NULL,'text/x-tcl',NULL),
	 ('tex         ',NULL,'text/x-tex',NULL),
	 ('vcs         ',NULL,'text/x-vcalendar',NULL),
	 ('3gp         ',NULL,'video/3gpp',NULL),
	 ('axv         ',NULL,'video/annodex',NULL),
	 ('dl          ',NULL,'video/dl',NULL),
	 ('dif         ',NULL,'video/dv',NULL),
	 ('fli         ',NULL,'video/fli',NULL),
	 ('gl          ',NULL,'video/gl',NULL),
	 ('mpeg        ',NULL,'video/mpeg',NULL),
	 ('ts          ',NULL,'video/MP2T',NULL),
	 ('mp4         ',NULL,'video/mp4',NULL),
	 ('qt          ',NULL,'video/quicktime',NULL),
	 (NULL,NULL,'video/mp4v-es',NULL),
	 ('ogv         ',NULL,'video/ogg',NULL),
	 (NULL,NULL,'video/parityfec',NULL),
	 (NULL,NULL,'video/pointer',NULL),
	 ('webm        ',NULL,'video/webm',NULL),
	 (NULL,NULL,'video/vnd.fvt',NULL),
	 (NULL,NULL,'video/vnd.motorola.video',NULL),
	 (NULL,NULL,'video/vnd.motorola.videop',NULL),
	 ('mxu         ',NULL,'video/vnd.mpegurl',NULL),
	 (NULL,NULL,'video/vnd.mts',NULL),
	 (NULL,NULL,'video/vnd.nokia.interleaved-multimedia',NULL),
	 (NULL,NULL,'video/vnd.vivo',NULL),
	 ('flv         ',NULL,'video/x-flv',NULL),
	 ('lsf         ',NULL,'video/x-la-asf',NULL),
	 ('mng         ',NULL,'video/x-mng',NULL),
	 ('asf         ',NULL,'video/x-ms-asf',NULL),
	 ('wm          ',NULL,'video/x-ms-wm',NULL),
	 ('wmv         ',NULL,'video/x-ms-wmv',NULL),
	 ('wmx         ',NULL,'video/x-ms-wmx',NULL),
	 ('wvx         ',NULL,'video/x-ms-wvx',NULL),
	 ('avi         ',NULL,'video/x-msvideo',NULL),
	 ('movie       ',NULL,'video/x-sgi-movie',NULL),
	 ('mpv         ',NULL,'video/x-matroska',NULL),
	 ('ice         ',NULL,'x-conference/x-cooltalk',NULL),
	 ('sisx        ',NULL,'x-epoc/x-sisx-app',NULL),
	 ('vrm         ',NULL,'x-world/x-vrml',NULL),
	 ('odt         ',NULL,'application/vnd.oasis.opendocument.text',NULL),
	 ('fodt        ',NULL,'application/vnd.oasis.opendocument.text-flat-xml',NULL),
	 ('ott         ',NULL,'application/vnd.oasis.opendocument.text-template',NULL),
	 ('oth         ',NULL,'application/vnd.oasis.opendocument.text-web',NULL),
	 ('odm         ',NULL,'application/vnd.oasis.opendocument.text-master',NULL),
	 ('otm         ',NULL,'application/vnd.oasis.opendocument.text-master-template',NULL),
	 ('odg         ',NULL,'application/vnd.oasis.opendocument.graphics',NULL),
	 ('fodg        ',NULL,'application/vnd.oasis.opendocument.graphics-flat-xml',NULL),
	 ('otg         ',NULL,'application/vnd.oasis.opendocument.graphics-template',NULL),
	 ('odp         ',NULL,'application/vnd.oasis.opendocument.presentation',NULL),
	 ('fodp        ',NULL,'application/vnd.oasis.opendocument.presentation-flat-xml',NULL),
	 ('otp         ',NULL,'application/vnd.oasis.opendocument.presentation-template',NULL),
	 ('ods         ',NULL,'application/vnd.oasis.opendocument.spreadsheet',NULL),
	 ('fods        ',NULL,'application/vnd.oasis.opendocument.spreadsheet-flat-xml',NULL),
	 ('ots         ',NULL,'application/vnd.oasis.opendocument.spreadsheet-template',NULL),
	 ('odc         ',NULL,'application/vnd.oasis.opendocument.chart',NULL),
	 ('odf         ',NULL,'application/vnd.oasis.opendocument.formula',NULL),
	 ('odi         ',NULL,'application/vnd.oasis.opendocument.image',NULL),
	 ('sxw         ',NULL,'application/vnd.sun.xml.writer',NULL),
	 ('stw         ',NULL,'application/vnd.sun.xml.writer.template',NULL),
	 ('sxg         ',NULL,'application/vnd.sun.xml.writer.global',NULL),
	 ('sdw         ',NULL,'application/vnd.stardivision.writer',NULL),
	 ('sgl         ',NULL,'application/vnd.stardivision.writer-global',NULL),
	 ('sxc         ',NULL,'application/vnd.sun.xml.calc',NULL),
	 ('stc         ',NULL,'application/vnd.sun.xml.calc.template',NULL),
	 ('sdc         ',NULL,'application/vnd.stardivision.calc',NULL),
	 ('sds         ',NULL,'application/vnd.stardivision.chart',NULL),
	 ('sxi         ',NULL,'application/vnd.sun.xml.impress',NULL),
	 ('sti         ',NULL,'application/vnd.sun.xml.impress.template',NULL),
	 ('sdd         ',NULL,'application/vnd.stardivision.impress',NULL),
	 ('sxd         ',NULL,'application/vnd.sun.xml.draw',NULL),
	 ('std         ',NULL,'application/vnd.sun.xml.draw.template',NULL),
	 ('sda         ',NULL,'application/vnd.stardivision.draw',NULL),
	 ('sxm         ',NULL,'application/vnd.sun.xml.math',NULL),
	 ('smf         ',NULL,'application/vnd.stardivision.math',NULL),
	 ('odb         ',NULL,'application/vnd.sun.xml.base',NULL),
	 ('oxt         ',NULL,'application/vnd.openofficeorg.extension',NULL),
	 ('ttf         ',NULL,'application/font-sfnt',NULL),
	 ('nbp         ',NULL,'application/mathematica',NULL),
	 ('dot         ',NULL,'application/msword',NULL),
	 ('mxf         ',NULL,'application/mxf',NULL),
	 ('deploy      ',NULL,'application/octet-stream',NULL),
	 ('onetoc2     ',NULL,'application/onenote',NULL),
	 ('ai          ',NULL,'application/postscript',NULL),
	 ('smil        ',NULL,'application/smil+xml',NULL),
	 ('xht         ',NULL,'application/xhtml+xml',NULL),
	 ('xsd         ',NULL,'application/xml',NULL),
	 ('xslt        ',NULL,'application/xslt+xml',NULL),
	 ('ddeb        ',NULL,'application/vnd.debian.binary-package',NULL),
	 ('xlb         ',NULL,'application/vnd.ms-excel',NULL),
	 ('pps         ',NULL,'application/vnd.ms-powerpoint',NULL),
	 ('vst         ',NULL,'application/vnd.visio',NULL),
	 ('cda         ',NULL,'application/x-cdf',NULL),
	 ('udeb        ',NULL,'application/x-debian-package',NULL),
	 ('dir         ',NULL,'application/x-director',NULL),
	 ('pfb         ',NULL,'application/x-font',NULL),
	 ('pcf.Z       ',NULL,'application/x-font-pcf',NULL),
	 ('taz         ',NULL,'application/x-gtar-compressed',NULL),
	 ('hdf         ',NULL,'application/x-hdf',NULL),
	 ('pht         ',NULL,'#application/x-httpd-php',NULL),
	 ('isp         ',NULL,'application/x-internet-signup',NULL),
	 ('skd         ',NULL,'application/x-koan',NULL),
	 ('kpt         ',NULL,'application/x-kpresenter',NULL),
	 ('kwt         ',NULL,'application/x-kword',NULL),
	 ('maker       ',NULL,'application/x-maker',NULL),
	 ('exe         ',NULL,'application/x-msdos-program',NULL),
	 ('pyo         ',NULL,'application/x-python-code',NULL),
	 ('shp         ',NULL,'application/x-qgis',NULL),
	 ('sce         ',NULL,'application/x-scilab',NULL),
	 ('swfl        ',NULL,'application/x-shockwave-flash',NULL),
	 ('sitx        ',NULL,'application/x-stuffit',NULL),
	 ('texi        ',NULL,'application/x-texinfo',NULL),
	 ('%           ',NULL,'application/x-trash',NULL),
	 ('tr          ',NULL,'application/x-troff',NULL),
	 ('snd         ',NULL,'audio/basic',NULL),
	 ('orc         ',NULL,'audio/csound',NULL),
	 ('midi        ',NULL,'audio/midi',NULL),
	 ('mpega       ',NULL,'audio/mpeg',NULL),
	 ('ogg         ',NULL,'audio/ogg',NULL),
	 ('aiff        ',NULL,'audio/x-aiff',NULL),
	 ('rm          ',NULL,'audio/x-pn-realaudio',NULL),
	 ('cache       ',NULL,'chemical/x-cache',NULL),
	 ('cascii      ',NULL,'chemical/x-cactvs-binary',NULL),
	 ('csm         ',NULL,'chemical/x-csml',NULL),
	 ('cef         ',NULL,'chemical/x-cxf',NULL),
	 ('embl        ',NULL,'chemical/x-embl-dl-nucleotide',NULL),
	 ('gam         ',NULL,'chemical/x-gamess-input',NULL),
	 ('fchk        ',NULL,'chemical/x-gaussian-checkpoint',NULL),
	 ('gjc         ',NULL,'chemical/x-gaussian-input',NULL),
	 ('ist         ',NULL,'chemical/x-isostar',NULL),
	 ('dx          ',NULL,'chemical/x-jcamp-dx',NULL),
	 ('mmod        ',NULL,'chemical/x-macromodel-input',NULL),
	 ('sdf         ',NULL,'chemical/x-mdl-sdfile',NULL),
	 ('mif         ',NULL,'#chemical/x-mif',NULL),
	 ('mol2        ',NULL,'chemical/x-mol2',NULL),
	 ('mopcrt      ',NULL,'chemical/x-mopac-input',NULL),
	 ('ent         ',NULL,'chemical/x-ncbi-asn1-ascii',NULL),
	 ('aso         ',NULL,'chemical/x-ncbi-asn1-binary',NULL),
	 ('ent         ',NULL,'chemical/x-pdb',NULL),
	 ('otf         ',NULL,'font/otf',NULL),
	 ('otf         ',NULL,'font/sfnt',NULL),
	 ('otf         ',NULL,'font/ttf',NULL),
	 ('jpg2        ',NULL,'image/jp2',NULL),
	 ('jpg         ',NULL,'image/jpeg',NULL),
	 ('jpf         ',NULL,'image/jpx',NULL),
	 ('svgz        ',NULL,'image/svg+xml',NULL),
	 ('tif         ',NULL,'image/tiff',NULL),
	 ('djv         ',NULL,'image/vnd.djvu',NULL),
	 ('iges        ',NULL,'model/iges',NULL),
	 ('mesh        ',NULL,'model/mesh',NULL),
	 ('vrml        ',NULL,'model/vrml',NULL),
	 ('icz         ',NULL,'text/calendar',NULL),
	 ('htm         ',NULL,'text/html',NULL),
	 ('markdown    ',NULL,'text/markdown',NULL),
	 ('txt         ',NULL,'text/plain',NULL),
	 ('wsc         ',NULL,'text/scriptlet',NULL),
	 ('vcard       ',NULL,'text/vcard',NULL),
	 ('hpp         ',NULL,'text/x-c++hdr',NULL),
	 ('cpp         ',NULL,'text/x-c++src',NULL),
	 ('h           ',NULL,'text/x-chdr',NULL),
	 ('patch       ',NULL,'text/x-diff',NULL),
	 ('pas         ',NULL,'text/x-pascal',NULL),
	 ('pm          ',NULL,'text/x-perl',NULL),
	 ('tk          ',NULL,'text/x-tcl',NULL),
	 ('ltx         ',NULL,'text/x-tex',NULL),
	 ('dv          ',NULL,'video/dv',NULL),
	 ('mpg         ',NULL,'video/mpeg',NULL),
	 ('mov         ',NULL,'video/quicktime',NULL),
	 ('lsx         ',NULL,'video/x-la-asf',NULL),
	 ('asx         ',NULL,'video/x-ms-asf',NULL),
	 ('mkv         ',NULL,'video/x-matroska',NULL),
	 ('vrml        ',NULL,'x-world/x-vrml',NULL),
	 ('vor         ',NULL,'application/vnd.stardivision.writer',NULL),
	 ('sdp         ',NULL,'application/vnd.stardivision.impress',NULL),
	 ('msu         ',NULL,'application/octet-stream',NULL),
	 ('onetmp      ',NULL,'application/onenote',NULL),
	 ('eps         ',NULL,'application/postscript',NULL),
	 ('udeb        ',NULL,'application/vnd.debian.binary-package',NULL),
	 ('xlt         ',NULL,'application/vnd.ms-excel',NULL),
	 ('vsw         ',NULL,'application/vnd.visio',NULL),
	 ('dxr         ',NULL,'application/x-director',NULL),
	 ('gsf         ',NULL,'application/x-font',NULL),
	 ('php         ',NULL,'#application/x-httpd-php',NULL),
	 ('skt         ',NULL,'application/x-koan',NULL),
	 ('frame       ',NULL,'application/x-maker',NULL),
	 ('bat         ',NULL,'application/x-msdos-program',NULL),
	 ('shx         ',NULL,'application/x-qgis',NULL),
	 ('bak         ',NULL,'application/x-trash',NULL),
	 ('roff        ',NULL,'application/x-troff',NULL),
	 ('sco         ',NULL,'audio/csound',NULL),
	 ('kar         ',NULL,'audio/midi',NULL),
	 ('mp2         ',NULL,'audio/mpeg',NULL),
	 ('opus        ',NULL,'audio/ogg',NULL),
	 ('aifc        ',NULL,'audio/x-aiff',NULL),
	 ('ram         ',NULL,'audio/x-pn-realaudio',NULL),
	 ('ctab        ',NULL,'chemical/x-cactvs-binary',NULL),
	 ('gamin       ',NULL,'chemical/x-gamess-input',NULL),
	 ('gjf         ',NULL,'chemical/x-gaussian-input',NULL),
	 ('mpc         ',NULL,'chemical/x-mopac-input',NULL),
	 ('jpe         ',NULL,'image/jpeg',NULL),
	 ('silo        ',NULL,'model/mesh',NULL),
	 ('shtml       ',NULL,'text/html',NULL),
	 ('text        ',NULL,'text/plain',NULL),
	 ('hxx         ',NULL,'text/x-c++hdr',NULL),
	 ('cxx         ',NULL,'text/x-c++src',NULL),
	 ('sty         ',NULL,'text/x-tex',NULL),
	 ('mpe         ',NULL,'video/mpeg',NULL),
	 ('wrl         ',NULL,'x-world/x-vrml',NULL),
	 ('msp         ',NULL,'application/octet-stream',NULL),
	 ('onepkg      ',NULL,'application/onenote',NULL),
	 ('epsi        ',NULL,'application/postscript',NULL),
	 ('vss         ',NULL,'application/vnd.visio',NULL),
	 ('skm         ',NULL,'application/x-koan',NULL),
	 ('fm          ',NULL,'application/x-maker',NULL),
	 ('dll         ',NULL,'application/x-msdos-program',NULL),
	 ('old         ',NULL,'application/x-trash',NULL),
	 ('mp3         ',NULL,'audio/mpeg',NULL),
	 ('spx         ',NULL,'audio/ogg',NULL),
	 ('zmt         ',NULL,'chemical/x-mopac-input',NULL),
	 ('pot         ',NULL,'text/plain',NULL),
	 ('hh          ',NULL,'text/x-c++hdr',NULL),
	 ('cc          ',NULL,'text/x-c++src',NULL),
	 ('cls         ',NULL,'text/x-tex',NULL),
	 ('epsf        ',NULL,'application/postscript',NULL),
	 ('fb          ',NULL,'application/x-maker',NULL),
	 ('sik         ',NULL,'application/x-trash',NULL),
	 ('m4a         ',NULL,'audio/mpeg',NULL),
	 ('brf         ',NULL,'text/plain',NULL),
	 ('eps2        ',NULL,'application/postscript',NULL),
	 ('book        ',NULL,'application/x-maker',NULL),
	 ('srt         ',NULL,'text/plain',NULL),
	 ('eps3        ',NULL,'application/postscript',NULL),
	 ('fbdoc       ',NULL,'application/x-maker',NULL),
	 ('tro         ',NULL,'application/vtopo',NULL),
	 ('dpt         ',NULL,'application/octet-stream',NULL),
	 ('trk         ',NULL,'application/octet-stream',NULL),
	 ('gpx         ',NULL,'application/gpx+xml',NULL),
	 ('th          ',NULL,'application/therion',NULL),
	 ('th2         ',NULL,'application/therion',NULL),
	 ('thc         ',NULL,'application/therion',NULL),
	 ('xvi         ',NULL,'application/therion',NULL),
	 ('lox         ',NULL,'application/therion',NULL);