\c grottoce;
INSERT INTO public.t_right (id, "name", "comments")
VALUES (1, 'Application - view any', NULL),
    (2, 'Application - edit any', NULL),
    (3, 'Application - delete any', NULL),
    (4, 'Document - view any', NULL),
    (5, 'Document - edit any', NULL),
    (6, 'Document - delete any', NULL),
    (7, 'Cave - view any', NULL),
    (8, 'Cave - edit any', NULL),
    (9, 'Cave - delete any', NULL),
    (10, 'Caver - view any', NULL),
    (11, 'Caver - edit any', NULL),
    (12, 'Caver - delete any', NULL),
    (13, 'Entrance - view complete', NULL),
    (14, 'Caver - view complete', NULL),
    (20, 'Entrance - edit any', NULL),
    (21, 'Entrance - delete any', NULL),
    (22, 'Organization - view any', NULL),
    (23, 'Organization - edit any', NULL),
    (24, 'Organization - delete any', NULL),
    (25, 'Group - view any', NULL),
    (26, 'Group - edit any', NULL),
    (27, 'Group - delete any', NULL),
    (34, 'Massif - view any', NULL),
    (35, 'Massif - edit any', NULL),
    (36, 'Massif - delete any', NULL),
    (40, 'Right - view any', NULL),
    (41, 'Right - edit any', NULL),
    (42, 'Right - delete any', NULL),
    (50, 'Caver - edit own', NULL),
    (51, 'Caver - delete own', NULL),
    (75, 'File - view any', NULL),
    (76, 'File - edit any', NULL),
    (77, 'File - delete any', NULL),
    (78, 'File - create', NULL),
    (79, 'Document - create', NULL),
    (80, 'Cave - create', NULL),
    (81, 'Caver - create', NULL),
    (82, 'Entrance - create', NULL),
    (83, 'Organization - create', NULL),
    (84, 'Group - create', NULL),
    (85, 'Massif - create', NULL),
    (86, 'Right - create', NULL),
    (87, 'Entrance - view limited', NULL),
    (88, 'Application - merge duplicates', NULL),
    (89, 'Entrance - link resource', NULL),
    (90, 'Entrance - unlink resource', NULL),
    (91, 'Cave - link resource', NULL),
    (92, 'Cave - unlink resource', NULL),
    (93, 'Description - edit any', NULL),
    (95, 'Name - edit any', NULL),
    (97, 'Description - create', NULL),
    (98, 'Location - edit any', NULL),
    (99, 'Location - create', NULL),
    (100, 'Application - no request limit', NULL),
    (101, 'Document - edit not validated', NULL),
    (102, 'Document - csv import', NULL),
    (103, 'Entrance - csv import', NULL),
    (104, 'Cave - merge', NULL),
    (105, 'Application - no moderator delete request limit', NULL),
    (106, 'Application - no user delete request limit', NULL),
    (107, 'Document Duplicate - create', NULL),
    (108, 'Entrance Duplicate - create', NULL),
    (109, 'Document Duplicate - delete any', NULL),
    (110, 'Entrance Duplicate - delete any', NULL),
    (111, 'Entrance - mark as sensitive', NULL),
    (112, 'Entrance - unmark as sensitive', NULL);
