\c grottoce;
INSERT INTO public.t_right (id,name,"comments") VALUES
	 (1,'Application - view any',NULL),
	 (2,'Application - edit any',NULL),
	 (3,'Application - delete any',NULL),
	 (4,'Document - view any',NULL),
	 (5,'Document - edit any',NULL),
	 (6,'Document - delete any',NULL),
	 (7,'Cave - view any',NULL),
	 (8,'Cave - edit any',NULL),
	 (9,'Cave - delete any',NULL),
	 (10,'Caver - view any',NULL),
	 (11,'Caver - edit any',NULL),
	 (12,'Caver - delete any',NULL),
	 (20,'Entrance - edit any',NULL),
	 (21,'Entrance - delete any',NULL),
	 (22,'Organization - view any',NULL),
	 (23,'Organization - edit any',NULL),
	 (24,'Organization - delete any',NULL),
	 (25,'Group - view any',NULL),
	 (26,'Group - edit any',NULL),
	 (27,'Group - delete any',NULL),
	 (34,'Massif - view any',NULL),
	 (35,'Massif - edit any',NULL),
	 (36,'Massif - delete any',NULL),
	 (40,'Right - view any',NULL),
	 (41,'Right - edit any',NULL),
	 (42,'Right - delete any',NULL),
	 (50,'Caver - edit own',NULL),
	 (51,'Caver - delete own',NULL),
	 (74,'File - view any',NULL),
	 (75,'File - edit any',NULL),
	 (76,'File - delete any',NULL),
	 (77,'File - create',NULL),
	 (78,'Document - create',NULL),
	 (79,'Cave - create',NULL),
	 (80,'Caver - create',NULL),
	 (81,'Entrance - create',NULL),
	 (82,'Organization - create',NULL),
	 (83,'Group - create',NULL),
	 (84,'Massif - create',NULL),
	 (85,'Right - create',NULL),
	 (86,'Entrance - view complete',NULL),
	 (87,'Application - merge duplicates',NULL),
	 (88,'Entrance - view limited',NULL),
	 (89,'Caver - view complete',NULL),
	 (90,'Entrance - link resource',NULL),
	 (91,'Entrance - unlink resource',NULL),
	 (92,'Cave - link resource',NULL),
	 (93,'Cave - unlink resource',NULL),
	 (95,'Description - edit any',NULL),
	 (96,'Name - edit any',NULL),
	 (97,'Name - edit own',NULL),
	 (98,'Location - edit any',NULL),
	 (100,'Description - create',NULL),
	 (101,'Location - create',NULL),
	 (104,'Document - edit not validated',NULL),
	 (105,'Document - csv import',NULL),
	 (106,'Entrance - csv import',NULL),
	 (107,'Cave - merge',NULL),
	 (110,'Document Duplicate - create',NULL),
	 (111,'Entrance Duplicate - create',NULL),
	 (112,'Document Duplicate - delete any',NULL),
	 (113,'Entrance Duplicate - delete any',NULL),
	 (114,'Entrance - mark as sensitive',NULL),
	 (115,'Entrance - unmark as sensitive',NULL),
	 (116,'History - edit any',NULL),
	 (117,'History - create',NULL),
	 (118,'Comment - edit any',NULL),
	 (119,'Comment - create',NULL),
   (120,'Rigging - edit any',NULL),
   (121,'Rigging - create',NULL),
   (122,'Country - subscribe',NULL),
   (123,'Massif - subscribe',NULL),
   (124,'Comment - edit own',NULL);
