\c grottoce;

INSERT INTO t_subject (code, subject, code_parent, url, dewey_cote, dewey_topic) VALUES
('1','KARSTOLOGY AND GEOSPELEOLOGY','1','https://ontology.uis-speleo.org/ontology/#karstologyAndGeospeleology','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1','KARSTOLOGY','1','https://ontology.uis-speleo.org/ontology/#karstology','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.0','Karstology general topics','1','https://ontology.uis-speleo.org/ontology/#karstologyGeneralTopics','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.0.1','Karst processes and phenomena; karst systems: definitions, structure, functioning, karstogenetic environments','1','https://ontology.uis-speleo.org/ontology/#karstProcessesAndPhenomena','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.0.2','Typology and classifications of karst','1','https://ontology.uis-speleo.org/ontology/#typologyAndClassificationsOfKarst','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.0.3','Physical chemistry of karst processes, numerical models','1','https://ontology.uis-speleo.org/ontology/#physicalChemistryOfKarstProcesses','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.0.4','Dissolution from field observations, solution rates','1','https://ontology.uis-speleo.org/ontology/#dissolutionFromFieldObservations','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.1','Karst morphology and morphogenesis','1','https://ontology.uis-speleo.org/ontology/#karstMorphologyAndMorphogenesis','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.1.1','Epikarst: structure, profiles, morphogenetic mechanisms','1','https://ontology.uis-speleo.org/ontology/#epikarst','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.1.2','Superficial morphogenetic processes and forms','1','https://ontology.uis-speleo.org/ontology/#superficialMorphogeneticProcessesAndForms','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.1.3','Morphometric analysis of karst landforms','1','https://ontology.uis-speleo.org/ontology/#morphometricAnalysisOfKarstLandforms','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.1.4','Typology and classification of karst landforms and landscapes','1','https://ontology.uis-speleo.org/ontology/#typologyAndClassificationOfKarstLandformsAndLandscapes','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.1.5','Karst geomorphological mapping','1','https://ontology.uis-speleo.org/ontology/#karstGeomorphologicalMapping','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.1.6','Karst landscapes evolution, geomorphic history of karst terrains','1','https://ontology.uis-speleo.org/ontology/#karstLandscapesEvolution','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.2','Karst hydrology and hydrogeology','1','https://ontology.uis-speleo.org/ontology/#karstHydrologyAndHydrogeology','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.2.1','Karst hydro(geo)logic systems and aquifers: structure, physical characteristics, flow properties and controls, boundary conditions','1','https://ontology.uis-speleo.org/ontology/#karstHydro-geo-logicSystemsAndAquifers','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.2.2','Superficial karst hydrology','1','https://ontology.uis-speleo.org/ontology/#superficialKarstHydrology','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.2.3','Hydrodynamic zones in karst; karst hydrology in specific zones and settings','1','https://ontology.uis-speleo.org/ontology/#hydrodynamicZonesInKarst','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.2.4','Analysis of karst hydrogeologic systems: general methodology','1','https://ontology.uis-speleo.org/ontology/#analysisOfKarstHydrogeologicSystems','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.2.5','Evolution of karst hydrologic systems, paleohydrogeology','1','https://ontology.uis-speleo.org/ontology/#paleohydrogeology','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.2.6','Regime of karst waters, resourses assessment, monitoring','1','https://ontology.uis-speleo.org/ontology/#regimeOfKarstWaters','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.2.7','Chemistry of karst waters, pollution','1','https://ontology.uis-speleo.org/ontology/#chemistryOfKarstWaters','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.3','Geological conditions and effects of karst','1','https://ontology.uis-speleo.org/ontology/#geologicalConditionsAndEffectsOfKarst','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.3.1','Stratigraphic control','1','https://ontology.uis-speleo.org/ontology/#stratigraphicControl','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.3.2','Lithologic controls, texture and structure of rocks','1','https://ontology.uis-speleo.org/ontology/#lithologicControls','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.3.3','Tectonics','1','https://ontology.uis-speleo.org/ontology/#tectonics','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.3.4','Jointing, fissuring','1','https://ontology.uis-speleo.org/ontology/#jointingFissuring','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.3.5','Paleokarst, epochs and geological effects of karstification, paleogeographic records in karst','1','https://ontology.uis-speleo.org/ontology/#paleokarst','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.3.6','Karst sediments and deposits, deposition in karst environment','1','https://ontology.uis-speleo.org/ontology/#karstSedimentsAndDepositsDepositionInKarstEnvironment','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.4','Geographic conditions and effects of karst','1','https://ontology.uis-speleo.org/ontology/#geographicConditionsAndEffectsOfKarst','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.4.1','Climatic perceipt in karst geomorphology, climatic types of karst','1','https://ontology.uis-speleo.org/ontology/#climaticPerceiptInKarstGeomorphology','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.4.2','Microclimate of karst landforms','1','https://ontology.uis-speleo.org/ontology/#microclimateOfKarstLandforms','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.4.3','Soil formation, types and processes; CO₂ generation','1','https://ontology.uis-speleo.org/ontology/#soilFormation','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.4.4','Vegetation in karst landscapes','1','https://ontology.uis-speleo.org/ontology/#vegetationInKarstLandscapes','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.5','Geophisics of karst terrains','1','https://ontology.uis-speleo.org/ontology/#geophisicsOfKarstTerrains','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.5.1','Geothermic fields in karst areas','1','https://ontology.uis-speleo.org/ontology/#geothermicFieldsInKarstAreas','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.5.2','Heat exchange in karst massifs','1','https://ontology.uis-speleo.org/ontology/#heatExchangeInKarstMassifs','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.5.3','Natural radioactivity on karst terrains','1','https://ontology.uis-speleo.org/ontology/#naturalRadioactivityOnKarstTerrains','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.5.4','Geophisical methods of investigation of karst','1','https://ontology.uis-speleo.org/ontology/#geophisicalMethodsOfInvestigationOfKarst','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.6','Specific settings of karst development','1','https://ontology.uis-speleo.org/ontology/#specificSettingsOfKarstDevelopment','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.6.1','Hydrothermal karst','1','https://ontology.uis-speleo.org/ontology/#hydrothermalKarst','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.6.2','Deep karst, endokarst','1','https://ontology.uis-speleo.org/ontology/#deepKarstEndokarst','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.6.3','Artesian karst','1','https://ontology.uis-speleo.org/ontology/#artesianKarst','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.6.4','Coastal karst, karst of atolls and reefs','1','https://ontology.uis-speleo.org/ontology/#coastalKarst','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.7','Pseudokarst and hypokarst','1','https://ontology.uis-speleo.org/ontology/#pseudokarstAndHypokarst','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.7.1','Pseudokarst in volcanic rocks','1','https://ontology.uis-speleo.org/ontology/#pseudokarstInVolcanicRocks','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.7.2','Hypokarst in ice (cryokarst)','1','https://ontology.uis-speleo.org/ontology/#hypokarstInIce','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.7.3','Piping processes and phenomena (in any lithologies)','1','https://ontology.uis-speleo.org/ontology/#pipingProcessesAndPhenomena','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.1.7.4','Karst-like features in other lithologies','1','https://ontology.uis-speleo.org/ontology/#karst-likeFeaturesInOtherLithologies','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2','GEOSPELEOLOGY','1','https://ontology.uis-speleo.org/ontology/#geospeleology','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.0.1','Speleology: subject, definitions, structure etc.','1','https://ontology.uis-speleo.org/ontology/#speleologySubjectDefinitionsStructure','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.0.2','Speleogenetic processes, genetic types of caves (various)','1','https://ontology.uis-speleo.org/ontology/#speleogeneticProcesses','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.1','Morphology of caves and speleogenesis','1','https://ontology.uis-speleo.org/ontology/#morphologyOfCavesAndSpeleogenesis','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.1.1','General theories of the cave origin and development, speleogenetic settings, genetic classifications','1','https://ontology.uis-speleo.org/ontology/#generalTheoriesOfTheCaveOriginAndDevelopment','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.1.2','Physical chemistry of speleogenetic processes','1','https://ontology.uis-speleo.org/ontology/#physicalChemistryOfSpeleogeneticProcesses','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.1.3','Early development of caves; conceptual models, hardware and humerical modelling','1','https://ontology.uis-speleo.org/ontology/#earlyDevelopmentOfCaves','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.1.4','Macro-morphology, cave pattern development in specific zones and settings','1','https://ontology.uis-speleo.org/ontology/#macro-morphology','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.1.5','Meso-morphology:solution sculpturing forms and mechanisms','1','https://ontology.uis-speleo.org/ontology/#meso-morphologysolutionSculpturingFormsAndMechanisms','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.1.6','Breakdown morphology and mechanisms','1','https://ontology.uis-speleo.org/ontology/#breakdownMorphologyAndMechanisms','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.1.7','Depositional morphology','1','https://ontology.uis-speleo.org/ontology/#depositionalMorphology','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.2','Hydrology and hydrochemistry of caves','1','https://ontology.uis-speleo.org/ontology/#hydrologyAndHydrochemistryOfCaves','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.2.1','Hydraulic and hydrologic factors in cave development','1','https://ontology.uis-speleo.org/ontology/#hydraulicAndHydrologicFactorsInCaveDevelopment','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.2.2','Hydrologic and hydrochemical regime of caves','1','https://ontology.uis-speleo.org/ontology/#hydrologicAndHydrochemicalRegimeOfCaves','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.3','Geologic controls of cave development','1','https://ontology.uis-speleo.org/ontology/#geologicControlsOfCaveDevelopment','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.3.1','Stratigraphy','1','https://ontology.uis-speleo.org/ontology/#stratigraphy','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.3.2','Lithology, texture and structure of rocks','1','https://ontology.uis-speleo.org/ontology/#lithology','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.3.3','Tectonics: general settings, block & faults','1','https://ontology.uis-speleo.org/ontology/#tectonics','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.3.4','Jointing, fissuring','1','https://ontology.uis-speleo.org/ontology/#jointingFissuring','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.3.5','Influence of paleokarst features','1','https://ontology.uis-speleo.org/ontology/#influenceOfPaleokarstFeatures','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.4','Cave climatology, physics of cave environment','1','https://ontology.uis-speleo.org/ontology/#caveClimatology','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.4.1','Climatic classifications of caves','1','https://ontology.uis-speleo.org/ontology/#climaticClassificationsOfCaves','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.4.2','Air circulation and exchange, termo- and baro-conditions and regime','1','https://ontology.uis-speleo.org/ontology/#airCirculationAndExchange','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.4.3','Humidity of cave air, condensation processes','1','https://ontology.uis-speleo.org/ontology/#humidityOfCaveAir','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.4.4','Gas composition of cave air','1','https://ontology.uis-speleo.org/ontology/#gasCompositionOfCaveAir','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.5','Cave deposits','1','https://ontology.uis-speleo.org/ontology/#caveDeposits','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.5.0','Classifications of cave deposits, depositional environments, cave facies, stratigraphy','1','https://ontology.uis-speleo.org/ontology/#classificationsOfCaveDeposits','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.5.1','Subaqueous chemical deposits','1','https://ontology.uis-speleo.org/ontology/#subaqueousChemicalDeposits','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.5.2','Subaeral chemical deposits','1','https://ontology.uis-speleo.org/ontology/#subaeralChemicalDeposits','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.5.3','Collapse deposits','1','https://ontology.uis-speleo.org/ontology/#collapseDeposits','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.5.4','Ice in cave','1','https://ontology.uis-speleo.org/ontology/#iceInCave','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.5.5','Biogenetic deposits','1','https://ontology.uis-speleo.org/ontology/#biogeneticDeposits','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.5.6','Chronology of cave deposits, paleoreconstructions (radiocarbon dating, thermoluminescence, palynology, paleontology)','1','https://ontology.uis-speleo.org/ontology/#chronologyOfCaveDeposits','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.6','Cave geochemistry','1','https://ontology.uis-speleo.org/ontology/#caveGeochemistry','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.7','Caves in special lithologies, special cave-forming processes','1','https://ontology.uis-speleo.org/ontology/#cavesInSpecialLithologies','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.7.1','Caves in volcanic rocks, volcanospeleology','1','https://ontology.uis-speleo.org/ontology/#cavesInVolcanicRocks','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.7.2','Cave ice','1','https://ontology.uis-speleo.org/ontology/#caveIce','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.7.3','Piping (suffosion) caves','1','https://ontology.uis-speleo.org/ontology/#piping-suffosion-Caves','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.7.4','Tectonic caves','1','https://ontology.uis-speleo.org/ontology/#tectonicCaves','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.7.5','Caves in the evaporites','1','https://ontology.uis-speleo.org/ontology/#cavesInTheEvaporites','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('1.2.7.6','Other types of caves: conglomerates, magnesite, travertines, calcarenites','1','https://ontology.uis-speleo.org/ontology/#otherTypesOfCaves','551','General geology, geodynamics, geomorphology, climatology, stratigraphy'),
('2','REGIONAL SPELEOLOGY AND KARSTOLOGY','2','https://ontology.uis-speleo.org/ontology/#regionalSpeleologyAndKarstology','796,525','Caving and spelunking'),
('3','BIOSPELEOLOGY','3','https://ontology.uis-speleo.org/ontology/#biospeleology','578,77','Subterranean biology'),
('3.1','SYSTEMATIC BIOSPELEOLOGY','3','https://ontology.uis-speleo.org/ontology/#systematicBiospeleology','578,77','Subterranean biology'),
('3.1.1','Crustacea: ostracoda, copepoda, malacostraci (bathynellacea, mysidacea, isopoda, amphipoda), mystacocardia','3','https://ontology.uis-speleo.org/ontology/#crustacea','578,77','Subterranean biology'),
('3.1.2','Hexapoda: collembola, protura, diplura, thysanura, orthoptera, hemiptera, coleoptera, lepidoptera, diptera, amphaniptera','3','https://ontology.uis-speleo.org/ontology/#hexapoda','578,77','Subterranean biology'),
('3.1.3','Aracnidae: scorpiones, pseudoscorpiones, opiliones, araneae, acari','3','https://ontology.uis-speleo.org/ontology/#aracnidae','578,77','Subterranean biology'),
('3.1.4','Myriapoda: symphila, pauropoda, diplopoda','3','https://ontology.uis-speleo.org/ontology/#myriapoda','578,77','Subterranean biology'),
('3.1.5','Mollusca: gastropoda, bivalvia','3','https://ontology.uis-speleo.org/ontology/#mollusca','578,77','Subterranean biology'),
('3.1.6','Vertebrata','3','https://ontology.uis-speleo.org/ontology/#vertebrata','578,77','Subterranean biology'),
('3.1.7','Hupygean flora, fungi, algae','3','https://ontology.uis-speleo.org/ontology/#hupygeanFloraFungiAlgae','578,77','Subterranean biology'),
('4','ANTHROPOSPELEOLOGY AND PALAEONTHOSPELEOLOGY','4','https://ontology.uis-speleo.org/ontology/#anthropospeleologyAndPalaeonthospeleology','569,9','Fossil hominids'),
('4.1','ARCHAEOLOGY, PREHISTORICAL AND HISTORICAL CULTURES','4','https://ontology.uis-speleo.org/ontology/#archaeologyPrehistoricalAndHistoricalCultures','569,9','Fossil hominids'),
('4.1.1','General information, investigation methods (speleoarchaeology)','4','https://ontology.uis-speleo.org/ontology/#speleoarchaeology','569,9','Fossil hominids'),
('4.1.2','Prehistoric man','4','https://ontology.uis-speleo.org/ontology/#prehistoricMan','569,9','Fossil hominids'),
('4.1.3','Use of caves, underground cities','4','https://ontology.uis-speleo.org/ontology/#useOfCavesUndergroundCities','569,9','Fossil hominids'),
('4.1.4','Rock art','4','https://ontology.uis-speleo.org/ontology/#rockArt','700','Arts'),
('4.2','Archaeozoology, paleontology','4','https://ontology.uis-speleo.org/ontology/#archaeozoologyPaleontology','560','Fossils and prehistoric life'),
('4.2.1','General information, methods of investigation (paleontology)','4','https://ontology.uis-speleo.org/ontology/#generalInformationMethodsOfInvestigation-paleontology-','560','Fossils and prehistoric life'),
('4.2.1.1','Paleofaunes, paleoclimates, paleovegetations','4','https://ontology.uis-speleo.org/ontology/#paleofaunesPaleoclimatesPaleovegetations','560,45','Paleoecology'),
('4.3','SPELEOLOGY IN ANTHROPIC CAVE','4','https://ontology.uis-speleo.org/ontology/#speleologyInAnthropicCave','796,525','Caving or Speleology'),
('5','SPELEOLOGICAL AND KARSTOLOGICAL ACTIVITIES','5','https://ontology.uis-speleo.org/ontology/#speleologicalAndKarstologicalActivities','796,525','Caving or Speleology'),
('5.1.1','History of speleology and karstology','5','https://ontology.uis-speleo.org/ontology/#historyOfSpeleologyAndKarstology','551,4409','History of Speleology'),
('5.1.2','Personalias','5','https://ontology.uis-speleo.org/ontology/#personalias','551,44092','Biographies of speleologists'),
('5.2','SPELEOLOGIC AND KARST ORGANIZATIONS','5','https://ontology.uis-speleo.org/ontology/#speleologicAndKarstOrganizations','60','General organizations & museum science'),
('5.2.1','International speleological union','5','https://ontology.uis-speleo.org/ontology/#internationalSpeleologicalUnion','60','General organizations & museum science'),
('5.2.2','Other international organizations','5','https://ontology.uis-speleo.org/ontology/#otherInternationalOrganizations','60','General organizations & museum science'),
('5.2.3','National and regional organizations','5','https://ontology.uis-speleo.org/ontology/#nationalAndRegionalOrganizations','60','General organizations & museum science'),
('5.2.4','International conferences and symposia','5','https://ontology.uis-speleo.org/ontology/#internationalConferencesAndSymposia','60','General organizations & museum science'),
('5.2.5','National conferences and symposia','5','https://ontology.uis-speleo.org/ontology/#nationalConferencesAndSymposia','60','General organizations & museum science'),
('5.2.6','Regional conferences and symposia','5','https://ontology.uis-speleo.org/ontology/#regionalConferencesAndSymposia','60','General organizations & museum science'),
('5.3','RESEARCH MANAGEMENT','5','https://ontology.uis-speleo.org/ontology/#researchManagement','60','General organizations & museum science'),
('5.3.1','Research centers','5','https://ontology.uis-speleo.org/ontology/#researchCenters','60','General organizations & museum science'),
('5.3.2','Underground laboratories','5','https://ontology.uis-speleo.org/ontology/#undergroundLaboratories','60','General organizations & museum science'),
('5.4','MUSEUMS, COLLECTIONS, AND ART','5','https://ontology.uis-speleo.org/ontology/#museumsCollectionsAndArt','60','General organizations & museum science'),
('5.4.1','Speleologic museums','5','https://ontology.uis-speleo.org/ontology/#speleologicMuseums','60','General organizations & museum science'),
('5.4.2','Collections: stamps, postcards, photo albums, posters','5','https://ontology.uis-speleo.org/ontology/#collections','790,132','Collecting as a hobby'),
('5.4.3','Exhibitions','5','https://ontology.uis-speleo.org/ontology/#exhibitions','',''),
('5.5','FICTIONS','5','https://ontology.uis-speleo.org/ontology/#fictions','',''),
('5.5.1','Literary, essays, poetry','5','https://ontology.uis-speleo.org/ontology/#literaryEssaysPoetry','',''),
('5.5.2','Art and painting, comics','5','https://ontology.uis-speleo.org/ontology/#artAndPaintingComics','',''),
('5.5.3','Folklore, traditions, legends','5','https://ontology.uis-speleo.org/ontology/#folkloreTraditionsLegends','',''),
('6','SPELEOLOGY AND APPLIED KARST SCIENCE','6','https://ontology.uis-speleo.org/ontology/#speleologyAndAppliedKarstScience','796,525','Caving or Speleology'),
('6.1','USE OF KARST','6','https://ontology.uis-speleo.org/ontology/#useOfKarst','796,525','Caving or Speleology'),
('6.1.1','Environment: impact and vulnerability','6','https://ontology.uis-speleo.org/ontology/#environmentImpactAndVulnerability','796,525','Caving or Speleology'),
('6.1.2','Drinking water','6','https://ontology.uis-speleo.org/ontology/#drinkingWater','796,525','Caving or Speleology'),
('6.1.3','Other resources: artificial lakes, dams, hydrothermal plants','6','https://ontology.uis-speleo.org/ontology/#otherResources','796,525','Caving or Speleology'),
('6.2','USE OF CAVES','6','https://ontology.uis-speleo.org/ontology/#useOfCaves','796,525','Caving or Speleology'),
('6.2.1','Concepts and assessments','6','https://ontology.uis-speleo.org/ontology/#conceptsAndAssessments','796,525','Caving or Speleology'),
('6.2.2','Technical aspects, management, practice','6','https://ontology.uis-speleo.org/ontology/#technicalAspectsManagementPractice','796,525','Caving or Speleology'),
('6.2.3','Tourist caves','6','https://ontology.uis-speleo.org/ontology/#touristCaves','796,525','Caving or Speleology'),
('6.2.4','Sports, speleology, adventure, recreation','6','https://ontology.uis-speleo.org/ontology/#sportsSpeleologyAdventureRecreation','796,525','Caving or Speleology'),
('6.2.5','Speleotherapy','6','https://ontology.uis-speleo.org/ontology/#speleotherapy','796,525','Caving or Speleology'),
('6.2.6','Exploitation of resources (mines, guano, saltpeter, salt, etc.)','6','https://ontology.uis-speleo.org/ontology/#exploitationOfResources','796,525','Caving or Speleology'),
('6.3','PROTECTION OF CAVES AND KARST LANDS','6','https://ontology.uis-speleo.org/ontology/#protectionOfCavesAndKarstLands','551,4479','Environmental Protection of Karst and Cave Systems'),
('6.3.1','Legal aspects, regulations, guidelines, codes','6','https://ontology.uis-speleo.org/ontology/#legalAspectsRegulationsGuidelinesCodes','551,4479','Environmental Protection of Karst and Cave Systems'),
('6.3.2','Water resource protection','6','https://ontology.uis-speleo.org/ontology/#waterResourceProtection','551,4479','Environmental Protection of Karst and Cave Systems'),
('6.3.3','Landscape protection, parks and reserves','6','https://ontology.uis-speleo.org/ontology/#landscapeProtectionParksAndReserves','551,4479','Environmental Protection of Karst and Cave Systems'),
('6.3.4','Cave protection, regulated access, closed caves','6','https://ontology.uis-speleo.org/ontology/#caveProtection','551,4479','Environmental Protection of Karst and Cave Systems'),
('7','TECHNICAL SPELEOLOGY','7','https://ontology.uis-speleo.org/ontology/#technicalSpeleology','796,525','Caving or Speleology'),
('7.1','MATERIALS AND EXPLORATION TECHNIQUES','7','https://ontology.uis-speleo.org/ontology/#materialsAndExplorationTechniques','796,525','Caving or Speleology'),
('7.1.1','Progression and materials: ropes and tools','7','https://ontology.uis-speleo.org/ontology/#progressionAndMaterialsRopesAndTools','796,525','Caving or Speleology'),
('7.1.2','Progression and materials: electrical and unblocking materials','7','https://ontology.uis-speleo.org/ontology/#progressionAndMaterialsElectricalAndUnblockingMaterials','796,525','Caving or Speleology'),
('7.1.3','Lighting systems','7','https://ontology.uis-speleo.org/ontology/#lightingSystems','796,525','Caving or Speleology'),
('7.1.4','Personal equipment','7','https://ontology.uis-speleo.org/ontology/#personalEquipment','796,525','Caving or Speleology'),
('7.1.5','Collective equipment and camp logistics','7','https://ontology.uis-speleo.org/ontology/#collectiveEquipmentAndCampLogistics','796,525','Caving or Speleology'),
('7.2','SPELEO-DIVING ACTIVITIES AND MATERIALS','7','https://ontology.uis-speleo.org/ontology/#speleo-divingActivitiesAndMaterials','797,23','Diving'),
('7.3','PROSPECTION','7','https://ontology.uis-speleo.org/ontology/#prospection','551,44072','Cave Prospecting'),
('7.4','ACCIDENTS AND RESCUE','7','https://ontology.uis-speleo.org/ontology/#accidentsAndRescue','363,124','Cave Accidents and Rescue Operations'),
('7.5','MEDICINE: PHYSIOLOGY, PSYCHOLOGY, SOCIOLOGY, NUTRITION','7','https://ontology.uis-speleo.org/ontology/#medicinePhysiologyPsychologySociologyNutrition','616,98','Medical Aspects of Caving'),
('7.6','EDUCATION: COURSES, OUTREACH, ETHICS','7','https://ontology.uis-speleo.org/ontology/#educationCoursesOutreachEthics','371','Schools & their activities; special education'),
('7.6.1','Speleology courses','7','https://ontology.uis-speleo.org/ontology/#speleologyCourses','371','Schools & their activities; special education'),
('7.6.2','Teaching, compulsory schools, minors','7','https://ontology.uis-speleo.org/ontology/#teachingCompulsorySchoolsMinors','371','Schools & their activities; special education'),
('8','DOCUMENTATION OF KARST AND CAVES','8','https://ontology.uis-speleo.org/ontology/#documentationOfKarstAndCaves','551,4407','Karst terrains — Methods, equipment, documentation'),
('8.1','TOPOGRAPHY AND CARTOGRAPHY','8','https://ontology.uis-speleo.org/ontology/#topographyAndCartography','551,4407','Karst terrains — Methods, equipment, documentation'),
('8.1.1','Surveying techniques and tools','8','https://ontology.uis-speleo.org/ontology/#surveyingTechniquesAndTools','551,4407','Karst terrains — Methods, equipment, documentation'),
('8.1.2','Cartography: surveying techniques and tools, GPS','8','https://ontology.uis-speleo.org/ontology/#cartography','551,4407','Karst terrains — Methods, equipment, documentation'),
('8.1.3','Computers: programs and computerized representations of caves','8','https://ontology.uis-speleo.org/ontology/#computers','551,4407','Karst terrains — Methods, equipment, documentation'),
('8.2','TERMINOLOGY AND TOPONYMY','8','https://ontology.uis-speleo.org/ontology/#terminologyAndToponymy','401,4','Linguistics – Terminology'),
('8.2.1','Speleological terminology, glossaries, lexicon','8','https://ontology.uis-speleo.org/ontology/#speleologicalTerminology','401,4','Linguistics – Terminology'),
('8.2.2','Toponyms of karst areas','8','https://ontology.uis-speleo.org/ontology/#toponymsOfKarstAreas','401,4','Linguistics – Terminology'),
('8.2.3','Cave naming methods','8','https://ontology.uis-speleo.org/ontology/#caveNamingMethods','401,4','Linguistics – Terminology'),
('8.3','BIBLIOGRAPHY','8','https://ontology.uis-speleo.org/ontology/#bibliography','16','Bibliographies and catalogs'),
('8.3.1','General bibliography, regional and thematic lists','8','https://ontology.uis-speleo.org/ontology/#generalBibliography','17','Bibliographies and catalogs'),
('8.3.2','Libraries','8','https://ontology.uis-speleo.org/ontology/#libraries','18','Bibliographies and catalogs'),
('8.3.3','Speleological and karst periodicals, indexes','8','https://ontology.uis-speleo.org/ontology/#speleologicalAndKarstPeriodicalsIndexes','19','Bibliographies and catalogs'),
('8.3.3.1','Other periodicals','8','https://ontology.uis-speleo.org/ontology/#otherPeriodicals','20','Bibliographies and catalogs'),
('8.3.4','Books on speleology, karstology, geology, hydrogeology, biospeleology, Archaeology','8','https://ontology.uis-speleo.org/ontology/#booksOnSpeleologyKarstologyGeologyHydrogeologyBiospeleologyArchaeology','21','Bibliographies and catalogs'),
('8.3.5','Reviews of periodicals, monographs, articles','8','https://ontology.uis-speleo.org/ontology/#reviewsOfPeriodicalsMonographsArticles','22','Bibliographies and catalogs'),
('8.4','PHOTOGRAPHY AND AUDIOVIDEO','8','https://ontology.uis-speleo.org/ontology/#photographyAndAudiovideo','770','Photography, computer art, cinematography, videography'),
('8.4.1','General information (photography and audiovideo)','8','https://ontology.uis-speleo.org/ontology/#generalInformation-photographyAndAudiovideo','770','Photography, computer art, cinematography, videography'),
('8.4.2','Photography','8','https://ontology.uis-speleo.org/ontology/#photography','770','Photography, computer art, cinematography, videography'),
('8.4.3','Films and audiovideo media, techniques and materials','8','https://ontology.uis-speleo.org/ontology/#filmsAndAudiovideoMediaTechniquesAndMaterials','791,43','Motion pictures'),
('8.5','DATABASES AND ARCHIVES','8','https://ontology.uis-speleo.org/ontology/#databasesAndArchives','5,74','Data files and databases'),
('8.5.2','Systematic identification systems for karst and caves, cadastral lists, maps, inventories','8','https://ontology.uis-speleo.org/ontology/#systematicIdentificationSystemsForKarstAndCaves','5,75','Data files and databases'),
('8.5.3','Database registration, data transfer, data security','8','https://ontology.uis-speleo.org/ontology/#databaseRegistrationDataTransferDataSecurity','5,76','Data files and databases'),
('8.6','INTERNET AND WEBSITES','8','https://ontology.uis-speleo.org/ontology/#internetAndWebsites','25,04','Information storage and retrieval systems – Online information systems'),
('9','OTHER TOPICS','9','https://ontology.uis-speleo.org/ontology/#otherTopics','1,9','Controversial knowledge'),
('9.1','CANYONING','9','https://ontology.uis-speleo.org/ontology/#canyoning','796,5','Canyonning');
