\c grottoce;
INSERT INTO public.t_history (
		id,
		id_author,
		id_reviewer,
		date_inscription,
		date_reviewed,
		relevance,
		body,
		id_cave,
		id_entrance,
		id_point,
		id_language,
		is_deleted
	)
VALUES (
		5555,
		1,
		NULL,
		'2021-04-03 21:01:40.000',
		NULL,
		1,
		'Découverte initialement par Jean-Dupond en 1973',
		5,
		NULL,
		NULL,
		'fra',
		false
	),(
		6666,
		2,
		NULL,
		'2021-04-03 21:01:40.000',
		NULL,
		1,
		'Le passage situé à l''est a été découvert en 1998 par Marc Luc',
		6,
		NULL,
		NULL,
		'fra',
		false
	),(
		81,
		6,
		NULL,
		'2009-04-03 21:01:40.000',
		NULL,
		4,
		'L''entrée originelle de la Leicasse a été découverte le 2 janvier 1983, par Gilles BARRAU (GERSAM) lors d''une séance de prospection avec deux collègues.\n\nLe trou souffleur initial gros comme le poing et le méandre qui suivait ont nécessité 6 séances de désobstruction percutante.\nLe 6 février 1983 le puits du Robot (P109, fractionné en trois parties est descendu en première par Gilles BARRAU, Jean CHERY puis Guilhem MAISTRE) est atteint et la galerie des Meulières est explorée.\n\nS''ensuivent  trois séances de désobstruction vers -160.\n\nDans la nuit du 12 au 13 mars 1983 les spéléos du GERSAM explorent les galeries de la Nuit Blanche jusqu''à la salle Edmond Milhau.\nCourant 1983 et 1984 l''essentiel du réseau est exploré.\nEn septembre 1984 le GERSAM explore le réseau du Grand Fond\nPar la suite les explos se sont poursuivies plus ou moins régulièrement jusque dans les années 90.\n\nHistorique complet disponible dans la monographie du réseau.',
		NULL,
		17,
		NULL,
		'fra',
		false
	),
	(
		101,
		3,
		NULL,
		'2009-08-16 12:08:27.000',
		NULL,
		1,
		'La topographie initiale est relevée par le GSBM en 1986. \nEn 2002, une autre équipe, du GSBM et quelques amis spéléos, découvrent une suite du gouffre et atteignent la profondeur de 750 mètres.\nEn janvier 2005 Frédéric Poggia, aidé d''une multitude de sherpas, plonge le siphon aval et atteint la profondeur de 795 mètres[ref]Spéléo N° 52[/ref].\n\nA partir de 1995, l''exploration de l''amont du méandre de l''Ankou est entreprise. Elle aboutit en 2013 par le percement de la seconde entrée, nommée aven Aubert en l''hommage du généreux propriétaire du terrain, disparu prématurément. Prolongé ainsi par le haut, le réseau atteint ainsi en 2013 une profondeur de 843 mètres et un développement de 5152 mètres[ref]SAUSSE Olivier, "Ouverture de l’aven Aubert : nouvelle entrée du trou Souffleur (Saint-Christol-d’Albion, Vaucluse)", Spelunca n°130, pages 19 à 30 : http://www.gsbm.fr/publications/france/2013_Spelunca_130_Sausse.pdf[/ref].\n\nLe 21 décembre 2014, la jonction avec l''aven des Neiges porte la profondeur à 921 mètres et le développement à plus de 10 kilomètres[ref]Spéléo Magazine n°89, mars 2015[/ref] [ref]CATON Pascal, "Découverte de l’aven des Neiges: nouvelle entrée du trou Souffleur (Saint-Christol-d’Albion, Vaucluse)", Spelunca n°137, 2015, pages 13 à 15 : http://www.gsbm.fr/publications/france/2015_Spelunca_137_Caton.pdf[/ref].',
		NULL,
		12,
		NULL,
		'fra',
		false
	),
	(
		327,
		2,
		NULL,
		'2013-08-19 21:23:49.000',
		NULL,
		2,
		'En 1973, après plusieurs plongées de reconnaissance, les plongeurs du CLPA  (Daniel Bosc, Jean-louis et Yves Gilles, Pascal Parot) organisent un camp post-siphon (08-16/09/73) dans l''amont, augmentant la connaissance de la cavité de 300m et levant une topographie précise. Une incursion dans l''aval l''année suivante (07/10/1974) permet à la même équipe de parcourir 500m de rivière supplémentaires.\nLe 25/11/1978, Patrick PENEZ et Fred VERGIER poursuivent l''exploration du réseau aval en franchissant le rapide qui avait arrêté leurs prédécesseurs : 350m de première, arrêt sur diaclase impénétrable dans la rivière.',
		NULL,
		18,
		NULL,
		'fra',
		false
	),
	(
		325,
		1,
		NULL,
		'2013-07-20 19:38:46.000',
		NULL,
		4,
		'Cavité découverte en 1975 et non en 1957',
		NULL,
		11,
		NULL,
		'fra',
		false
	),
	(
		326,
		2,
		NULL,
		'2013-08-19 21:22:35.000',
		NULL,
		0,
		'Tiré du site "http://www.plongeesout.com/"\n\nAprès une visite de reconnaissance (13/09/1885), L.ARMAND, E.FOULQUIER, G.GAUPILLAT et E.A.MARTEL atteignent la rivière le 07/07/1889 à la suite d''une descente mouvementée ponctuée de chutes de pierres.\nEn 1923, M.CREMIEU franchit une voûte basse et progresse jusqu''au siphon aval. Il faudra attendre 1933 pour que des spéléologues découvrent du "neuf" avec l''exploration d''une salle en amont (L.BALSAN), puis 1934 pour la première descente par les "puits parallèles".\nLes premières plongées remontent au 21-22/03/1970 où le GEPS, mené par Jean-Louis VERNETTE, et le SCM avec l''assistance du SCBAM franchit les siphons amont et aval, découvrant au total plus de 1000m de galeries vierges avec les conduits et salles post-siphon.',
		NULL,
		18,
		NULL,
		'fra',
		false
	),
	(
		2651,
		5,
		NULL,
		'2016-11-17 19:39:39.000',
		NULL,
		-5,
		'Le gouffre a été ainsi baptisé par les spéléos du club Vulcain en souvenirs des spéléos Jean Dupont et Bernard Raffy, disparus pendant une exploration de la goule de Foussoubie en 1963.\nLe gouffre Jean-Bernard fut pendant quelque temps la cavité la plus profonde connue du monde au passage à la cote -1 455 m en 1981, avant d''être dépassé par le gouffre Mirolda. \nEn 2010 il reste le deuxième gouffre le plus profond de France, et le sixième mondial[ref]Article de l''encyclopédie collaborative Wikipédia, en français "Gouffre Jean-Bernard" : https://fr.wikipedia.org/wiki/Gouffre_Jean-Bernard[/ref].\n\nCoupe en 1991 : http://www.groupe-speleo-vulcain.com/wp-content/uploads/2011/03/JB-Coupe1991.pdf\n\nPlan en 2011 : http://www.groupe-speleo-vulcain.com/wp-content/uploads/2011/03/JB-plan2010-2.pdf\nAtlas en 2011: http://www.groupe-speleo-vulcain.com/wp-content/uploads/2011/03/Atlas-JB-Binded1000.pdf',
		NULL,
		1,
		NULL,
		'fra',
		false
	),
	(
		6423,
		5,
		NULL,
		'2019-02-14 13:36:30.000',
		NULL,
		0,
		'En 1951 et 1952, le SCM entreprend le déblaiement du trop-plein de la source de Saint-Jean alias source des Sicards (cf. présente fiche GC n°9) ; mais le SCM est arrêté par l''interdiction du propriétaire. \n\nCette désobstruction est reprise en 1969 par le CLPA à la suite de la coloration de la grotte de l''Ours et de la recherche du vrai propriétaire de la source. Le propriétaire présumé n''étant pas celui interdisant l''accès des lieux. Coloration dont le temps de réapparition rapide (10m /h) plaidait en faveur d''un réseau important exondé.\nUn siphon, plongé par les frères Gilles, P. Parrot, D. Bosc de 1971 à 1973, donne accès à un réseau important. \n\nPour éviter toute polémique au sujet de la source et de sa fréquentation et explorer la galerie qui fait suite a la salle du 8 juin découverte par les plongeurs du club l''ouverture d''une entrée artificielle est effectuée avec l''accord du propriétaire de la parcelle concernée.La première salle est repérée en surface (expérience électromagnétique), et le 8 juin 1974, après bien des efforts de désobstruction, cette entrée artificielle est ouverte (702,89-171,28-193m). \nElle est située à 15 mètres au nord de la route, 30 mètres après la maison isolée jouxtant un ancien virage corrigé. Cette entrée est condamnée et ne doit pas être utilisée. Une nouvelle entrée artificielle a été réalisée : L''entrée des "Feuilles Mortes".\n\nOn trouvera dans Caumont (1979) une première approche de l''étude de la cavité et l''historique détaillé de l''exploration du Garrel jusqu''à 1979. \n\nEn 1982, escalade sur 150 mètres d''une cheminée de 15x15 (Cheminée du Phallus). \nNouveaux travaux de topographie du CLPA à partir de 1984. \n\nEn 1990 une nouvelle entrée dite des Feuilles Mortes (702,76-171,31 - 235 m) est ouverte après report de topographie en surface et repérage aux fumigènes (cf. fiche GC n°24784 : https://www.grottocenter.org/html/file_Fr.php?type=change&category=entry&id=24784#)[ref]Groupe d''Etudes et de Recherches Spéléologiques et Archéologiques de Montpellier (GERSAM), "L''inventaire du Larzac et de la Séranne", chapitre "53 - Commune de Saint-Jean-de-Buèges" : http://jfbrun.eu/gersam/stjeanbu.htm[/ref].',
		NULL,
		9,
		NULL,
		'fra',
		false
	);
