\c grottoce;
INSERT INTO public.t_comment (
    id,
    id_author,
    id_reviewer,
    date_inscription,
    date_reviewed,
    relevance,
    e_t_underground,
    e_t_trail,
    aestheticism,
    caving,
    approach,
    title,
    body,
    alert,
    id_cave,
    id_entrance,
    id_exit,
    id_language,
    is_deleted
)
VALUES (
        5555,
        1,
        2,
        '2020-09-07 17:42:51.000',
        '2020-09-08 17:42:51.000',
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Bilan du 15/06/2020',
        'C''était pas terrible.',
        false,
        5,
        NULL,
        NULL,
        'fra',
        false
	),
    (
        5556,
        2,
        1,
        '2020-09-07 17:42:51.000',
        '2020-09-08 17:42:51.000',
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Amazing!',
        'What an amazing cave, fabulous!',
        false,
        5,
        NULL,
        NULL,
        'eng',
        false
	),
    (
        6666,
        2,
        1,
        '2020-09-07 17:42:51.000',
        '2020-09-08 17:42:51.000',
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Exploration du 23/06/2020',
        'C''était chouette, merveilleuse cavité !',
        false,
        6,
        NULL,
        NULL,
        'fra',
        false
	),
    (
		1,
		6,
		NULL,
		'2008-07-29 14:07:09.000',
		NULL,
		2,
		'06:00:00'::interval,
		'00:20:00'::interval,
		5.0,
		5.0,
		4.0,
		'Sortie du dimanche 20 janvier 2008',
		'Une chouette sortie à la journée pour se perfectionner à l''équipement ou travailler sa progression sur corde (on ne la quitte jamais). Le plus difficile étant de ne pas se perdre dans les bois et le passage de la lucarne. \n',
		false,
		NULL,
		7,
		NULL,
		'fra',
		false
	),
	(
		2,
		6,
		NULL,
		'2008-07-29 18:27:00.000',
		NULL,
		2,
		'05:00:00'::interval,
		'01:30:00'::interval,
		7.0,
		7.0,
		3.0,
		'Sortie du samedi 12 juillet 2008 - cascade Jean Dupont',
		'Une très jolie sortie, techniquement facile avec des puits plein de volume (puits des Savoyard et puits Alain).\nMalheureusement, nous n''avons pu aller jusqu''à la cascade Jean Dupont en raison du trop grand volume d''eau.\nTemps d''approche 1h30 en été à partir du refuge du Folly.',
		false,
		NULL,
		1,
		NULL,
		'fra',
		false
	),
	(
		6,
		4,
		NULL,
		'2008-08-04 17:07:26.000',
		NULL,
		2,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		'Possibilité de traversée depuis 2006',
		'En 2006, une nouvelle entrée "Rochotte" a été découverte. \nDescendre la route sur env. 500m puis prendre à gauche un chemin forestier qu''il faut remonter sur env. 300m. \nL''entrée, entourée d''un grillage, s''ouvre sur la droite. Possibilité de faire une traversée avec 2 équipes.\nEnchaînement de deux puits (chatière entre les 2), le second arrivant un peu avant la cascade.',
		false,
		NULL,
		3,
		NULL,
		'fra',
		false
	),
	(
		28,
		1,
		NULL,
		'2008-08-18 10:43:34.000',
		NULL,
		4,
		'16:30:00'::interval,
		'00:15:00'::interval,
		10.0,
		4.0,
		8.0,
		'Restriction saisonnière d''accès',
		'Accès interdit en période de chasse.',
		false,
		NULL,
		17,
		NULL,
		'fra',
		false
	),
	(
		50,
		6,
		NULL,
		'2008-09-19 19:06:29.000',
		NULL,
		2,
		'09:00:00'::interval,
		NULL,
		NULL,
		NULL,
		NULL,
		'CR Saint de Glace, Méaudre (38) du 07/09/2008',
		'Participants : Estelle Forbach, Frédéric Delègue, avec pour initiés : Alexandra, Renaud, Sonia, Anouk, Loïc, Cédric.\n\nVoici un petit groupe d''invétérés,\nPartant sous un beau temps presque avéré,\nA l''assaut des abîmes du Vercors,\nPour aller y faire quelques efforts.\n\nCette sortie prévue de longue date,\nIl ne fallait pas qu''ils la ratent,\nEt c''est avec un rendez-vous de bonne heure,\nQu''ils partirent, dans la joie et la bonne humeur.\n\nLes initiés curieusement accoutrés,\nOnt progressivement vu leurs curiosités s''aiguiser,\nJusqu''à ce qu''enfin le moment soit venu,\nDe s''engouffrer dans des profondeurs inconnues.\n\nC''est alors qu''ils purent découvrir,\nCe terrain donc ils garderaient des souvenirs,\nFait de méandres, puits et conduites forcées,\nOù dans la boue, on peut se rouler.\n\nAlex se souvenant de Jujurieux,\nSe souvint qu''elle en était sortie pleine de bleus,\nMais grâce à de miraculeuses genouillères,\nElle ressortit de là, bien moins amère.\n\nFaisant confiance au descendeur,\nIl fallut combattre leurs peurs :\nPour une première descente en rappel,\nIl ne fallait pas qu''ils chancèlent.\n\nL''ambiance était plutôt aquatique,\nEt les bleus de travail n''étant pas très pratiques,\nChaque attente en haut d''un puits,\nFit que rapidement, l''air sembla rafraîchi.\n\nMais c''était évident, une fois en bas,\nLes chercher, on ne viendrait pas :\nIl fallait sur les cordes remonter,\nAvec ce que l''on appellait, croll et poignée.\n\nLa remontée sembla pour beaucoup très physique,\nEt il fallut faire un effort sur son psychique,\nPuis, pendant que certains servaient de marche pied,\nRenaud aussi, aidait les autres à remonter.\n\nLe retour tardif chez chacun,\nFut pour bon nombre, suivi d''un bon bain :\nLoin des activités citadines,\nCe ne fut pas une sortie anodine...\nTPST : 9 h',
		false,
		NULL,
		21,
		NULL,
		'fra',
		false
	),
	(
		67,
		6,
		NULL,
		'2008-10-13 15:39:49.000',
		NULL,
		3,
		'14:00:00'::interval,
		'00:10:00'::interval,
		5.0,
		4.0,
		9.0,
		'Travaux en cours (2008)',
		'Travaux d''exploration toujours en cours.\nPour toutes informations, contactez le CLPA',
		false,
		NULL,
		9,
		NULL,
		'fra',
		false
	),
	(
		224,
		5,
		NULL,
		'2009-08-18 21:11:54.000',
		NULL,
		4,
		'00:00:00'::interval,
		'00:00:00'::interval,
		8.0,
		3.0,
		8.0,
		'',
		'Attention au CO2 dans les inter-siphons.',
		false,
		NULL,
		6,
		NULL,
		'fra',
		false
	),
	(
		215,
		5,
		NULL,
		'2009-08-18 17:46:31.000',
		NULL,
		2,
		NULL,
		NULL,
		8.0,
		4.0,
		10.0,
		'Appréciation globale et conseils de prudence',
		'Cavité magnifique, bivouac ****. \nL''accès au réseau terminal se fait par des escalades extrêmement glaiseuses, il faut faire attention aux cordes.\nPrévoir d''amener dans son équipement un coinceur ou "goutte d''eau" pour pouvoir équiper certains passages en hors crue.\nIl est déconseillé d''aller à - 600 en cas de fortes pluies ou période assez humide ; le P114 "arrose".',
		false,
		NULL,
		12,
		NULL,
		'fra',
		false
	),
	(
		324,
		5,
		NULL,
		'2009-09-02 16:53:11.000',
		NULL,
		-4,
		NULL,
		NULL,
		7.0,
		7.0,
		9.0,
		'',
		'',
		false,
		NULL,
		5,
		NULL,
		'fra',
		false
	),
	(
		312,
		5,
		NULL,
		'2009-08-28 19:36:03.000',
		NULL,
		4,
		'00:00:00'::interval,
		'00:00:00'::interval,
		8.0,
		7.0,
		9.0,
		'',
		'Très jolie cavité, assez complexe.\n\nDemander l''autorisation au gérant de la grotte.',
		false,
		NULL,
		13,
		NULL,
		'fra',
		false
	),
	(
		338,
		5,
		NULL,
		'2009-09-22 04:51:27.000',
		NULL,
		4,
		NULL,
		NULL,
		6.0,
		8.0,
		10.0,
		'',
		'Cavité d''initiation à la verticale et à l''équipement esthétique.',
		false,
		NULL,
		15,
		NULL,
		'fra',
		false
	),
	(
		376,
		5,
		NULL,
		'2009-11-14 06:51:15.000',
		NULL,
		3,
		NULL,
		NULL,
		7.0,
		7.0,
		10.0,
		'Cavité d''initiation jusqu''à la salle Hydrokarst',
		'Cavité praticable en crue jusqu''à la salle Hydrokarst (équipement hors crue possible), tout en sachant que certains ressauts arroseront et le spéléo sera mouillé malgré tout.\nPour ce qui est du hors crue, il faut quand même faire attention.\nLa salle Hydrokarst peut se mettre en charge lors de très grosses crues, et le méandre jonctionnant la salle Hydrokarst et le bas du Toboggan peut alors siphonner.\n\n\nJusqu''à la salle Hydrokarst, c''est effectivement une chouette balade ; initiation possible avec des novices qui ont un minimum de condition physique...\n',
		false,
		NULL,
		21,
		NULL,
		'fra',
		false
	),
	(
		391,
		1,
		NULL,
		'2009-12-16 09:56:47.000',
		NULL,
		4,
		'09:30:00'::interval,
		'00:15:00'::interval,
		6.0,
		5.0,
		10.0,
		'Traversée Saints de Glace -> Trou Qui Souffle',
		'La traversée est intéressante sur les deux parties verticales : entrée par SdG, les puits et la salle HydroKarst + sortie par les grands puits du TQS. En outre, la partie étroite et boueuse à mi-parcours peut en décourager certains... Cette sortie vaut vraiment le coup mais attention à bien avoir la topo avec sois, voire même la boussole car il y a des endroits assez labyrinthiques !',
		false,
		NULL,
		21,
		NULL,
		'fra',
		false
	),
	(
		398,
		2,
		NULL,
		'2009-12-30 22:27:52.000',
		NULL,
		3,
		'08:00:00'::interval,
		'00:10:00'::interval,
		9.0,
		4.0,
		8.0,
		'Appréciation et remarques en 2009',
		'Contacter le propriétaire pour avoir l''autorisation d’accès.\nToujours aussi bien ! \nLe shunt décrit rend l’accès à la galerie du Tac o Tac très "rapide".\niI y a un autre shunt qui mène à l''extrémité de la galerie de la nuit blanche plus sympa car on fait alors toute la galerie avec sa section en tube et la cavité parait plus importante. ',
		false,
		NULL,
		17,
		NULL,
		'fra',
		false
	),
	(
		849,
		4,
		NULL,
		'2010-02-19 22:35:45.000',
		NULL,
		2,
		'05:00:00'::interval,
		'00:01:00'::interval,
		6.0,
		5.0,
		10.0,
		'Temps d''approche et de visite - Avertissement',
		'ATTENTION : Il convient d''être très attentif aux conditions climatiques avant de s''engager dans la cavité.',
		false,
		NULL,
		4,
		NULL,
		'fra',
		false
	),
	(
		890,
		1,
		NULL,
		'2010-06-07 13:39:03.000',
		NULL,
		4,
		NULL,
		'10:00:00'::interval,
		9.0,
		7.0,
		10.0,
		'Etat de l''équipement en 2010',
		'La cavité a été rééquipée en 2009-2010 : \n- du fossile jusqu''à la cascade de 12 mètres (C12), par des échelons et des broches (prendre une corde pour le rappel de la C12 (30 m minimum), et pour d''autres ressauts si besoin.\n- la partie fossile entre le P40 et le siphon 1 : cordes neuves sur broches.\n\nIl n''y a plus de fil clair, sauf 2 entre le siphon 1 et le siphon 2.\n',
		false,
		NULL,
		14,
		NULL,
		'fra',
		false
	),
	(
		984,
		4,
		NULL,
		'2012-03-21 17:45:26.000',
		NULL,
		4,
		'09:00:00'::interval,
		'00:10:00'::interval,
		7.0,
		4.0,
		9.0,
		'Témoignage de visite (2012)',
		'Paumatoire mais superbe!\nAller - retour jusqu''au siphon des pas perdus avec un détour par la (grande) salle des pas perdus.',
		false,
		NULL,
		9,
		NULL,
		'fra',
		false
	),
	(
		1002,
		4,
		NULL,
		'2012-07-30 18:53:37.000',
		NULL,
		4,
		'06:00:00'::interval,
		'00:01:00'::interval,
		9.0,
		8.0,
		10.0,
		'Sortie aller-retour par l''entrée de la carrière jusqu''à la galerie des marmites - Temps passé (voir icônes) et appréciation',
		'Superbe !',
		false,
		NULL,
		3,
		NULL,
		'fra',
		false
	),
	(
		1054,
		1,
		NULL,
		'2013-05-02 23:51:25.000',
		NULL,
		4,
		'04:30:00'::interval,
		'00:20:00'::interval,
		7.0,
		7.0,
		7.0,
		'Fiche d''équipement',
		'Dans la fiche d''équipement j''ai enlevé les 4 sangles : inutiles.',
		false,
		NULL,
		7,
		NULL,
		'fra',
		false
	),
	(
		2309,
		5,
		NULL,
		'2014-08-02 21:26:34.000',
		NULL,
		4,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		'CP16 : accès au réseau de la Combe aux Puaires',
		'Le CP16 représente un accès particulièrement facile et rapide au réseau de la Combe aux Puaires. \n\nLe CP16 présente cependant encore un défaut important : malgré la découverte d’un nouvel itinéraire dans le puits d’entrée, il ne faut guère espérer une ouverture avant fin août ou début septembre. \nLa période d’exploration est forcément courte.',
		false,
		NULL,
		2,
		NULL,
		'fra',
		false
	),
    (
		2624,
		4,
		NULL,
		'2014-11-02 20:28:43.000',
		NULL,
		3,
		'09:00:00'::interval,
		'00:05:00'::interval,
		8.0,
		5.0,
		6.0,
		'Ma première visite de la Leicasse',
		'Plusieurs shunts, du volume. Superbe!\nEn période de chasse bien contacter le propriétaire (voir avec le CDS34) avant de vous rendre sur place pour vérifier qu''une battue n''est pas organisée!\n',
		false,
		NULL,
		17,
		NULL,
		'fra',
		false
	),
	(
		2671,
		4,
		NULL,
		'2015-04-16 01:16:02.000',
		NULL,
		4,
		'10:00:00'::interval,
		'00:10:00'::interval,
		9.0,
		7.0,
		8.0,
		'Temps de visite jusqu''en haut du P40, en 2015 : 10 heures',
		'Sortie d''une dizaine d''heures avec le SCM jusqu''en haut du P40. \nIl y avait beaucoup d''eau (plus de 40 à l''échelle de l''entrée) et les cascades étaient grandioses !',
		false,
		NULL,
		14,
		NULL,
		'fra',
		false
	),
	(
		2667,
		4,
		NULL,
		'2015-04-09 16:28:44.000',
		NULL,
		4,
		'06:00:00'::interval,
		'00:15:00'::interval,
		8.0,
		6.0,
		10.0,
		'Traversée TQS -> Saints de Glace',
		'Très belle travsersée faite avec la CoJ un lendemain de pluie avec pas mal d''eau dans TQS et dans Saints de Glace. Superbe!!\nOn a fait un petit détour vers le siphon depuis la salle Hydrokarst avant de remonter le méandre des Saints de glace.\nTout était équipé pour la CoJ mais nous avons déséquipé le méandre Francois et les Saints de Glace à la remontée.',
		false,
		NULL,
		20,
		NULL,
		'fra',
		false
	),
	(
		2884,
		4,
		NULL,
		'2016-03-16 19:31:12.000',
		NULL,
		4,
		'20:00:00'::interval,
		'00:01:00'::interval,
		8.0,
		4.0,
		10.0,
		'Expérience personnelle',
		'Sortie club avec le SCM jusqu''à la rivière en équipant et déséquipant (9 kits). \nOn s''est trompé dans le méandre de l''Ankou en prenant le bas du méandre (1h30 de perdu !) Il faut bien rester en haut du méandre ! \nLes grands puits terminaux et la rivière sont superbe !',
		false,
		NULL,
		12,
		NULL,
		'fra',
		false
	),
	(
		2885,
		5,
		NULL,
		'2016-03-17 01:55:19.000',
		NULL,
		3,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		'Conseil pour le méandre de l''Ankou',
		'Comme indiqué dans le témoignage précédent, il faut rester (presque) en haut du méandre de l''Ankou pour éviter de se retrouver dans un cul-de-sac.\nPour se guider, on pourra tenter de suivre, outre les traces de passage parfois trompeuses, d''anciens micro-perçages destinés à faciliter un éventuel élargissement du méandre en cas de secours difficile...',
		false,
		NULL,
		12,
		NULL,
		'fra',
		false
	),
	(
		2973,
		5,
		NULL,
		'2016-08-10 11:48:49.000',
		NULL,
		4,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		'Année de découverte',
		'Joël, si tu as des sources fiables, n''hésite pas à corriger directement le champ "année de découverte".',
		false,
		NULL,
		11,
		NULL,
		'fra',
		false
	),
	(
		3041,
		5,
		NULL,
		'2016-11-17 20:21:08.000',
		NULL,
		0,
		'17:00:00'::interval,
		'01:00:00'::interval,
		NULL,
		NULL,
		NULL,
		'De la cascade Jean Dupont au bivouac -900 m',
		'Course réalisable uniquement en hiver ; attention au redoux possible et aux risques d''avalanche.\nTemps d''approche à partir du refuge quand on connait les passages clefs. ; il est facile de se perdre avec la neige, surtout si le brouillard est de la partie...\nCourse magnifique, grandiose. \nCela reste une course d''envergure, même si elle est techniquement assez facile. \nNe pas oublier que nous sommes constamment dans les embruns et le souffles des cascades. \nAttention, la course est longue, le TPST affiché est dans le cas ou la cavité est en grande partie équipée ; sinon, compter plusieurs sorties pour équiper la cavité jusqu''au fond.\nContacter le GS Vulcain pour plus d''infos quant au conditions, et au matériel disponible sur place.\nToujours en cours d''exploration...',
		false,
		NULL,
		1,
		NULL,
		'fra',
		false
	),
	(
		3052,
		1,
		NULL,
		'2017-01-27 17:28:38.000',
		NULL,
		-1,
		'12:00:00'::interval,
		'03:00:00'::interval,
		10.0,
		5.0,
		10.0,
		'Lieu vers albums photos',
		'Photos de 1984 prise par Laurent\nhttps://goo.gl/photos/G42QVk25GrtECUTk9',
		false,
		NULL,
		17,
		NULL,
		'fra',
		false
	),
	(
		3104,
		5,
		NULL,
		'2017-04-18 18:41:15.000',
		NULL,
		0,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		'Les travaux prévus en juillet 2017 sont reportés en octobre 2017',
		'Communiqué du CDS 21\n \nInitialement prévu du 5 au 12 juillet 2017, les travaux à la Combe aux Prêtres ont été reportés en octobre 2017[ref]http://speleo-cote-dor.cds21.org/2017/07/25/travaux-a-la-combe-aux-pretres/[/ref].\n\nDans le cadre de l’équipement et de la sécurité des sites de pratique, le CDS21 a décidé de réaliser des travaux durant la période du 12 au 17 octobre 2017 sur l’entrée historique de la Combe aux Prêtres. De ce fait la cavité ne sera pas accessible par cette entrée.\n\nCes travaux consistent au démontage du toit en lave au dessus du premier puits d’accès. A la place il y aura un toit et un encadrement solide en maçonnerie garantissant une parfaite protection des pratiquants.\n\nL’entrée par le Gouffre de la Rochotte reste bien évidemment accessible. Un panneau indiquant les prochains travaux sera installé à l’entrée de la Combe.\n\nMerci dans prendre note et de diffuser\n\nEt merci de votre compréhension…\n\nLe CDS 21',
		false,
		NULL,
		3,
		NULL,
		'fra',
		false
	),
	(
		3249,
		2,
		NULL,
		'2018-11-23 14:23:00.000',
		NULL,
		3,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		'ETAT DES EXPLORATIONS EN 2018-2020',
		'La cavité est toujours en exploration par le CLPA en 2018 et 2020\nPrière de respecter les équipements mis en place dont certains sont régulièrement volés. Ne pas poser de flêchages et autres marques fluorescentes !.\nLe CLPA, inventeur de la cavité, contribue à l''entretien de ces équipements dans la mesure de ses moyens.   \n\nUne monographie complète de la cavité est en cours. Elle est pratiquement terminée Elle sera publiée courant 2020. ',
		false,
		NULL,
		9,
		NULL,
		'fra',
		false
	),
	(
		3391,
		3,
		NULL,
		'2019-07-01 10:52:57.000',
		NULL,
		1,
		'10:00:00'::interval,
		'00:20:00'::interval,
		7.0,
		5.0,
		8.0,
		'Une belle visite de près de 10h00 - Juin 2019',
		'Une très belle visite jusque après la C12.\nNous nous sommes arrêté là, car la vire en fixe de la C12 est plus que pourrie ! Rongée à moitié contre une plaquette ! Pas sécuritaire du tout. \nPrévoyez votre propre corde pour passer et accéder à la grande barrière non loin de là. \nLa plupart des vires sont HS (arrachée). Certainement le débit important d''eau par période. \n\nVidéo de la sortie : https://www.youtube.com/watch?v=AGq0dB81Zzk ',
		false,
		NULL,
		14,
		NULL,
		'fra',
		false
	),
	(
		3427,
		5,
		NULL,
		'2019-09-07 17:42:51.000',
		NULL,
		4,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		'Recommandations du CDS 64',
		'1 - ATTENTION AUX CRUES\n\nEn cas de forte crue, les deux derniers puits (P54 et P47) sont très arrosés et deviennent difficiles voir impossibles à remonter. \nDe même, la progression dans la rivière peut se révéler très dangereuse notamment le changement de rive avant la cascade de 8 m, la vasque juste avant l''embarcadère et les rapides. \nPour ces raisons, les périodes de fortes pluies et/ou de fonte des neiges sont à éviter.\n\n\n\n2 - PRÉCAUTIONS DE PROGRESSION\n\nPour la partie aquatique (depuis l''Embarcadère), deux choix s''offrent à vous /\n- néoprène complète \nou \n- pontonnière + canot + 25 mètres de drisse de rappel.\n\nLa progression horizontale n''est pas toujours évidente ; pensez à vous munir d''une corde de 15 à 20 mètres pour vous assurer dans certains passages ou pour remplacer une corde fixe abîmée.\n\n',
		false,
		NULL,
		10,
		NULL,
		'fra',
		false
	);
