\c grottoce;

INSERT INTO public.t_location (
		id,
		id_author,
		id_reviewer,
		date_inscription,
		date_reviewed,
		relevance,
		title,
		body,
		id_entrance,
		id_language,
		is_deleted
	)
VALUES (
		305,
		5,
		NULL,
		'2009-09-02 16:53:33.000',
		NULL,
		4,
		'Accès piste',
		'Piste normalement fermée par une barrière.',
		5,
		'fra',
		false
	),
	(
		1,
		6,
		NULL,
		'2008-07-28 19:35:20.000',
		NULL,
		3,
		'Accès',
		'A partir de Neuville/Ain, prendre la D42 en direction de Meyriat et Hautecourt. Environ 1 km apres Fromente prendre à droite sur la D59 en direction de Hautecourt.  Après la deuxième intersection D81 (Bohas-Meyrat) - D59 (Hautecourt) continuer sur la droite et se garer 200m plus loin en bordure gauche. Sur notre droite prendre un chemin en terre (le premier depuis le croisement). Pour éviter tout problème avec le propriétaire, il est préférable de se garer avant de prendre le chemin en terre.\nAu bout de 200 m cette piste finit de longer les champs et tourne a gauche pour pénétrer dans le bois. La prendre. Apres encore 200 m un chemin part a droite vers une clairiere/coupe de bois. Juste apres la piste se transforme tout droit en chemin plus etroit : prendre alors la piste a droite, puis au bout de 200 m prendre la piste de gauche. 40m après prendre à gauche vers la clairiere. 25m plus loin le gouffre s''ouvre sur votre gauche en bord de clairiere. Il est entouré d''un grillage et un panneau en indique l''entrée.\nAttention, la forêt est un vrai labyrinthe de buis.',
		7,
		'fra',
		false
	),
	(
		2,
		6,
		NULL,
		'2008-07-29 18:32:18.000',
		NULL,
		1,
		'Coordonnées',
		'Coordonnées Lambert II Centre (km) : X= 943,37 Y= 132,12 Z=1840 (entrée V4)[ref]"Gouffre Jean-Bernard", sur le site du GS Vulcain : https://www.groupe-speleo-vulcain.com/explorations/explorations-a-samoens/gouffre-jean-bernard/[/ref].\nATTENTION : Ces coordonnées Lambert II Centre ne sont pas tout à fait équivalentes aux coordonnées WGS84 décimales, pourtant également fournies par un document du GS Vulcain[ref]Synthèse topographique 2010 : https://www.groupe-speleo-vulcain.com/wp-content/uploads/2011/03/JB-Coupe1991.pdf[/ref].\n\nA partir de Samoëns, aller se garer sur le parking qui permet d''accéder au Lac des Chambres et au refuge du Folly.\nMonter au refuge ; il faut compter 1h30 de marche (600 mètres de dénivelé). \nA partir du refuge, prendre la direction du lac des Chambres. \nUn peu avant le lac, prendre sur la gauche. \nL''entrée V4 est un petit porche. \nCompter 1h30 de marche entre le refuge et l''entrée.',
		1,
		'fra',
		false
	),
	(
		7,
		1,
		NULL,
		'2008-08-02 21:34:30.000',
		NULL,
		0,
		'Consignes locales',
		'Pour toute info sur cette cavité vous pouvez contactez le club spéléo CLPA : contact.clpa-chez-laposte.net \nLa cavité est d''accès libre. \nPrière de respecter les équipements en place et signaler au CLPA les matériels défectueux constatés. \n\nL''entrée décrite par la présente fiche concerne le trop-plein temporaire pénétrable situé en tête de talweg et exhalant un trés fort courant d''air.\nCe trop-plein est situé au-dessus de la source pérenne importante appelée "Foux de Saint Jean" ou "Foux des Sicards".\n\nLes coordonnées suivantes ont été également signalées pour l''émergence pérenne de la "Foux de Saint-Jean" alias "Foux des Sicards3 : \nLatitude    : 43.8341 degrés N.\nLongitude : 3.61652 degrés E.',
		9,
		'fra',
		false
	),
	(
		8,
		4,
		NULL,
		'2008-08-04 16:58:07.000',
		NULL,
		2,
		NULL,
		'A partir de Francheville prendre le D103 en direction de Vernot. \n1,5 Km après la sortie du village, se garer à gauche dans une ancienne carrière. \nL’entrée du gouffre se trouve dans le front de taille de la carrière.[ref]Les spéléos à Francheville : http://www.mairie-francheville21.fr/index.php?option=com_content&view=article&id=61:les-speleos-a-francheville&catid=18&Itemid=120[/ref]\n\nIl est possible de dormir dans un ancien lavoir à proximité. ou au gite de "la clairière" à 20 minutes à pied de Francheville\n\nTopographie et source : http://cds21.org/cavites_cotedor/topo/cap.htm',
		3,
		'fra',
		false
	),
	(
		157,
		6,
		NULL,
		'2009-03-29 14:22:00.000',
		NULL,
		2,
		'Accès',
		'Les coordonnées GPS de Grottocenter ont été validées le 1er novembre 2014.\n\nDu hameau du Coulet, emprunter la piste qui conduit au ruines du Mas de Larret. \nAu bout de 600 mètres, tourner à gauche. \nAu bout de 1,5 km de piste en état moyen (voiture surélevée conseillée), se garer sur un replat à droite de la piste (coordonnées du parking N43.81996 E003.55991). \nDe là, un petit sentier mène à l''entrée de l''aven distant d''environ 150 mètres.\nL''entrée est maçonnée et la porte n''existe plus.\n\nExplorations interdites en périodes de chasse.\n\nPendant la période "tolérée" le propriétaire (Mr Buresi) demande à ce qu''un seul véhicule soit garé à proximité du trou (cf. supra). \nLes autres doivent être garés au bord de la route juste à la sortie du Coulet (aire de parking herbeuse à droite).',
		17,
		'fra',
		false
	),
	(
		228,
		5,
		NULL,
		'2009-08-18 21:13:15.000',
		NULL,
		4,
		'Sentier',
		'Le sentier qui descend à la gortte se situe dans l''épongle de la route. Il faut descendre d''une 20aine de mètres.',
		6,
		'fra',
		false
	),
	(
		216,
		3,
		NULL,
		'2009-08-16 11:56:27.000',
		NULL,
		4,
		'Accès',
		'A la sortie du village, au bord de la route qui mène à Lagarde d’Apt, l’ancienne entrée dangereuse de l’aven est surmontée d’une grande chèvre métallique. \nLa nouvelle entrée a été forée en 2015 et est situé à une dizaine de mètres de la chèvre sous une bouche d''égout.\n\nNe pas se garer proche des habitations mais plutot directement sur la pelouse sur le terrain de l''entrée du Souffleur.',
		12,
		'fra',
		false
	),
	(
		295,
		5,
		NULL,
		'2009-08-28 19:36:30.000',
		NULL,
		4,
		'Note accès',
		'Grotte touristique, fléchèe dans le village.',
		13,
		'fra',
		false
	),
	(
		323,
		3,
		NULL,
		'2009-10-01 14:14:05.000',
		NULL,
		3,
		NULL,
		'Depuis la grotte touristique (grottes de Choranche), continuer le chemin en pied de falaise.\nSuivre le ruisseau en remontant, jusqu''au porche.',
		14,
		'fra',
		false
	),
	(
		384,
		1,
		NULL,
		'2009-12-30 21:31:52.000',
		NULL,
		3,
		'Accès alternatif',
		'Accés alternatif "par le haut", nettement plus long mais plus praticable.\nL''accés classique par "le bas" est praticable en dec 2010. \n\nDu coulet prendre la piste à l''est (GR) suivre le GR sur 1km et laisser à main gauche le départ du chemin d''accés par le bas. \nRapidement il y a un nouvel embranchement, suivre toujours le GR = aller à gauche cette fois. le chemin monte puis marque une épingle (2,7 km depuis le coulet). \nPrendre le chemin en face dans l''épingle et quitter le GR. \nCe chemin est barré par une clôture juste aprés ; ne pas oublier de refermer derrière soi. \nLa piste suit longuement une clôture à flanc de colline, sous le Serre des Pins, arrive à un replat et redescend plus nettement après un virage à gauche. \nLa piste change alors de versant en contournant un puech et descend toujours. \nAprès une épingle à cheveux à droite, le parking de l''aven se situe sur un replat entre deux puech (point coté 625 sur l''IGN)\nAccés à l''entrée de la grotte en descendant dans le petit talweg.\n\nATTENTION\nLa boucle "accés haut" - "accés bas" est parfaitement visible sur la vue satellite. \nLes chemins sont sur la carte IGN 1/25000.',
		17,
		'fra',
		false
	),
	(
		480,
		4,
		NULL,
		'2010-02-19 17:07:25.000',
		NULL,
		4,
		'Accès',
		'De la D911, quelques kilomètres au nord du pont de Lescheraines, il suffit de prendre la petite route qui descend vers le Chéran et vers l''entrée de la grotte. \nIl est possible de garer 4 à 5 voitures avant le pont, sur la droite.',
		4,
		'fra',
		false
	),
	(
		834,
		2,
		NULL,
		'2013-08-19 21:15:51.000',
		NULL,
		3,
		'Accès',
		'De Millau, prendre l''autoroute A75 vers Montpellier. \nA 30 kilomètres prendre la sortie 48 direction Cornus, Alzon ; puis au rond point prendre la direction des Infruts, La Pezade. \nTraverser la Pezade puis prendre la D 140 à droite vers Mas Raynal. \nOn laisse ce village sur la droite puis on continue la route sur 1 kilomètre et on emprunte alors un chemin à gauche (panneau indicateur : Abîme du Mas Raynal). \nLe chemin mène à moins de 100 mètres de la grande entrée (40 m x 20 m) située sur la gauche du parking.',
		18,
		'fra',
		false
	),
	(
		2360,
		1,
		NULL,
		'2014-08-02 21:25:44.000',
		NULL,
		3,
		'Note et accès',
		'Le digramme "CP" fait référence à la zone de la Combe aux Puaires.\n\nLe CP16 est situé à une trentaine de mètres à l’est du CP14, en contrebas de la falaise du CP15. \nLe gouffre s’ouvre à la faveur de la grande faille qui traverse l’ensemble des lapiaz de la Tête à l''Homme.',
		2,
		'fra',
		false
	),
	(
		2699,
		4,
		NULL,
		'2015-04-09 16:23:08.000',
		NULL,
		4,
		'Accès',
		'Au bord de la route sur la gauche en montant derrière une barrière bleu.',
		20,
		'fra',
		false
	),
	(
		5207,
		5,
		NULL,
		'2019-09-07 17:17:09.000',
		NULL,
		0,
		NULL,
		'Avant d''arriver à la station de ski, prendre à droite la route de l''espagne, passer devant l''ancien chalet des douanes et continuer vers le col de la PSM. \nOn aperçevra sur la droite une bergerie à 50 mètres de la route, au niveau du départ du télésiège des contrebandiers. \nOn pourra garer les véhicules en bordure de route (demander aux bergers).\n\nPrendre ensuite le sentier qui passe devant la bergerie et se diriger vers la dépression herbeuse de Caque. \nPrendre un petit sentier (peu marqué) sur la droite pendant 50 mètres (ne pas aller jusqu''au sommet du lapiaz) puis se diriger vers la gauche, dans le lapiaz, sur 100 mètres. \nUn sentier discret mène au GL 102[ref]* Fiche cavité du CDS 64 : http://cds64.org/WordPress3/wp-content/uploads/2017/07/GL_102.pdf[/ref].',
		10,
		'fra',
		false
	);
