\c grottoce;

INSERT INTO public.t_rigging (
		id,
		id_author,
		id_reviewer,
		date_inscription,
		date_reviewed,
		relevance,
		title,
		obstacles,
		ropes,
		anchors,
		observations,
		id_entrance,
		id_exit,
		id_point,
		id_language,
		is_deleted
	)
VALUES (
		20,
		1,
		NULL,
		'2009-03-29 11:48:00.000',
		NULL,
		2,
		'Réseau du Petit Fond',
		'Escalade',
		NULL,
		NULL,
		'En fixe',
		17,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		17,
		1,
		NULL,
		'2009-03-29 11:40:40.000',
		NULL,
		2,
		'Accès par l''ancienne entrée',
		'R7\nR2|;|R5',
		'16 m|;|10 m',
		'AN + 1S|;|AN',
		'Etroiture|;|',
		17,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		18,
		6,
		NULL,
		'2009-03-29 11:45:39.000',
		NULL,
		2,
		'Des Meulières aux galeries de la Nuit Blanche par l''ancien réseau de puits',
		'R3|;|R8|;|P12|;|P10|;|P35',
		'|;|10 m|;|20 m|;|16 m|;|50 m',
		'|;|AN|;|3S + 1DEV|;|2S + 1S|;|2S (MC) + 2S + 1S (MC) + 2S',
		'Etrier en place|;|Quitter avant le fond sur la gauche.|;||;||;|Equiper le méandre en MC au plafond.',
		17,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		19,
		6,
		NULL,
		'2009-03-29 11:47:14.000',
		NULL,
		2,
		'Des Meulières aux galeries de la Nuit Blanche par le nouveau réseau de puits',
		'R5|;|Vire|;|Puits',
		'Echelle rigide 6 m|;||;|',
		'|;||;|',
		'En fixe|;||;|',
		17,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		1,
		4,
		NULL,
		'2008-08-04 17:01:02.000',
		NULL,
		4,
		'',
		'La Vire, le R3 de la Galerie des Gours et le R4 du Réseau Ben|;|P10|;|MC|;|P20|;|Trémie Galerie Nord MC + P7',
		'Equipés en fixe|;|C65|;|Même corde|;|Même corde|;|C38 (facultatif)',
		'Equipés en fixe|;|AN (barrière) + 2Br + 2Br|;|2Br + 1Br + 1Br + 1Br + 1Br + 1Br + 2Br|;|2Br + 2Br + 2Br\n|;|6 x (1Br + 1S)',
		'A chaque visite il est important de vérifier l’état des cordes et amarrages. |;|Les 2 premières broches sous le porche font passer la corde très près d''un becquet, préférer 2 Spits disponible à coté\nPossibilité d''équiper le P10 fractionné en double avec une corde de 15m (prévoir 2S + 2B)|;|Il est préférable d''accéder au P20 final après la lucarne de la main courante plutot qu''avant|;|Possibilité d''équiper en double le dernier P20 direct avec une corde de 22m (prévoir 2S +2S)|;|La trémie peut se désescalader mais il est préférable de l''équiper en MC pour des débutants ou des personnes mal chaussées)',
		3,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		2,
		2,
		NULL,
		'2019-06-21 21:32:51.000',
		NULL,
		4,
		'',
		NULL,
		NULL,
		NULL,
		NULL,
		4,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		3,
		6,
		NULL,
		'2008-07-28 20:00:34.000',
		NULL,
		4,
		'Objectif Fond',
		'P34|;|E9|;|P28|;|Lucarne\nR10\nR6|;|P20 \nP23|;|Total',
		'C40|;|C15|;|C25|;|C25|;|C65|;|185m',
		'AN (arbre)|;|2S|;|3S +1S à-9m et 1S à -15m\n|;|CP + 2S - MC\n1S + 1S à -1m\n1S|;|CP+2S +1S + 1S + 1S à -10m\n1S + 1S à -1m|;|19 plaquettes',
		'|;|équipement en fixe|;|Certains spits sont doublés par des goujons de 12 mm|;|2S avant la lucarne. bien s''engager pour équiper proprement\nCertains spits sont doublés par des goujons de 12 mm|;|Certains spits sont doublés par des goujons de 12 mm|;|A partir de l''escalade, toutes les cordes peuvent être reliées.\nAttention, quelques spits sont à ménager',
		7,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		4,
		6,
		NULL,
		'2008-10-13 15:38:08.000',
		NULL,
		4,
		'De l''entrée au Carrefour',
		'P10 coulée|;|V10 lac|;|R3 blocs|;|R4 laminoir|;|E5 début galeries du Minautore|;|V10 |;|P10 salle à manger|;|V10 siphon salle à manger',
		'20 m ou échelle|;|Câble|;|7 m|;|7 m|;|10 m|;|15 m|;|15 m ou échelle|;|20 m',
		'Nat|;|3 spits|;|Nat|;|Nat|;|Nat|;|Nat + 1 spit|;|Nat + 1 spit|;|3 spits',
		'Parfois en fixe|;|En fixe|;|En fixe|;|En fixe|;|En fixe|;|En fixe|;|En fixe|;|En fixe',
		9,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		5,
		6,
		NULL,
		'2009-01-20 21:27:57.000',
		NULL,
		2,
		'Du Carrefour au siphon des Pas Perdus',
		'E8|;|E3|;|P5 galerie latérale siphon suspendu PP aval|;|P3|;|E13 siphon suspendu PP amont|;|E6',
		'15m|;|5 m|;|6 m|;|5 m + échelle de corde|;|20m|;|10 m',
		'Nat + 1Spit|;|1Spit|;|1Spit|;|2 Spits|;|3 Spits|;|1Spit',
		'En fixe|;|En fixe|;|En fixe|;|En fixe|;|En fixe|;|En fixe :\nPuits / Cheminée de jonction avec la salle des Pas Perdus',
		9,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		6,
		6,
		NULL,
		'2009-01-20 21:37:36.000',
		NULL,
		2,
		'Le Réseau Supérieur (P100 / salle du Miroir / cheminée de l''Ours)',
		'E10|;|P"100"|;|Vire salle du Miroir|;|P14 accès siphon suspendu du Réseau Supérieur|;|E5 accès siphon suspendu du Réseau Supérieur|;|Vire siphon suspendu du Réseau Supérieur|;|E8 accès cheminée de l''Ours|;|Vire 10 m|;|E80|;|P7 accès puits "CNS"|;|P18 + P28 (puits "CNS")|;|P15 + P8 accès puits parallèles et puits de la Queue de Dragon|;|P15|;|R8 + R4 + R3|;|P6|;|Puits de la Queue de Dragon|;|',
		'15 m|;|60 m\n80 m|;|2x10 m|;|20 m|;|15 m|;|10 m|;|Echelle de corde 10 m|;|Corde15 m|;||;|15 m|;|80 m|;|20 m + 15 m|;|20 m|;||;|10 m|;||;|',
		'2 Spits|;|Spits|;|Spits|;|2 Spits|;|3 Spits|;|4 spits|;||;|5 spits|;|AN + Spits|;||;|AN + Spits|;||;||;||;||;|AN + Spits|;|',
		'En fixe|;|En fixe|;|En fixe|;|En fixe|;|En fixe|;|En fixe|;|En fixe|;|En fixe|;|En fixe jusqu''à +130|;||;||;||;||;||;||;||;|',
		9,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		7,
		1,
		NULL,
		'2009-01-20 21:39:47.000',
		NULL,
		2,
		'Du Carrefour à la salle du Belvédère et des Niphargus',
		'E3 + vire|;|Vire|;|E20|;|Vire|;|P15 salle des Niphargus|;||;|',
		'10 m + Echelle rigide|;|Câble 15 m|;|30 m|;|15 m|;|25 m|;||;|',
		'2 Spits|;|Nat + Spits|;|Nat + Spits|;||;|Nat + Spits|;||;|',
		'En fixe|;|En fixe|;|En fixe|;|En fixe|;|A équiper !|;||;|',
		9,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		8,
		1,
		NULL,
		'2009-01-20 21:42:13.000',
		NULL,
		2,
		'De la salle du Belvédère à l''étroiture Madonna',
		'P10|;|P5|;|E5|;|E15 réseau du Traître',
		'15 m|;|10 m|;|10 m|;|',
		'|;||;||;|',
		'En fixe|;|En fixe|;|En fixe|;|',
		9,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		9,
		1,
		NULL,
		'2009-01-20 21:46:08.000',
		NULL,
		2,
		'Cheminée des Niphargus',
		'P10|;|E20|;|E41|;|E100|;|Tb du "Dôme"|;|Tb15',
		'20 m|;|30 m|;|50 m|;||;|20 m|;|20 m',
		'Spits|;|Spits|;|Spits|;|Spits|;|2 Spits|;|2 AN',
		'En fixe|;|En fixe|;|En fixe|;|En fixe|;|En fixe|;|En fixe',
		9,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		10,
		1,
		NULL,
		'2009-01-20 21:57:57.000',
		NULL,
		2,
		'Cheminée du Phallus',
		'E 150',
		NULL,
		'AN + spits',
		'30 premiers mètres déséquipés',
		9,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		11,
		1,
		NULL,
		'2009-01-20 22:00:46.000',
		NULL,
		2,
		'Réseau du Labyrinthe',
		'E8',
		'10 m',
		NULL,
		'En fixe',
		9,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		12,
		5,
		NULL,
		'2019-09-07 17:54:36.000',
		NULL,
		4,
		'Equipement d''après le CDS 64',
		'P34\n|;|P50-P5-P13 : \n|;|R5-P20 \n|;|P14-P19: \n|;|P14\n|;|P16 + P 17\n|;|R5\n|;|P54\n|;|P47\n|;|MC\n|;|MC\n|;|R dans blocs|;|Cascade 8m\n|;|R3\n|;|MC10\n|;|P12\n|;|P6\n|;|R3\n|;|R entre blocs\n|;|R8 : \n|;|R6 des rapides',
		'C47|;|C100|;|C43|;|C55|;|C25|;|C50|;|C8|;|C70|;|C60|;| C10|;|C10|;|C12|;|C25|;|C5 |;|C15|;|C19 |;|C10 |;|C5 |;|C5|;|C18 |;|C15',
		'5 broches|;|11 broches + 1 AN|;|8 broches|;|8 broches|;|4 broches|;|11 broches + 1 dev/broche|;|2 broches|;|5 broches|;|7 broches|;|en fixe|;|en fixe|;|en fixe|;|5 broches|;|en fixe|;|en fixe|;|en fixe|;|en fixe|;|en fixe|;|en fixe|;|en fixe 5 broches|;|',
		'|;||;||;||;||;||;||;||;||;||;||;||;||;||;||;||;||;||;||;|Embarcadère|;|',
		10,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		13,
		1,
		NULL,
		'2009-11-06 17:58:24.000',
		NULL,
		4,
		'Fiche d''équipement hors crues (PP - AREHPA 2005)',
		'Forage + ressaut|;|P5|;|P10|;|P36|;|P48|;|P42|;|P28|;|P4|;|Méandre d''ankou|;|P70 (Puits Ayme)|;|P80 (Puits de l''Astrolabe)|;|R80 (Série de puits)|;|P114',
		'25 m|;|15 m|;|20 m|;|80 m|;|80 m|;|70 m|;|50 m|;|10 m|;||;|100 m|;|30 m + 100 m|;|60 m + 60 m|;|200 m',
		'Prévoir de la dyneema pour le départ de puits\n2S + 2S|;|2S + 2S à -5|;|4S|;|20S + 1AN + 1DEV|;|16S|;|14S|;|8S|;|1AN + 3S|;||;|16S + 1AN|;|20S|;|20S + 1DEV|;|24S + 1DEV',
		'Ne pas utiliser l''ancienne entrée (sous la chèvre) qui est dangereuse !|;||;||;||;||;||;|Arrivée à -200|;||;|Bien rester en haut du méandre ! Le bas du méandre est très étroit et se termine sur un puits sans issue.|;||;|Rabouter dans la corde précédente. Prévoir des déviations si nécessaire|;|Prévoir une C40 en plus au cas où. Prévoir des déviations si nécessaire|;|Arrivée dans la rivière',
		12,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		14,
		5,
		NULL,
		'2009-08-28 19:36:53.000',
		NULL,
		4,
		'Equipé en fixe.',
		NULL,
		NULL,
		NULL,
		NULL,
		13,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		15,
		1,
		NULL,
		'2010-06-10 13:30:00.000',
		NULL,
		4,
		'Equipement jusqu''à la cascade de 12 mètres (alias ',
		'Lac d''entrée|;|Vire au dessus du lac d''entrée|;|Cascade de 12 mètres',
		'40m de filin flottant si va et vient |;|C50 m|;|C30 m',
		'|;|monter de 5m, 2broches, partir sur la vire à droite 1broche, 1 broche, 1broche (maillon rapide à demeure, rouillé), 1 as sur concrétion, 1 an sur concrétion derrière une colone,2 broches, 1 broche, 1 broche|;|Broches',
		'|;|l''escalade de 5m depuis le lac est équipée de barreaux, la fin n''est pas sécurisable pour le premier à monter |;|Corde nécessaire pour le rappel de la cascade',
		14,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		16,
		1,
		NULL,
		'2009-03-29 11:39:17.000',
		NULL,
		4,
		'Nouvelle entrée aux galeries des Meulières',
		'P10 d''entrée|;|P6|;|R6|;|R10|;|P37|;|P35|;|TB10',
		'20 m\n(ou 40m pour faire les 2 puits)|;|12 m|;|12 m|;|15 m|;|95 m\n\n|;|Même corde|;|Corde 15 m',
		'1AN (arbre)\n2S\n2S vers -4 |;|AN\nou bien : 2S et dev sur amarge foré. 1S puis nat dans le meandre|;|AN + 1S|;|2S|;|2S\nMC\n2 Broches|;|2 Broches\nMC\n2 Broches\n2S ou AN pour accrocher le bout de corde au belvédère|;|',
		'Beaucoup d''araignées|;|ne pas descendre tout le puits. S''arréter 3m avant le fond pour prendre un méandre.|;|Départ étroit|;|Départ étroit|;|Contre parois jusqu''au palier intermédiaire|;|prévoir 1 mouskif supplémentaire pour éviter un frottement.\nA mi-hauteur penduler pour atteindre le belvédère.|;|En fixe à droite de la galerie.\n = Corde fixe en decembre 2010\nplein frottement à surveiller...',
		17,
		NULL,
		NULL,
		'fra',
		false
	);
INSERT INTO public.t_rigging (
		id,
		id_author,
		id_reviewer,
		date_inscription,
		date_reviewed,
		relevance,
		title,
		obstacles,
		ropes,
		anchors,
		observations,
		id_entrance,
		id_exit,
		id_point,
		id_language,
		is_deleted
	)
VALUES (
		21,
		1,
		NULL,
		'2009-04-03 22:20:28.000',
		NULL,
		2,
		'Réseau du Grand Fond',
		'V10|;|P23 (facultatif)|;|R45|;|P13|;|P5|;|P8|;|P6|;|P7|;|P8|;|P5|;|P11|;|P19',
		'|;|30 m|;||;||;||;||;||;||;||;||;||;|',
		'|;||;||;||;||;||;||;||;||;||;||;|',
		'En fixe?|;||;|Désescalade délicate|;||;||;||;||;||;||;||;||;|',
		17,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		22,
		1,
		NULL,
		'2009-12-30 22:06:51.000',
		NULL,
		4,
		'de la nouvelle entrée à la galerie de la nuit blanche',
		'P entrée P12?|;|2eme puits P8?|;|R3 ou 4|;|P8 (?)|;|"P100"\nne se descend pas en totalité|;|toboggan|;|R8 (?)',
		'C40|;|corde précédente|;| C6 (?)|;|C10 ou 15|;|C87|;|C25??|;|C15 (?)',
		'4 spits|;|2 spits + 1 AN + 2 spits ou 2 AN en bas|;|1 AN |;|2 spits + 2 spits |;|2 spits + AN en hauteur + 2 broches + 2 broches au pallier|;|2 spits|;|1 AN',
		'C40 enchaine les deux puits|;|ne pas descendre au fond enquiller le méandre à mi hauteur|;|facultatif (mais fort utile)|;|équipement possible sans MC|;|équipement strict minimum. + 2 broches facultatives possibles au pallier avant le plein vide|;|corde changée en juin 2016 (Gersam)|;|Ressaut d''accés galerie nuit blanche. Corde fixe fin 2009',
		17,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		23,
		2,
		NULL,
		'2013-08-19 21:11:35.000',
		NULL,
		4,
		'Par les puits parrallèles',
		'MC + P21 de l''entrée |;|R5|;|MC + P13 |;|dalle (R6 et P9) + P33|;|Total minimum :',
		'C38|;|C15|;|C28|;|C95|;|33 mousquetons sans plaquette',
		'1 AN + 1 AN (main courante) \n2B tête puits ou 1S + 1B\n2B + 2B|;|2B + 2B |;|MC et vire : 2B   \nY : 2B \n1 AN + 1 S|;|R6 et P9 : 2B + 2B + B + 2B + 2B + 2B \n\nP33 : 2B + 2B +dev/B + B\n|;|2 mousquetons avec plaquette',
		'Possibilité d''allonger la MC sur 2 B \n=> corde 48 m|;||;|En dernier : fractio jambon pour éviter un frottement. (prévoir 1 longue Dyneema).|;|Dans les deux cas, ne pas descendre jusqu''au fond mais penduler qq mètres avant le fond pour se poser sur le gros rocher en pente. Prévoir 1 sangle pour la DEV.\n \n|;|1 sangle\n1 Dyneema longue',
		18,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		24,
		4,
		NULL,
		'2016-10-12 23:49:45.000',
		NULL,
		4,
		'Grande verticale + vire d''accès',
		'Vire + Grand puits',
		'C30 + C100',
		'10 mousquetons\n1 plaquette\n3 sangles\n1 sangle longue\n1 kit pour frottement',
		'1 Nat \n1Spit \n3 Broches\n2 Nat sur poutre\nDev sur broche\nNat',
		18,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		25,
		6,
		NULL,
		'2008-09-19 19:03:55.000',
		NULL,
		4,
		'Accès à la salle Hydrokarst',
		'P11 |;|P9|;|P4|;|P6|;|R3|;|P3\nP5|;|P11 (salle hydrokarst)',
		'C24|;|C22|;|C13|;|C13|;|C5|;|C30|;|C20',
		'2S + 1B + 1B + 1S pour MC + 1S et 1B en y|;|1AN (bloc énorme) +1 B (ou 2 B selon le côté où l''on équipe) + 1 dev sur spit|;|2 B + 1 B + 1S et 1B en y|;|2 B + 1B + 1S et 1B (ou 2S) en y|;|2S|;|corde de 30 m, 2S (ou 1B) + 1B + 1S (ou 1B) + 2B (ou 2S)  en y|;|2B (ou 1S et 1B) + 2B en y',
		'B = broche|;|B = broche|;|B = broche|;|B = broche|;|équipement très facultatif |;|B = broche|;|B = broche',
		21,
		NULL,
		NULL,
		'fra',
		false
	);
