\c grottoce;
INSERT INTO public.t_description (
		id,
		id_author,
		id_reviewer,
		date_inscription,
		date_reviewed,
		relevance,
		title,
		body,
		id_cave,
		id_entrance,
		id_exit,
		id_massif,
		id_point,
		id_document,
		id_language,
		is_deleted
	)
VALUES (
		6666,
		4,
		NULL,
		'2020-11-02 20:10:18.000',
		NULL,
		1,
		'Un véritable labyrinthe',
		'On perd rapidement le sens de l''orientation...',
		6,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		6667,
		2,
		1,
		'2021-11-02 23:10:18.000',
		NULL,
		1,
		'Doc 6666',
		'Un document rattaché à la cavité 6',
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		6666,
		'fra',
		false
	),
	(
		5555,
		2,
		1,
		'2021-11-02 23:10:18.000',
		NULL,
		1,
		'Très jolie',
		'Cette cavité est magnifique !!',
		5,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		5556,
		2,
		1,
		'2021-11-02 23:10:18.000',
		NULL,
		1,
		'Doc 5555',
		'Un document rattaché à la cavité 5',
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		5555,
		'fra',
		false
	),
	(
		21,
		4,
		NULL,
		'2014-11-02 20:10:18.000',
		NULL,
		-3,
		'Le Labyrinthe',
		'(...)',
		NULL,
		17,
		NULL,
		NULL,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		1,
		4,
		NULL,
		'2008-07-29 17:45:32.000',
		NULL,
		-6,
		'Topographie et informations importantes',
		'Informations importantes: http://www.groupe-speleo-vulcain.com/explorations/explorations-a-samoens/gouffre-jean-bernard\n\nVoici la topo du réseau du Jean-Bernard, issue du site web du Groupe Spéléo Vulcain http://groupe.vulcain.free.fr :\n\nPlan en 2017 : https://www.groupe-speleo-vulcain.com/wp-content/uploads/2018/06/jb-Xav-2017-plan1000.pdf\nCoupe en 2017 : https://www.groupe-speleo-vulcain.com/wp-content/uploads/2018/06/jb-2017-coupe.pdf\n',
		NULL,
		1,
		NULL,
		NULL,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		2,
		5,
		NULL,
		'2016-11-17 19:34:16.000',
		NULL,
		3,
		' Du V4 à la cascade Jean Dupont (équipement et balisage en place)',
		'Les premiers -100m se font dans une conduite forcé ponctuée de quelques ressauts équipés jusqu''au puit des Savoyard (-25 m). \nJuste après le puits, descendre dans les éboulis. \nOn enchaine les Puits Alain (2 -15 m). \nOn suit un méandre jusqu''à un affluent du Jean-Bernard. \n3 ressauts dans l''affluent permettent d''atteindre la cascade Jean Dupont.',
		NULL,
		1,
		NULL,
		NULL,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		3,
		1,
		NULL,
		'2014-08-02 21:26:12.000',
		NULL,
		1,
		'Description générale',
		'L’entrée du CP16 est bouchée par un énorme névé quasiment en permanence. \nElle apparaît alors comme un simple abri sous roche protégeant un névé résiduel.\nEn réalité, le bouchon de neige et de glace protège un large puits de 25 mètres de profondeur qui amène dans une belle salle au sol recouvert de neige. \nSur la droite, un méandre surmonté d’une petite conduit forcée amène au sommet d’un beau puits de 14 mètres très propre. \nLe fond est irrémédiablement colmaté par un éboulis.\n\nLa suite se situe en réalité dans la salle d’entrée.\nUne escalade de 7 mètres permet de prendre pied dans un méandre descendant.\nUne dizaine de mètres étroits amènent au sommet d’un puits de 6 mètres.\nLe méandre continue un peu plus large, mais entrecoupé de concrétion jusqu’au sommet d’un puits de 5 mètres. \nLa galerie se sépare en deux puits qui se rejoignent peu après.\n \nLa cavité se développe alors sur une grande faille et les puits prennent du volume.\nPlusieurs paliers permettent d’atteindre le sommet d’un superbe puits circulaire de 48 mètres de profondeur.\nPlusieurs ressauts de tailles plus modestes peuvent ensuite se désescalader jusqu’à la cote -151 m où l’on butte sur un méandre impénétrable parcouru par un léger courant d’air.\n\nLa suite se situe en réalité à une dizaine de mètre du fond du P48 où un pendule permet de prendre pied sur une margelle qui donne accès à un nouveau méandre descendant de 1 mètre de large environ et parcouru par un violent courant d’air.\n\nCette lucarne donne accès à une courte galerie, avec deux ressauts, qui mène à un petit carrefour : \n\nDes boyaux étroits et malcommodes, dans l’axe de la galerie, amènent au sommet d’un vaste puits, la base du puits du Rasoir.\nDe fait il vaut mieux prendre un boyau horizontal en paroi droite qui débouche en lucarne dans le même puits du Rasoir.',
		NULL,
		2,
		NULL,
		NULL,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		20,
		4,
		NULL,
		'2014-11-02 20:05:22.000',
		NULL,
		-1,
		'Le Grand Fond',
		'De la base du P35, tourner à gauche dans la galerie de la Nuit Blanche et traverser un P23 en vire. \nIl est conseillé de descendre ce dernier pour aller visiter un méandre spectaculairement beau qui conduit après quelques ressauts à deux siphons dont le point bas est à -248.\n\nRevenu dans la galerie, on progresse de 80 mètres jusqu''au "Mur de la Honte" qui défend l''accès à un laminoir de 90 mètres suivi d''une série de ressauts sur 45 mètres, délicats à désescalader. \n\nOn poursuit dans un réseau de conduits surbaissés labyrinthiques, suivi d''une belle galerie en conduite forcée entrecoupée de trois puits de 13, 5 et 8 m jusqu''à -270. \n250 mètres de galeries basses entrecoupées de petits puits de 6, 7, 8, 5, 11 et 19 m conduisent à un siphon à la côte -331.\n(...)',
		NULL,
		17,
		NULL,
		NULL,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		4,
		4,
		NULL,
		'2008-08-04 19:42:37.000',
		NULL,
		-2,
		'Description générale',
		'L''entrée se situe dans la paroi est de la carrière. \nUne succession de puits et de fissures plus ou moins étroits donne, après 52 mètres de descente, sur la rivière souterraine que l''on parcourt sur 200 mètres. \nEnsuite, une chatière longue d''une vingtaine de mètres et étroite permet d''accéder à la deuxième partie du réseau.\n\nCette dernière est constituée de galeries spacieuses, parfois très hautes, entrecoupées de grandes salles, et recoupant la rivière souterraine à plusieurs reprises.\nAu delà des grandes salles encombrées d''éboulis (jusqu''à 45 mètres de hauteur), la dernière partie constituée de diaclases étroites parcourues par la rivière se termine sur une voûte mouillante.\nLe développement total dépasse 20 kilomètres[ref]Les spéléos à Francheville : http://www.mairie-francheville21.fr/index.php?option=com_content&view=article&id=61:les-speleos-a-francheville&catid=18&Itemid=120[/ref].\n\nCavité en partie aquatique mais ne nécessite pas de néoprène, éventuellement une pontonnière. \nUn pont de singe permet de franchir un petit lac.\n\nEn 2006, une nouvelle entrée "Rochotte" a été désobstruée, ouvrant la possibilité de faire une traversée avec 2 équipes (cf Rochotte).\nPour cela, descendre la route sur environ 500 mètres puis prendre à gauche un chemin forestier qu''il faut remonter sur environ 300 mètres.\nL''entrée, entourée d''un grillage, s''ouvre sur la droite. \nPossibilité de faire une traversée avec 2 équipes.\nEnchaînement de deux puits (chatière entre les 2), le 2e arrivant un peu avant la cascade[ref]CDS 21 > Combe aux Prêtres : http://cds21.org/cavites_cotedor/topo/cap.htm[/ref]. ',
		NULL,
		3,
		NULL,
		NULL,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		5,
		4,
		NULL,
		'2010-02-19 22:34:00.000',
		NULL,
		-5,
		'Avertissement important et descriptif général',
		'ATTENTION : Il convient d''être très attentif aux conditions climatiques avant de s''engager dans la cavité.\n\nGalerie du sable - Chapelle : \n\nSuivre la galerie d''entrée jusqu''à un ressaut que l''on descend à l''aide d''une corde. \nAu pied se trouve un plan d''eau.\nPrendre la galerie qui remonte à droite. \nLaisser une galerie qui redescend vers le plan d''eau et rejoindre un carrefour (A). \nPrendre à gauche et franchir 2 passages bas faisant baignoire (le second est équipé d''un tuyau qui permet de vider l''eau vers l''avant de la progression).\nPrendre à droite, passer sur le bord  d''un puits : la galerie devient davantage concrétionnée. \nOn descend un ressaut pour atteindre une diaclase que l''on remonte pour rejoindre les marmites. \nIl est possible de mettre une corde pour assurer le passage (C25 4S). \nAu delà on arrive dans une grande galerie. \nA droite la galerie du sable remonte jusqu''à un puits d''une dizaine de mètres. \nIl faut le contourner par la droite. \nA gauche on atteint rapidement la Chapelle.\n\nLac vert : \n\nAu carrefour (A), il convient de continuer à remonter la galerie qui devient plus étroite.\nA un carrefour suivant, continuer par la galerie toujours étroite qui permet de continuer la progression dans la même direction.  \nOn entend l''eau couler quand l''espace s''élargit. \nArrivé dans une petite salle il faut trouver sous ses pieds la faille qui permet de rejoindre le lac vert. \nLe longer par le côté droit et s''engager dans une faille resserrée que l''on peut suivre jusqu''à une étroiture. \nOn peut choisir, quand une cheminée de quelques mètres s''ouvre dans le plafond, de la remonter et de suivre un itinéraire parallèle plus large et plus propre.. \nFait suite une diaclase qui descend à droite, équipée d''une corde à nœuds. \nUn boyau resserré permet de rejoindre la galerie d''entrée.\n',
		NULL,
		4,
		NULL,
		NULL,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		6,
		6,
		NULL,
		'2008-07-28 20:06:02.000',
		NULL,
		3,
		'Objectif Fond',
		'L''entrée est un joli P34 d''env. 3m de diamètre qui s''équipe à partir de l''arbre. Sa base est encombrée de branchages.\nOn continue sur une escalade de 9m équipée en fixe. La suite est une succession de puits. On ne quitte plus la corde. A la base du P28, le principal obstacle de la cavité (en particulier pour les débutants à l''équipement) la lucarne. Il s''ensuit une agréable coulée stalagmitique suivi du P20 et du P23. Un méandre étroit se termine sur une étroiture.\nUne cavité idéal pour apprendre à équiper.',
		NULL,
		7,
		NULL,
		NULL,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		7,
		6,
		NULL,
		'2008-10-13 15:41:56.000',
		NULL,
		3,
		'DANGER DÛ A LA COMPLEXITE DU RESEAU',
		'Réseau "paumatoire". \nNe pas s''y aventurer sans quelqu''un qui connaît ou une bonne topo, sinon "bonjour la galère"...',
		NULL,
		9,
		NULL,
		NULL,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		8,
		5,
		NULL,
		'2018-11-23 14:17:25.000',
		NULL,
		4,
		'DANGER DES CRUES CEVENOLES (avertissement du CLPA)',
		'ATTENTION DANGER\nNe pas s''introduire dans la cavité en période de précipitations intenses, notamment lors d''un "épisode cévenol". \nMise en charge possible rapide et passage du "Lac" impossible. \n',
		NULL,
		9,
		NULL,
		NULL,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		9,
		5,
		NULL,
		'2019-09-07 17:57:32.000',
		NULL,
		3,
		'LES PUITS DU GL 102',
		'Le premier puits est étroit, à sa base ; penduler vers le nord pour accéder au bon côté de la fissure.\n\nEnsuite, aucun problème d''itinéraire, les puits se succèdent jusqu''à - 370 m.\n\nA la base du dernier puits, un éboulis conduit dans une vaste galerie à la côte -390 m.',
		NULL,
		10,
		NULL,
		NULL,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		10,
		5,
		NULL,
		'2019-09-07 17:58:47.000',
		NULL,
		4,
		'DE LA BASE DES PUITS À L''EMBARCADÈRE',
		'Prendre sur la droite à la base des puits, passer un premier chaos (à gauche) pour arriver dans une salle d''un peu plus de 150 mètres.\n\nAu fond de cette salle se trouve une cascade qu''on descendra en rive droite. \n\nUne fois traversé le Chaos des Titans, on retrouve la rivière, c''est l''Embarcadère.\n',
		NULL,
		10,
		NULL,
		NULL,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		11,
		5,
		NULL,
		'2019-09-07 18:02:13.000',
		NULL,
		3,
		'DE L''EMBARCADÈRE À LA SALLE STYX',
		'Une fois le matériel de progression aquatique enfilé, on le gardera jusqu''au fond. \nOn rentrera dans l''actif sur 200 mètres, puis on sortira de l''eau peu avant le sommet d''un ressaut de 8 mètres qui conduit à une série de vasques. \n\nAprés un grand bassin, on va suivre l''actif sur 500 mètres dans une succession de rapides.\n\nJuste après un bassin de 10 mètres de long qui barre toute la galerie, on trouvera un passage bas, suivi de quelques mètres de galerie qui nous fera déboucher dans le Grand Chaos. \nLong de 300 mètres, son passage clé se trouve au bout de 100 mètres de chaos.\nIl faut descendre sur la droite, progresser entre les blocs et remonter de l''autre cōté, sans essayer de rejoindre la rivière que l''on entend plus bas.\n\nLa deuxième partie du Grand Chaos est plus évidente. \nA la fin, on redescend dans la rivière qu''on suivra pendant une centaine de mètres jusqu''à sa disparition sous une voûte basse ; la suite est sur la gauche. \n\nDans cette galerie, on restera en haut de l''éboulis, 150 mètres plus loin, on peut retrouver l''actif.\nDès lors la progression jusqu''à la Salle Styx ne pose plus de problème.',
		NULL,
		10,
		NULL,
		NULL,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		12,
		1,
		NULL,
		'2010-04-07 13:40:34.000',
		NULL,
		3,
		'Description sommaire',
		'La cavité est décrite de manière détaillée dans de nombreux ouvrages (cf. section "Bibliographie" ci-dessous).\n\nVoir aussi quelques conseils de prudence dans la section "Commentaires" ci-dessous.',
		NULL,
		12,
		NULL,
		NULL,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		13,
		3,
		NULL,
		'2009-10-01 14:12:25.000',
		NULL,
		-6,
		'Description ',
		'Superbe entrée au travers des buis. \nUn lac de 40 mètres constitue, avec la vire qui lui succède, la seule vrai difficulté de ce périple d''initiation. \nFranchir ce plan d''eau de 6 mètres de profondeur en rive droite (c''est à dire à gauche en entrant), pour arriver sur un débarcadère stalagmitique spacieux. \nGrimper 5 mètres à l''aplomb de ce dernier, pour équiper la vire (scellements en place). \nOn prend pied dans une vaste galerie, avec une arrivée d''eau sur le coté, origine de la coulée de calcite que l''on a dû contourner par le haut (alias "La Méduse"). \nOn va progresser dans une galerie remontante, mais soumise à des fluctuations altimétriques du style montagnes russes. \nAprès un premier point bas qui siphonne en crue, la galerie prend ses dimensions effectives qu''elle conservera une bonne partie de son existence. \nUn phare puissant est recommandé, qui permet de découvrir les merveilles de cette galerie, tant en concrétionnement, qu''en formes, en coloris ou en départs. \nNous croisons des cheminées, accès au réseau des Deux Jean et au réseau Inattendu.\nA 800 mètres de l''entrée, on arrive dans la salle des Fontaines, superbe salle concrétionnée, à l''actif très original, puisqu''ayant créé une fontaine symétrique, bordée d''immenses gours. \nUne remontée entre blocs coté gauche permet d''atteindre l''affluent du point 900. \nC''est dans ce secteur, au centre de la galerie qu''il faut trouver le premier accès à la rivière. \nCela peut faire un premier but de ballade (cote +55 environ). compter 1h30 avec un groupe de non spéléo bons marcheurs\nle premier accès bien marqué est expo équipé d''une cordelette pour une corde, ressortir de l''accès, prendre à gauche et passer entre les blocs pour descendre sans avoir besoin de matériel \n\nsuite vers le second accès (salle à manger): Continuer la galerie fossile, et via une vire coté gauche, on passe un portail de concrétions : la "Cascade Rouge". \nSuivent quelques dizaines de mètres de parcours fastidieux, avant de déboucher en balcon à la Salle à Manger, vaste entonnoir dont le fond constitue le deuxième accès à la rivière.\nil faut compter 2 heures pour cette partie avec un groupe de bons marcheurs non spéléo de 8 personnes.\nLa rivière jusqu''à la cascade de 12 mètres (C12) ne présente aucune difficulté et peut se faire sans équipements ; les rares passages athlétiques sont équipés avec des barreaux métalliques, les baudriers sont facultatifs mais bien utiles surtout pour remonter une petite cascade de 4m équipée "via". on notera tout le long du parcours de nombreux fossiles dont des sortes de moules de 20cm de long\nOn arrive en fin à une partie en cul de sac avec une main courrante qui mène à la C12, s''arrêter là (on passe dans la partie nécessitant du matériel de spéléologie (baudrier complet)). il y a un très beau fossile en passant à la nage dans l''actif sur la gauche 3m après la mise à l''eau à environ 1m20 au dessus du niveau de l''eau',
		NULL,
		14,
		NULL,
		NULL,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		14,
		1,
		NULL,
		'2009-10-22 12:04:04.000',
		NULL,
		1,
		'La rivière souterraine le 17-10-2009',
		'Ce descriptif fait abstraction du lac d''entrée et de la grosse galerie (cf. description précédente) pour décrire la rivière.\nL''entrée vers la rivière se fait dans une dépression marquée 2 au carbure (déchaulages et odeurs d''urine).\nLa progression dans la rivière se fait bien grâce à l''équipement avec des super barreaux de via ferrata.\nNous arrivons à une grosse remontée de cascade et, bonne surprise, encore des barreaux et une belle corde en place.\nOn suit toujours la rivière avec ses petits ressauts puis on arrive à une sorte de cul de sac. \nIl faut remonter vers une cascade plus haut.\nC''est le seul passage étroit sur la gauche ; on monte dans un chaos de blocs jusqu''à une belle corde. \nRemontée sur 30 mètres en via corda très fractionnée. \nOn retrouve une grosse cascade (on est content que le débit soit faible). \nEnsuite changement d''ambiance dans une galerie en as de pique un peu boueuse. \nEn sortie, sur la gauche, une grande salle (demi tour). \nNous continuons de remonter sur un équipement plus approximatif.\nRessaut sur échelle spéléo, petits puits sur petites cordes, amarrages fabrication maison. \nOn retrouve vite l''eau et de belles cascades. Redescente d''un P10 et remontée d''un P10 avec sortie sur main courante assez sportive !\nOn passe par des parties très aquatiques pour remonter une cascade (d''un coup je trouve le débit très suffisant).\nLe passage se resserre pour arriver au siphon ; sur le dessus ça continue mais apparemment c''est boueux.\nLe retour ressemble vraiment à un canyon, il y a même un saut de 3 mètres dans une vasque et des descentes dans cascades.\n\nBravo au groupe qui a entrepris de ré-équiper ce magnifique canyon souterrain.\nLa dernière partie pour arriver au siphon est en cours (les broches sont déjà en place) aussi bien ce sera nickel pour l''été 2010.\nCette sortie entièrement équipée nous a permis d''aller jusqu''au siphon à 7 spéléos pour 11 heures sous terre.',
		NULL,
		14,
		NULL,
		NULL,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		15,
		6,
		NULL,
		'2009-04-03 21:34:40.000',
		NULL,
		1,
		'De la nouvelle entrée à la galerie des Meulières.',
		'Un petit parcours entrecoupé de petits puits pas très larges conduit au sommet du P109.  \nAttention de ne pas descendre totalement le 2ème puits mais de s’arrêter 2-3m avant le fond pour s''engager dans un petit méandre. \nAu bas d''une première verticale de 37 mètres contre parois, on atteint une vire d''où part la suite du puits plein vide mais dont on ne descend que 34 mètres. \nPour atteindre le belvédère il faut penduler ou descendre légèrement plus bas puis remonter en escalade.\n\nDu belvédère on descend une vaste galerie qui conduit à -120 m dans une très grande salle qui n''est en fait qu''une section de l''énorme collecteur de la Leicasse.',
		NULL,
		17,
		NULL,
		NULL,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		16,
		1,
		NULL,
		'2009-10-22 11:01:24.000',
		NULL,
		4,
		'Le Petit Fond',
		'Pour le "Petit Fond", il faut remonter sur 10 mètres de corde sur la droite, aprés la salle Edmond Milhau et juste avant la galerie du Tac o Tac. \nNous remplaçons la corde (10-10-2009). \nIl y a du rab pour rééquiper un ressaut de 3 mètres avec corde en place pourrie.\n\nAprés la remontée, on prend une galerie sur la droite puis remontée étroite pour arriver sur le ressaut avec la corde abimée. \nOn suit une galerie assez jolie, galerie entrecoupée de passages rampés puis P8 équipé pour arriver au siphon. \nOn a de la chance il est complétement à sec !\n\nPartie la plus pénible dans un boyaux boueux pour arriver au lac. \nOn passe sur une main courante en place (niveau du lac trés bas), ça s’enchaîne sur une magnifique galerie entrecoupée de gours (un pont de singe est en place mais on passe à sec). \nRemontée sur main courante et remontée de 10 mètres (toutes deux équipées) pour arriver sur un petit lac qui est peut être un siphon pas long à traverser mais profond, nous faisons demi tour. ',
		NULL,
		17,
		NULL,
		NULL,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		17,
		2,
		NULL,
		'2009-12-30 21:51:13.000',
		NULL,
		1,
		'Du bas du Grand Puits à la galerie de la Nuit Blanche par le Shunt des Garrigues',
		'Après le pendule, on accède à un grand palier puis à une descente dans de grand blocs. \nCorde fixe à main droite facilitant la descente sur la coulée. \nEn bas, ne pas s''engager dans le passage marqué de flèches noires mais rester en hauteur pour rejoindre plus tard le fond de la galerie et les dunes sableuses.\n\nApres un passage bas, la galerie se divise en deux (trois départs à main droite, à gauche on tombe sur de multiples spits trace d''un bivouac et départ d''un autre cheminement alternatif vers la galerie de la nuit blanche).\nEmprunter le premier passage à droite, cela donne accès à un belle galerie richement concrétionnée. \nAu fond remonter l''éboulis. \nLa suite se trouve par un passage désobstrué au sein de l''éboulis (rubalise derrière un gros bloc). s''insinuer entre les blocs en suivant les marques. \n\nOn débouche de nouveau dans une grosse galerie après un ressaut remontant (corde à noeuds en fixe). \nSuivre les balisages, cairns et remonter entre de gros blocs. \nEnfin, une désescalade argileuse donne sur un ressaut contre une coulée (corde fixe +/- 10m). \nOn débouche en hauteur d''un grand éboulis à la fin des tubes de la galerie de la nuit blanche.(arrivée de la galerie des meulières dans le descriptif de Nathan). \n\nVers la droite, la galerie d''effondrement, de belle section, conduit vers la salle Edmond Milhau. \nA/R au Tac O Tac en 1/2 heure en galopant. \nPour le reste du parcours voir les descriptions de Nathan.',
		NULL,
		17,
		NULL,
		NULL,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		18,
		4,
		NULL,
		'2014-11-02 20:03:43.000',
		NULL,
		3,
		'Des Meulières à la galerie de la Nuit Blanche par l''ancien cheminement',
		'Après le pendule, on accède à un grand palier puis à une descente dans de grand blocs, après une corde en fixe sur la droite de la galerie qui permet de descendre un toboggan de calcite il faut descendre entre les blocs en suivant 2 flèches noir. \n\nUne série d''étroitures élargies permet d''accéder au sommet d''un P12. \nOn suit un méandre entrecoupé d''un R3 malaisé (étrier en place) pour accéder à "l''étroiture du pilier". \n\nSuivent une petite vire et un P8 qui ne doit pas être totalement descendu. \nUn passage étroit remontant entre des blocs sur la droite conduit à un P12. \nAu bas de ce dernier, on recoupe un méandre de type alpin parcouru par un ruisselet. \nP10 et un magnifique P35 permettent d''atteindre les galeries de la Nuit Blanche vers -200.',
		NULL,
		17,
		NULL,
		NULL,
		NULL,
		NULL,
		'fra',
		false
	),
 	(
		19,
		4,
		NULL,
		'2014-11-02 20:04:43.000',
		NULL,
		4,
		'Du début des galeries de la Nuit Blanche à la galerie du Tac O Tac.',
		'Départ depuis l''arrivée de l''ancien cheminement.\nParcours sans aucune difficulté long d''environ 1,2 km. \n\nAu bout des galeries en tube on remonte un énorme éboulis dans une grande salle où l''on retrouve la suite de la galerie des Meulières délaissée précédemment. \nPrendre sur la gauche. \nOn passe près d''un bidon qui sert de point d''eau et d''une tente vestige de bivouacs souterrains. \nOn débouche peu à peu dans la très spectaculaire salle Edmond MILHAU (ancien berger  local). \nLa galerie monumentale se poursuit en se réduisant peu à peu jusqu''à buter sur un énorme colmatage alluvionnaire.\n\nUne désobstruction spectaculaire (galerie du Tac O Tac = une chance au grattage, une chance au tirage) a permis de creuser un tranchée digne des catacombes sur plus de 100 m. \nChacun est invité à ressortir un bidon de sable lors de sa visite pour faire avancer le chantier...',
		NULL,
		17,
		NULL,
		NULL,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		22,
		4,
		NULL,
		'2014-11-02 20:14:09.000',
		NULL,
		4,
		'Du bas du Grand Puits à la galerie de la Nuit Blanche par le Schunt de la Géode',
		'Après le pendule, on accède à un grand palier puis une descente dans de grand blocs. \nCorde fixe à main droite facilitant la descente sur la coulée. \nEn bas, ne pas s''engager dans le passage marqué de flèches noires mais rester en hauteur pour rejoindre plus tard le fond de la galerie et les dunes sableuses. \nAprès un passage bas, la galerie se divise en deux : laisser l''ancien camp à gauche et prendre la galerie a droite. \nLe départ étroit du Shunt de la Géode est sur la gauche entre de gros blocs. \n2 spits sont visibles au dessus de ces blocs. \n\nAprès un passage entre des blocs et une corde en fixe de 6 mètres on arrive à la Géode. \nLa suite jusqu''à la galerie de la Nuit Blanche est à écrire (...)',
		NULL,
		17,
		NULL,
		NULL,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		23,
		4,
		NULL,
		'2016-10-12 23:42:42.000',
		NULL,
		2,
		'Description sommaire',
		'Le puits principal est une verticale de 100 mètres, au bas de laquelle coule la Sorgue souterraine. \nLa rivière peut être suivie sur quelques dizaines de mètres en amont et en aval. \nOn peut aussi descendre par des puits parallèles brochés (P21, R5, P12, R6, P9, P33) qui donnent par des balcons une belle vue sur l''ambiance du grand puits. \nOn peut, si l''on constitue 2 équipes, descendre par les petits puits et remonter par le P100 ou vice versa. \nPrévoir dans ce cas le matériel pour équiper les puits parallèles.',
		NULL,
		18,
		NULL,
		NULL,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		24,
		4,
		NULL,
		'2015-04-09 16:21:07.000',
		NULL,
		3,
		'Traversée TQS -> Saints de Glace',
		'La traversée TQS -> Saints de glace est bien marqué avec des flèches sur support réfléchissant.\nLe méandre francois peut etre descendu en rappel. Les mains courantes sont en place.\nDescendre les puits de l''entrée de TQS puits sortir de l''actif par la droite pour s''engager dans une zone étroite et boueuse avant d''arriver au méandre francois que l''on parcoure au plafond sur des vires.\nAprès le méandre Francois on arrive dans la Salle de la Conciergerie. On empreinte ensuite de belles galeries avec des marmites jusqu''à la salle Hydrokarst. De la salle Hydrokarst on récupère le méandre des Saints de Glace pour sortir.',
		NULL,
		21,
		20,
		NULL,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		25,
		5,
		NULL,
		'2015-04-09 16:21:07.000',
		NULL,
		3,
		'Title 6068',
		'Description 6068',
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		6068,
		'fra',
		false
	),
	(
		26,
		5,
		NULL,
		'2015-04-09 16:21:07.000',
		NULL,
		3,
		'Title 1409',
		'Description 1409',
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		1409,
		'fra',
		false
	),
	(
		27,
		5,
		NULL,
		'2015-04-09 16:21:07.000',
		NULL,
		3,
		'Title 2542',
		'Description 2542',
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		2542,
		'fra',
		false
	),
	(
		28,
		5,
		NULL,
		'2015-04-09 16:21:07.000',
		NULL,
		3,
		'Title 2998',
		'Description 2998',
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		2998,
		'fra',
		false
	),
	(
		29,
		5,
		NULL,
		'2015-04-09 16:21:07.000',
		NULL,
		3,
		'Title 6065',
		'Description 6065',
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		6065,
		'fra',
		false
	),
	(
		30,
		5,
		NULL,
		'2015-04-09 16:21:07.000',
		NULL,
		3,
		'Title 6096',
		'Description 6096',
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		6096,
		'fra',
		false
	),
	(
		31,
		5,
		NULL,
		'2015-04-09 16:21:07.000',
		NULL,
		3,
		'Title 10406',
		'Description 10406',
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		10406,
		'fra',
		false
	),
	(
		32,
		5,
		NULL,
		'2015-04-09 16:21:07.000',
		NULL,
		3,
		'Title 12639',
		'Description 12639',
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		12639,
		'fra',
		false
	),
	(
		33,
		5,
		NULL,
		'2015-04-09 16:21:07.000',
		NULL,
		3,
		'Title 109',
		'Description 109',
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		109,
		'fra',
		false
	),
	(
		34,
		5,
		NULL,
		'2015-04-09 16:21:07.000',
		NULL,
		3,
		'Title 5801',
		'Description 5801',
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		5801,
		'fra',
		false
	),
	(
		35,
		5,
		NULL,
		'2015-04-09 16:21:07.000',
		NULL,
		3,
		'Title 191',
		'Description 191',
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		191,
		'fra',
		false
	),
	(
		36,
		5,
		NULL,
		'2015-04-09 16:21:07.000',
		NULL,
		3,
		'Title 16746',
		'Description 16746',
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		16746,
		'fra',
		false
	),
	(
		37,
		5,
		NULL,
		'2015-04-09 16:21:07.000',
		NULL,
		3,
		'Title 161',
		'Description 161',
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		161,
		'fra',
		false
	),
	(
		38,
		5,
		NULL,
		'2015-04-09 16:21:07.000',
		NULL,
		3,
		'Title 1378',
		'Description 1378',
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		1378,
		'fra',
		false
	),
	(
		39,
		5,
		NULL,
		'2015-04-09 16:21:07.000',
		NULL,
		3,
		'Title 2591',
		'Description 2591',
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		2591,
		'fra',
		false
	),
	(
		40,
		5,
		NULL,
		'2015-04-09 16:21:07.000',
		NULL,
		3,
		'Title 12106',
		'Description 12106',
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		12106,
		'fra',
		false
	);
