\c grottoce;

INSERT INTO public.t_location (
		id,
		id_author,
		id_reviewer,
		date_inscription,
		date_reviewed,
		relevance,
		title,
		body,
		id_entrance,
		id_language,
		is_deleted
	)
VALUES (
		305,
		5,
		NULL,
		'2009-09-02 16:53:33.000',
		NULL,
		4,
		'Accès piste',
		'Piste normalement fermée par une barrière.',
		5,
		'fra',
		false
	),
	(
		1,
		6,
		NULL,
		'2008-07-28 19:35:20.000',
		NULL,
		3,
		'Accès',
		'A partir de Neuville/Ain, prendre la D42 en direction de Meyriat et Hautecourt. Environ 1 km apres Fromente prendre à droite sur la D59 en direction de Hautecourt.  Après la deuxième intersection D81 (Bohas-Meyrat) - D59 (Hautecourt) continuer sur la droite et se garer 200m plus loin en bordure gauche. Sur notre droite prendre un chemin en terre (le premier depuis le croisement). Pour éviter tout problème avec le propriétaire, il est préférable de se garer avant de prendre le chemin en terre.\nAu bout de 200 m cette piste finit de longer les champs et tourne a gauche pour pénétrer dans le bois. La prendre. Apres encore 200 m un chemin part a droite vers une clairiere/coupe de bois. Juste apres la piste se transforme tout droit en chemin plus etroit : prendre alors la piste a droite, puis au bout de 200 m prendre la piste de gauche. 40m après prendre à gauche vers la clairiere. 25m plus loin le gouffre s''ouvre sur votre gauche en bord de clairiere. Il est entouré d''un grillage et un panneau en indique l''entrée.\nAttention, la forêt est un vrai labyrinthe de buis.',
		7,
		'fra',
		false
	),
	(
		2,
		6,
		NULL,
		'2008-07-29 18:32:18.000',
		NULL,
		1,
		'Coordonnées',
		'Coordonnées Lambert II Centre (km) : X= 943,37 Y= 132,12 Z=1840 (entrée V4)[ref]"Gouffre Jean-Bernard", sur le site du GS Vulcain : https://www.groupe-speleo-vulcain.com/explorations/explorations-a-samoens/gouffre-jean-bernard/[/ref].\nATTENTION : Ces coordonnées Lambert II Centre ne sont pas tout à fait équivalentes aux coordonnées WGS84 décimales, pourtant également fournies par un document du GS Vulcain[ref]Synthèse topographique 2010 : https://www.groupe-speleo-vulcain.com/wp-content/uploads/2011/03/JB-Coupe1991.pdf[/ref].\n\nA partir de Samoëns, aller se garer sur le parking qui permet d''accéder au Lac des Chambres et au refuge du Folly.\nMonter au refuge ; il faut compter 1h30 de marche (600 mètres de dénivelé). \nA partir du refuge, prendre la direction du lac des Chambres. \nUn peu avant le lac, prendre sur la gauche. \nL''entrée V4 est un petit porche. \nCompter 1h30 de marche entre le refuge et l''entrée.',
		1,
		'fra',
		false
	),
	(
		7,
		1,
		NULL,
		'2008-08-02 21:34:30.000',
		NULL,
		0,
		'Consignes locales',
		'Pour toute info sur cette cavité vous pouvez contactez le club spéléo CLPA : contact.clpa-chez-laposte.net \nLa cavité est d''accès libre. \nPrière de respecter les équipements en place et signaler au CLPA les matériels défectueux constatés. \n\nL''entrée décrite par la présente fiche concerne le trop-plein temporaire pénétrable situé en tête de talweg et exhalant un trés fort courant d''air.\nCe trop-plein est situé au-dessus de la source pérenne importante appelée "Foux de Saint Jean" ou "Foux des Sicards".\n\nLes coordonnées suivantes ont été également signalées pour l''émergence pérenne de la "Foux de Saint-Jean" alias "Foux des Sicards3 : \nLatitude    : 43.8341 degrés N.\nLongitude : 3.61652 degrés E.',
		9,
		'fra',
		false
	),
	(
		8,
		4,
		NULL,
		'2008-08-04 16:58:07.000',
		NULL,
		2,
		NULL,
		'A partir de Francheville prendre le D103 en direction de Vernot. \n1,5 Km après la sortie du village, se garer à gauche dans une ancienne carrière. \nL’entrée du gouffre se trouve dans le front de taille de la carrière.[ref]Les spéléos à Francheville : http://www.mairie-francheville21.fr/index.php?option=com_content&view=article&id=61:les-speleos-a-francheville&catid=18&Itemid=120[/ref]\n\nIl est possible de dormir dans un ancien lavoir à proximité. ou au gite de "la clairière" à 20 minutes à pied de Francheville\n\nTopographie et source : http://cds21.org/cavites_cotedor/topo/cap.htm',
		3,
		'fra',
		false
	),
	(
		157,
		6,
		NULL,
		'2009-03-29 14:22:00.000',
		NULL,
		2,
		'Accès',
		'Les coordonnées GPS de Grottocenter ont été validées le 1er novembre 2014.\n\nDu hameau du Coulet, emprunter la piste qui conduit au ruines du Mas de Larret. \nAu bout de 600 mètres, tourner à gauche. \nAu bout de 1,5 km de piste en état moyen (voiture surélevée conseillée), se garer sur un replat à droite de la piste (coordonnées du parking N43.81996 E003.55991). \nDe là, un petit sentier mène à l''entrée de l''aven distant d''environ 150 mètres.\nL''entrée est maçonnée et la porte n''existe plus.\n\nExplorations interdites en périodes de chasse.\n\nPendant la période "tolérée" le propriétaire (Mr Buresi) demande à ce qu''un seul véhicule soit garé à proximité du trou (cf. supra). \nLes autres doivent être garés au bord de la route juste à la sortie du Coulet (aire de parking herbeuse à droite).',
		17,
		'fra',
		false
	),
	(
		228,
		5,
		NULL,
		'2009-08-18 21:13:15.000',
		NULL,
		4,
		'Sentier',
		'Le sentier qui descend à la gortte se situe dans l''épongle de la route. Il faut descendre d''une 20aine de mètres.',
		6,
		'fra',
		false
	),
	(
		216,
		3,
		NULL,
		'2009-08-16 11:56:27.000',
		NULL,
		4,
		'Accès',
		'A la sortie du village, au bord de la route qui mène à Lagarde d’Apt, l’ancienne entrée dangereuse de l’aven est surmontée d’une grande chèvre métallique. \nLa nouvelle entrée a été forée en 2015 et est situé à une dizaine de mètres de la chèvre sous une bouche d''égout.\n\nNe pas se garer proche des habitations mais plutot directement sur la pelouse sur le terrain de l''entrée du Souffleur.',
		12,
		'fra',
		false
	),
	(
		295,
		5,
		NULL,
		'2009-08-28 19:36:30.000',
		NULL,
		4,
		'Note accès',
		'Grotte touristique, fléchèe dans le village.',
		13,
		'fra',
		false
	),
	(
		323,
		3,
		NULL,
		'2009-10-01 14:14:05.000',
		NULL,
		3,
		NULL,
		'Depuis la grotte touristique (grottes de Choranche), continuer le chemin en pied de falaise.\nSuivre le ruisseau en remontant, jusqu''au porche.',
		14,
		'fra',
		false
	),
	(
		384,
		1,
		NULL,
		'2009-12-30 21:31:52.000',
		NULL,
		3,
		'Accès alternatif',
		'Accés alternatif "par le haut", nettement plus long mais plus praticable.\nL''accés classique par "le bas" est praticable en dec 2010. \n\nDu coulet prendre la piste à l''est (GR) suivre le GR sur 1km et laisser à main gauche le départ du chemin d''accés par le bas. \nRapidement il y a un nouvel embranchement, suivre toujours le GR = aller à gauche cette fois. le chemin monte puis marque une épingle (2,7 km depuis le coulet). \nPrendre le chemin en face dans l''épingle et quitter le GR. \nCe chemin est barré par une clôture juste aprés ; ne pas oublier de refermer derrière soi. \nLa piste suit longuement une clôture à flanc de colline, sous le Serre des Pins, arrive à un replat et redescend plus nettement après un virage à gauche. \nLa piste change alors de versant en contournant un puech et descend toujours. \nAprès une épingle à cheveux à droite, le parking de l''aven se situe sur un replat entre deux puech (point coté 625 sur l''IGN)\nAccés à l''entrée de la grotte en descendant dans le petit talweg.\n\nATTENTION\nLa boucle "accés haut" - "accés bas" est parfaitement visible sur la vue satellite. \nLes chemins sont sur la carte IGN 1/25000.',
		17,
		'fra',
		false
	),
	(
		480,
		4,
		NULL,
		'2010-02-19 17:07:25.000',
		NULL,
		4,
		'Accès',
		'De la D911, quelques kilomètres au nord du pont de Lescheraines, il suffit de prendre la petite route qui descend vers le Chéran et vers l''entrée de la grotte. \nIl est possible de garer 4 à 5 voitures avant le pont, sur la droite.',
		4,
		'fra',
		false
	),
	(
		834,
		2,
		NULL,
		'2013-08-19 21:15:51.000',
		NULL,
		3,
		'Accès',
		'De Millau, prendre l''autoroute A75 vers Montpellier. \nA 30 kilomètres prendre la sortie 48 direction Cornus, Alzon ; puis au rond point prendre la direction des Infruts, La Pezade. \nTraverser la Pezade puis prendre la D 140 à droite vers Mas Raynal. \nOn laisse ce village sur la droite puis on continue la route sur 1 kilomètre et on emprunte alors un chemin à gauche (panneau indicateur : Abîme du Mas Raynal). \nLe chemin mène à moins de 100 mètres de la grande entrée (40 m x 20 m) située sur la gauche du parking.',
		18,
		'fra',
		false
	),
	(
		2360,
		1,
		NULL,
		'2014-08-02 21:25:44.000',
		NULL,
		3,
		'Note et accès',
		'Le digramme "CP" fait référence à la zone de la Combe aux Puaires.\n\nLe CP16 est situé à une trentaine de mètres à l’est du CP14, en contrebas de la falaise du CP15. \nLe gouffre s’ouvre à la faveur de la grande faille qui traverse l’ensemble des lapiaz de la Tête à l''Homme.',
		2,
		'fra',
		false
	),
	(
		2699,
		4,
		NULL,
		'2015-04-09 16:23:08.000',
		NULL,
		4,
		'Accès',
		'Au bord de la route sur la gauche en montant derrière une barrière bleu.',
		20,
		'fra',
		false
	),
	(
		5207,
		5,
		NULL,
		'2019-09-07 17:17:09.000',
		NULL,
		0,
		NULL,
		'Avant d''arriver à la station de ski, prendre à droite la route de l''espagne, passer devant l''ancien chalet des douanes et continuer vers le col de la PSM. \nOn aperçevra sur la droite une bergerie à 50 mètres de la route, au niveau du départ du télésiège des contrebandiers. \nOn pourra garer les véhicules en bordure de route (demander aux bergers).\n\nPrendre ensuite le sentier qui passe devant la bergerie et se diriger vers la dépression herbeuse de Caque. \nPrendre un petit sentier (peu marqué) sur la droite pendant 50 mètres (ne pas aller jusqu''au sommet du lapiaz) puis se diriger vers la gauche, dans le lapiaz, sur 100 mètres. \nUn sentier discret mène au GL 102[ref]* Fiche cavité du CDS 64 : http://cds64.org/WordPress3/wp-content/uploads/2017/07/GL_102.pdf[/ref].',
		10,
		'fra',
		false
	);

INSERT INTO public.t_file (
		id,
		date_inscription,
		date_reviewed,
		filename,
		id_file_format,
		id_document,
		path,
		is_validated
	)
VALUES (
		1629,
		'2020-12-22 00:13:44.771',
		NULL,
		'photo-lac-gournier.jpg',
		871,
		16746,
		'u427-t1579-r5275a16b5129b338f0339d5727010c0e-photo-lac-gournier.JPG',
		true
	);

INSERT INTO public.t_rigging (
		id,
		id_author,
		id_reviewer,
		date_inscription,
		date_reviewed,
		relevance,
		title,
		obstacles,
		ropes,
		anchors,
		observations,
		id_entrance,
		id_exit,
		id_point,
		id_language,
		is_deleted
	)
VALUES (
		20,
		1,
		NULL,
		'2009-03-29 11:48:00.000',
		NULL,
		2,
		'Réseau du Petit Fond',
		'Escalade',
		NULL,
		NULL,
		'En fixe',
		17,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		17,
		1,
		NULL,
		'2009-03-29 11:40:40.000',
		NULL,
		2,
		'Accès par l''ancienne entrée',
		'R7\nR2|;|R5',
		'16 m|;|10 m',
		'AN + 1S|;|AN',
		'Etroiture|;|',
		17,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		18,
		6,
		NULL,
		'2009-03-29 11:45:39.000',
		NULL,
		2,
		'Des Meulières aux galeries de la Nuit Blanche par l''ancien réseau de puits',
		'R3|;|R8|;|P12|;|P10|;|P35',
		'|;|10 m|;|20 m|;|16 m|;|50 m',
		'|;|AN|;|3S + 1DEV|;|2S + 1S|;|2S (MC) + 2S + 1S (MC) + 2S',
		'Etrier en place|;|Quitter avant le fond sur la gauche.|;||;||;|Equiper le méandre en MC au plafond.',
		17,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		19,
		6,
		NULL,
		'2009-03-29 11:47:14.000',
		NULL,
		2,
		'Des Meulières aux galeries de la Nuit Blanche par le nouveau réseau de puits',
		'R5|;|Vire|;|Puits',
		'Echelle rigide 6 m|;||;|',
		'|;||;|',
		'En fixe|;||;|',
		17,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		1,
		4,
		NULL,
		'2008-08-04 17:01:02.000',
		NULL,
		4,
		'',
		'La Vire, le R3 de la Galerie des Gours et le R4 du Réseau Ben|;|P10|;|MC|;|P20|;|Trémie Galerie Nord MC + P7',
		'Equipés en fixe|;|C65|;|Même corde|;|Même corde|;|C38 (facultatif)',
		'Equipés en fixe|;|AN (barrière) + 2Br + 2Br|;|2Br + 1Br + 1Br + 1Br + 1Br + 1Br + 2Br|;|2Br + 2Br + 2Br\n|;|6 x (1Br + 1S)',
		'A chaque visite il est important de vérifier l’état des cordes et amarrages. |;|Les 2 premières broches sous le porche font passer la corde très près d''un becquet, préférer 2 Spits disponible à coté\nPossibilité d''équiper le P10 fractionné en double avec une corde de 15m (prévoir 2S + 2B)|;|Il est préférable d''accéder au P20 final après la lucarne de la main courante plutot qu''avant|;|Possibilité d''équiper en double le dernier P20 direct avec une corde de 22m (prévoir 2S +2S)|;|La trémie peut se désescalader mais il est préférable de l''équiper en MC pour des débutants ou des personnes mal chaussées)',
		3,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		2,
		2,
		NULL,
		'2019-06-21 21:32:51.000',
		NULL,
		4,
		'',
		NULL,
		NULL,
		NULL,
		NULL,
		4,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		3,
		6,
		NULL,
		'2008-07-28 20:00:34.000',
		NULL,
		4,
		'Objectif Fond',
		'P34|;|E9|;|P28|;|Lucarne\nR10\nR6|;|P20 \nP23|;|Total',
		'C40|;|C15|;|C25|;|C25|;|C65|;|185m',
		'AN (arbre)|;|2S|;|3S +1S à-9m et 1S à -15m\n|;|CP + 2S - MC\n1S + 1S à -1m\n1S|;|CP+2S +1S + 1S + 1S à -10m\n1S + 1S à -1m|;|19 plaquettes',
		'|;|équipement en fixe|;|Certains spits sont doublés par des goujons de 12 mm|;|2S avant la lucarne. bien s''engager pour équiper proprement\nCertains spits sont doublés par des goujons de 12 mm|;|Certains spits sont doublés par des goujons de 12 mm|;|A partir de l''escalade, toutes les cordes peuvent être reliées.\nAttention, quelques spits sont à ménager',
		7,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		4,
		6,
		NULL,
		'2008-10-13 15:38:08.000',
		NULL,
		4,
		'De l''entrée au Carrefour',
		'P10 coulée|;|V10 lac|;|R3 blocs|;|R4 laminoir|;|E5 début galeries du Minautore|;|V10 |;|P10 salle à manger|;|V10 siphon salle à manger',
		'20 m ou échelle|;|Câble|;|7 m|;|7 m|;|10 m|;|15 m|;|15 m ou échelle|;|20 m',
		'Nat|;|3 spits|;|Nat|;|Nat|;|Nat|;|Nat + 1 spit|;|Nat + 1 spit|;|3 spits',
		'Parfois en fixe|;|En fixe|;|En fixe|;|En fixe|;|En fixe|;|En fixe|;|En fixe|;|En fixe',
		9,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		5,
		6,
		NULL,
		'2009-01-20 21:27:57.000',
		NULL,
		2,
		'Du Carrefour au siphon des Pas Perdus',
		'E8|;|E3|;|P5 galerie latérale siphon suspendu PP aval|;|P3|;|E13 siphon suspendu PP amont|;|E6',
		'15m|;|5 m|;|6 m|;|5 m + échelle de corde|;|20m|;|10 m',
		'Nat + 1Spit|;|1Spit|;|1Spit|;|2 Spits|;|3 Spits|;|1Spit',
		'En fixe|;|En fixe|;|En fixe|;|En fixe|;|En fixe|;|En fixe :\nPuits / Cheminée de jonction avec la salle des Pas Perdus',
		9,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		6,
		6,
		NULL,
		'2009-01-20 21:37:36.000',
		NULL,
		2,
		'Le Réseau Supérieur (P100 / salle du Miroir / cheminée de l''Ours)',
		'E10|;|P"100"|;|Vire salle du Miroir|;|P14 accès siphon suspendu du Réseau Supérieur|;|E5 accès siphon suspendu du Réseau Supérieur|;|Vire siphon suspendu du Réseau Supérieur|;|E8 accès cheminée de l''Ours|;|Vire 10 m|;|E80|;|P7 accès puits "CNS"|;|P18 + P28 (puits "CNS")|;|P15 + P8 accès puits parallèles et puits de la Queue de Dragon|;|P15|;|R8 + R4 + R3|;|P6|;|Puits de la Queue de Dragon|;|',
		'15 m|;|60 m\n80 m|;|2x10 m|;|20 m|;|15 m|;|10 m|;|Echelle de corde 10 m|;|Corde15 m|;||;|15 m|;|80 m|;|20 m + 15 m|;|20 m|;||;|10 m|;||;|',
		'2 Spits|;|Spits|;|Spits|;|2 Spits|;|3 Spits|;|4 spits|;||;|5 spits|;|AN + Spits|;||;|AN + Spits|;||;||;||;||;|AN + Spits|;|',
		'En fixe|;|En fixe|;|En fixe|;|En fixe|;|En fixe|;|En fixe|;|En fixe|;|En fixe|;|En fixe jusqu''à +130|;||;||;||;||;||;||;||;|',
		9,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		7,
		1,
		NULL,
		'2009-01-20 21:39:47.000',
		NULL,
		2,
		'Du Carrefour à la salle du Belvédère et des Niphargus',
		'E3 + vire|;|Vire|;|E20|;|Vire|;|P15 salle des Niphargus|;||;|',
		'10 m + Echelle rigide|;|Câble 15 m|;|30 m|;|15 m|;|25 m|;||;|',
		'2 Spits|;|Nat + Spits|;|Nat + Spits|;||;|Nat + Spits|;||;|',
		'En fixe|;|En fixe|;|En fixe|;|En fixe|;|A équiper !|;||;|',
		9,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		8,
		1,
		NULL,
		'2009-01-20 21:42:13.000',
		NULL,
		2,
		'De la salle du Belvédère à l''étroiture Madonna',
		'P10|;|P5|;|E5|;|E15 réseau du Traître',
		'15 m|;|10 m|;|10 m|;|',
		'|;||;||;|',
		'En fixe|;|En fixe|;|En fixe|;|',
		9,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		9,
		1,
		NULL,
		'2009-01-20 21:46:08.000',
		NULL,
		2,
		'Cheminée des Niphargus',
		'P10|;|E20|;|E41|;|E100|;|Tb du "Dôme"|;|Tb15',
		'20 m|;|30 m|;|50 m|;||;|20 m|;|20 m',
		'Spits|;|Spits|;|Spits|;|Spits|;|2 Spits|;|2 AN',
		'En fixe|;|En fixe|;|En fixe|;|En fixe|;|En fixe|;|En fixe',
		9,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		10,
		1,
		NULL,
		'2009-01-20 21:57:57.000',
		NULL,
		2,
		'Cheminée du Phallus',
		'E 150',
		NULL,
		'AN + spits',
		'30 premiers mètres déséquipés',
		9,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		11,
		1,
		NULL,
		'2009-01-20 22:00:46.000',
		NULL,
		2,
		'Réseau du Labyrinthe',
		'E8',
		'10 m',
		NULL,
		'En fixe',
		9,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		12,
		5,
		NULL,
		'2019-09-07 17:54:36.000',
		NULL,
		4,
		'Equipement d''après le CDS 64',
		'P34\n|;|P50-P5-P13 : \n|;|R5-P20 \n|;|P14-P19: \n|;|P14\n|;|P16 + P 17\n|;|R5\n|;|P54\n|;|P47\n|;|MC\n|;|MC\n|;|R dans blocs|;|Cascade 8m\n|;|R3\n|;|MC10\n|;|P12\n|;|P6\n|;|R3\n|;|R entre blocs\n|;|R8 : \n|;|R6 des rapides',
		'C47|;|C100|;|C43|;|C55|;|C25|;|C50|;|C8|;|C70|;|C60|;| C10|;|C10|;|C12|;|C25|;|C5 |;|C15|;|C19 |;|C10 |;|C5 |;|C5|;|C18 |;|C15',
		'5 broches|;|11 broches + 1 AN|;|8 broches|;|8 broches|;|4 broches|;|11 broches + 1 dev/broche|;|2 broches|;|5 broches|;|7 broches|;|en fixe|;|en fixe|;|en fixe|;|5 broches|;|en fixe|;|en fixe|;|en fixe|;|en fixe|;|en fixe|;|en fixe|;|en fixe 5 broches|;|',
		'|;||;||;||;||;||;||;||;||;||;||;||;||;||;||;||;||;||;||;|Embarcadère|;|',
		10,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		13,
		1,
		NULL,
		'2009-11-06 17:58:24.000',
		NULL,
		4,
		'Fiche d''équipement hors crues (PP - AREHPA 2005)',
		'Forage + ressaut|;|P5|;|P10|;|P36|;|P48|;|P42|;|P28|;|P4|;|Méandre d''ankou|;|P70 (Puits Ayme)|;|P80 (Puits de l''Astrolabe)|;|R80 (Série de puits)|;|P114',
		'25 m|;|15 m|;|20 m|;|80 m|;|80 m|;|70 m|;|50 m|;|10 m|;||;|100 m|;|30 m + 100 m|;|60 m + 60 m|;|200 m',
		'Prévoir de la dyneema pour le départ de puits\n2S + 2S|;|2S + 2S à -5|;|4S|;|20S + 1AN + 1DEV|;|16S|;|14S|;|8S|;|1AN + 3S|;||;|16S + 1AN|;|20S|;|20S + 1DEV|;|24S + 1DEV',
		'Ne pas utiliser l''ancienne entrée (sous la chèvre) qui est dangereuse !|;||;||;||;||;||;|Arrivée à -200|;||;|Bien rester en haut du méandre ! Le bas du méandre est très étroit et se termine sur un puits sans issue.|;||;|Rabouter dans la corde précédente. Prévoir des déviations si nécessaire|;|Prévoir une C40 en plus au cas où. Prévoir des déviations si nécessaire|;|Arrivée dans la rivière',
		12,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		14,
		5,
		NULL,
		'2009-08-28 19:36:53.000',
		NULL,
		4,
		'Equipé en fixe.',
		NULL,
		NULL,
		NULL,
		NULL,
		13,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		15,
		1,
		NULL,
		'2010-06-10 13:30:00.000',
		NULL,
		4,
		'Equipement jusqu''à la cascade de 12 mètres (alias ',
		'Lac d''entrée|;|Vire au dessus du lac d''entrée|;|Cascade de 12 mètres',
		'40m de filin flottant si va et vient |;|C50 m|;|C30 m',
		'|;|monter de 5m, 2broches, partir sur la vire à droite 1broche, 1 broche, 1broche (maillon rapide à demeure, rouillé), 1 as sur concrétion, 1 an sur concrétion derrière une colone,2 broches, 1 broche, 1 broche|;|Broches',
		'|;|l''escalade de 5m depuis le lac est équipée de barreaux, la fin n''est pas sécurisable pour le premier à monter |;|Corde nécessaire pour le rappel de la cascade',
		14,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		16,
		1,
		NULL,
		'2009-03-29 11:39:17.000',
		NULL,
		4,
		'Nouvelle entrée aux galeries des Meulières',
		'P10 d''entrée|;|P6|;|R6|;|R10|;|P37|;|P35|;|TB10',
		'20 m\n(ou 40m pour faire les 2 puits)|;|12 m|;|12 m|;|15 m|;|95 m\n\n|;|Même corde|;|Corde 15 m',
		'1AN (arbre)\n2S\n2S vers -4 |;|AN\nou bien : 2S et dev sur amarge foré. 1S puis nat dans le meandre|;|AN + 1S|;|2S|;|2S\nMC\n2 Broches|;|2 Broches\nMC\n2 Broches\n2S ou AN pour accrocher le bout de corde au belvédère|;|',
		'Beaucoup d''araignées|;|ne pas descendre tout le puits. S''arréter 3m avant le fond pour prendre un méandre.|;|Départ étroit|;|Départ étroit|;|Contre parois jusqu''au palier intermédiaire|;|prévoir 1 mouskif supplémentaire pour éviter un frottement.\nA mi-hauteur penduler pour atteindre le belvédère.|;|En fixe à droite de la galerie.\n = Corde fixe en decembre 2010\nplein frottement à surveiller...',
		17,
		NULL,
		NULL,
		'fra',
		false
	);
INSERT INTO public.t_rigging (
		id,
		id_author,
		id_reviewer,
		date_inscription,
		date_reviewed,
		relevance,
		title,
		obstacles,
		ropes,
		anchors,
		observations,
		id_entrance,
		id_exit,
		id_point,
		id_language,
		is_deleted
	)
VALUES (
		21,
		1,
		NULL,
		'2009-04-03 22:20:28.000',
		NULL,
		2,
		'Réseau du Grand Fond',
		'V10|;|P23 (facultatif)|;|R45|;|P13|;|P5|;|P8|;|P6|;|P7|;|P8|;|P5|;|P11|;|P19',
		'|;|30 m|;||;||;||;||;||;||;||;||;||;|',
		'|;||;||;||;||;||;||;||;||;||;||;|',
		'En fixe?|;||;|Désescalade délicate|;||;||;||;||;||;||;||;||;|',
		17,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		22,
		1,
		NULL,
		'2009-12-30 22:06:51.000',
		NULL,
		4,
		'de la nouvelle entrée à la galerie de la nuit blanche',
		'P entrée P12?|;|2eme puits P8?|;|R3 ou 4|;|P8 (?)|;|"P100"\nne se descend pas en totalité|;|toboggan|;|R8 (?)',
		'C40|;|corde précédente|;| C6 (?)|;|C10 ou 15|;|C87|;|C25??|;|C15 (?)',
		'4 spits|;|2 spits + 1 AN + 2 spits ou 2 AN en bas|;|1 AN |;|2 spits + 2 spits |;|2 spits + AN en hauteur + 2 broches + 2 broches au pallier|;|2 spits|;|1 AN',
		'C40 enchaine les deux puits|;|ne pas descendre au fond enquiller le méandre à mi hauteur|;|facultatif (mais fort utile)|;|équipement possible sans MC|;|équipement strict minimum. + 2 broches facultatives possibles au pallier avant le plein vide|;|corde changée en juin 2016 (Gersam)|;|Ressaut d''accés galerie nuit blanche. Corde fixe fin 2009',
		17,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		23,
		2,
		NULL,
		'2013-08-19 21:11:35.000',
		NULL,
		4,
		'Par les puits parrallèles',
		'MC + P21 de l''entrée |;|R5|;|MC + P13 |;|dalle (R6 et P9) + P33|;|Total minimum :',
		'C38|;|C15|;|C28|;|C95|;|33 mousquetons sans plaquette',
		'1 AN + 1 AN (main courante) \n2B tête puits ou 1S + 1B\n2B + 2B|;|2B + 2B |;|MC et vire : 2B   \nY : 2B \n1 AN + 1 S|;|R6 et P9 : 2B + 2B + B + 2B + 2B + 2B \n\nP33 : 2B + 2B +dev/B + B\n|;|2 mousquetons avec plaquette',
		'Possibilité d''allonger la MC sur 2 B \n=> corde 48 m|;||;|En dernier : fractio jambon pour éviter un frottement. (prévoir 1 longue Dyneema).|;|Dans les deux cas, ne pas descendre jusqu''au fond mais penduler qq mètres avant le fond pour se poser sur le gros rocher en pente. Prévoir 1 sangle pour la DEV.\n \n|;|1 sangle\n1 Dyneema longue',
		18,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		24,
		4,
		NULL,
		'2016-10-12 23:49:45.000',
		NULL,
		4,
		'Grande verticale + vire d''accès',
		'Vire + Grand puits',
		'C30 + C100',
		'10 mousquetons\n1 plaquette\n3 sangles\n1 sangle longue\n1 kit pour frottement',
		'1 Nat \n1Spit \n3 Broches\n2 Nat sur poutre\nDev sur broche\nNat',
		18,
		NULL,
		NULL,
		'fra',
		false
	),
	(
		25,
		6,
		NULL,
		'2008-09-19 19:03:55.000',
		NULL,
		4,
		'Accès à la salle Hydrokarst',
		'P11 |;|P9|;|P4|;|P6|;|R3|;|P3\nP5|;|P11 (salle hydrokarst)',
		'C24|;|C22|;|C13|;|C13|;|C5|;|C30|;|C20',
		'2S + 1B + 1B + 1S pour MC + 1S et 1B en y|;|1AN (bloc énorme) +1 B (ou 2 B selon le côté où l''on équipe) + 1 dev sur spit|;|2 B + 1 B + 1S et 1B en y|;|2 B + 1B + 1S et 1B (ou 2S) en y|;|2S|;|corde de 30 m, 2S (ou 1B) + 1B + 1S (ou 1B) + 2B (ou 2S)  en y|;|2B (ou 1S et 1B) + 2B en y',
		'B = broche|;|B = broche|;|B = broche|;|B = broche|;|équipement très facultatif |;|B = broche|;|B = broche',
		21,
		NULL,
		NULL,
		'fra',
		false
	);
INSERT INTO public.t_bbs (
		id,
		articleyear,
		articletitle,
		librarycode,
		publicationother,
		publicationfascicule,
		publicationpages,
		"comments",
		publication_url,
		editor_address,
		editor_email,
		editor_url,
		abstract,
		xauteurfull,
		chaptercode,
		countrycode,
		xrefsubjectfull,
		xcountrycodefull,
		"ref",
		xrefnumeriquefinal,
		identifier,
		identifier_type,
		id_parent,
		pages
	)
VALUES (
		7,
		2015,
		NULL,
		'713',
		'Geositi della Puglia',
		NULL,
		NULL,
		'Fotografie',
		NULL,
		'Regione Puglia, Sagraf, Capurso (BA).',
		NULL,
		NULL,
		'Censimento di oltre 440 emergenze geologiche regionali di cui una gran parte di interesse carso-speleologico. Scheda descrittiva, fotografie e bibliografia per ogni geosito.',
		'MASTRONUZZI G. (a cura di); VALLETTA S. (a cura di); DAMIANI A. (a cura di); FIORE A. (a cura di); FRANCESCANGELI R. (a cura di); GIANDONATO P.B. (a cura di); IURILLI V. (a cura di); SABATO L. (a cura di);  ;  ',
		'1,11',
		NULL,
		'6.4; ; ; ; ',
		'IT12; ; ; ; ; ; ; ; ; ',
		'2019,0008',
		'5400007   ',
		NULL,
		NULL,
		NULL,
		'394'
	),
	(
		5,
		2014,
		'Zur Entwicklung der Karststrukturen im Riffkalkstein von Iberg und Winterberg bei Bad Grund (Westharz).',
		'706',
		'Mitt. Verb. dt. Höhlen- u. Karstforsch.',
		'60 (3+4)',
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		'On the development of karst structures in the western Harz/Germany.',
		'KNAPPE Hartmut;  ;  ;  ;  ;  ;  ;  ;  ;  ',
		'1,11',
		NULL,
		NULL,
		'D04; ; ; ; ; ; ; ; ; ',
		'2019,0006',
		'5400005   ',
		NULL,
		NULL,
		NULL,
		'80-90,'
	),
	(
		20,
		1997,
		'Wasserfärbung 1996 - Die Organisation',
		'62',
		'Jbericht Schweiz. Ges. für Höhlenforschung Sektion Bern',
		'45',
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		'Der Artikel beschreibt die einzelnen Arbeitsschritte, die für eine sorgfältige Planung einer Wasserfärbung / eines Tracerversuchs benötigt werden, und schätzt den dazu nötigen Zeitaufwand. Dazu gibt er Tipps für eine erfolgreiche Durchführung eines Versuchs.',
		'HÄUSELMANN Philipp;  ;  ;  ;  ;  ;  ;  ;  ;  ',
		'1,12',
		NULL,
		NULL,
		NULL,
		'2019,0021',
		'5400020   ',
		NULL,
		NULL,
		NULL,
		'82-92,'
	),
	(
		264,
		2014,
		'Die Vermessung der Bleßberghöhlen.',
		'706',
		'Karst und Höhle',
		'2011-2014',
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		'FOHLERT Rainer;  ;  ;  ;  ;  ;  ;  ;  ;  ',
		'2,11',
		'D09',
		NULL,
		NULL,
		'2019,0265',
		'5400264   ',
		NULL,
		NULL,
		NULL,
		'310-314,'
	),
	(
		18,
		2016,
		'Hydrodynamique d''un lac souterrain : équipement et premiers résultats (Lesse souterraine)',
		NULL,
		'Journées 2016 de Spéléologie Scientifique. Vingtième édition',
		' ',
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		'Compte rendu des vingtième Journées de la Spéléologie Scientifique organisées par l''Union Belge de Spéléologie. Résumé de communication sur des essais de traçages dans la Lesse souterraine.',
		'DEWAIDE Lorraine; ROCHEZ Gaëtan; PAUWELS Michel; HALLET Vincent;  ;  ;  ;  ;  ;  ',
		'1,12',
		NULL,
		'2.11; ; ; ; ',
		'B02; ; ; ; ; ; ; ; ; ',
		'2019,0019',
		'5400018   ',
		NULL,
		NULL,
		NULL,
		'1'
	),
	(
		52816,
		2003,
		'AA_NoCavingSubject___',
		'62',
		'Der Fledermaus',
		'Dez. 2003',
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		'AA_NoCavingSubject___',
		NULL,
		'9',
		NULL,
		NULL,
		NULL,
		NULL,
		'3955601   ',
		NULL,
		NULL,
		NULL,
		NULL
	);
INSERT INTO t_crs (
		id,
		id_author,
		id_reviewer,
		date_inscription,
		date_reviewed,
		definition,
		bounds,
		url,
		enabled,
		code
	)
VALUES (
		1,
		1,
		NULL,
		'2010-08-24 10:15:07.000',
		NULL,
		'+title=RGM 04 +proj=eqc +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0.0000,0.0000,0.0000,0,0,0,0 +units=m +no_defs',
		NULL,
		'http://spatialreference.org/ref/sr-org/6892/',
		true,
		'SR-ORG:6892'
	),
	(
		138,
		1,
		NULL,
		'2010-08-24 10:15:07.000',
		NULL,
		'+title=Old Hawaiian mean +proj=longlat +ellps=clrk66 +towgs84=58.0,-283.0,-182.0,0.0,0.0,0.0,0.0 +no_defs',
		NULL,
		'http://spatialreference.org/ref/epsg/61356405/',
		true,
		'EPSG:61356405'
	),
	(
		239,
		1,
		NULL,
		'2010-11-17 14:41:58.000',
		NULL,
		'+title=NTF (Paris) +proj=longlat +a=6378249.2 +b=6356515 +towgs84=-168,-60,320,0,0,0,0 +pm=paris +no_defs',
		NULL,
		'http://spatialreference.org/ref/epsg/4807',
		true,
		'EPSG:4807'
	),
	(
		255,
		1,
		NULL,
		'2010-11-17 14:41:58.000',
		NULL,
		'+title=NAD 1983 HARN New Mexico Central +proj=tmerc +lat_0=31 +lon_0=-106.25 +k=0.9999 +x_0=500000 +y_0=0 +ellps=GRS80 +units=m +no_defs',
		NULL,
		'http://spatialreference.org/ref/epsg/2826',
		true,
		'EPSG:2826'
	);
INSERT INTO public.j_country_crs (id_crs, id_country)
VALUES (239, 'FR'),
	(138, 'IT'),
	(255, 'US');
INSERT INTO public.j_country_language (id_country, id_language, is_official, is_main)
VALUES ('FR', 'epo', false, false),
	('IT', 'fra', false, false),
	('FR', 'fra', true, true),
	('IT', 'epo', true, true),
	('US', 'ces', false, false),
	('US', 'fra', false, false),
	('US', 'epo', true, true);
INSERT INTO public.j_document_caver_author (id_document, id_caver)
VALUES (16746, 4);
INSERT INTO public.j_document_language (id_document, id_language, is_main)
VALUES (109, '000', false),
	(161, '000', false),
	(191, '000', false),
	(1378, '000', false),
	(1409, '000', false),
	(2542, '000', false),
	(2591, '000', false),
	(2998, '000', false),
	(5801, '000', false),
	(6065, '000', false),
	(6068, '000', false),
	(6096, '000', false),
	(10406, '000', false),
	(12106, '000', false),
	(12639, '000', false),
	(16746, '000', false);
INSERT INTO public.j_document_region (id_document, id_region)
VALUES (109, 82),
	(161, 82),
	(191, 82),
	(1378, 82),
	(1409, 82),
	(2542, 82),
	(2591, 82),
	(2998, 82),
	(5801, 82),
	(6065, 82),
	(6068, 82),
	(6096, 82),
	(10406, 82),
	(12106, 82),
	(12639, 82),
	(16746, 82);
INSERT INTO public.j_entrance_caver (id_entrance, id_caver)
VALUES (1, 1),
	(1, 4),
	(1, 5),
	(1, 6),
	(2, 4),
	(2, 5),
	(3, 2),
	(4, 5),
	(5, 5),
	(5, 6),
	(6, 5),
	(7, 1),
	(7, 6),
	(9, 2),
	(10, 2),
	(11, 2),
	(12, 2),
	(12, 5),
	(13, 1),
	(13, 2),
	(13, 5),
	(14, 1),
	(14, 2),
	(15, 2),
	(15, 5),
	(16, 2),
	(17, 2),
	(18, 2),
	(20, 1),
	(20, 2),
	(20, 5),
	(21, 1),
	(21, 2),
	(21, 5);
INSERT INTO public.j_grotto_cave_explorer (id_cave, id_grotto)
VALUES (6, 1), (5, 1), (5, 2);
INSERT INTO public.j_grotto_cave_partner (id_cave, id_grotto)
VALUES (5, 1), (6,2);
INSERT INTO public.j_grotto_caver (id_caver, id_grotto)
VALUES (2, 1),
	(1, 2),
	(2, 2),
	(4, 2),
	(5, 2),
	(6, 2);
INSERT INTO public.j_license_type (id_license, id_type)
VALUES (1, 4),
	(1, 18);
-- INSERT INTO public.spatial_ref_sys (srid,auth_name,auth_srid,srtext,proj4text) VALUES
--	 (2192,'EPSG',2192,'PROJCS["ED50 / France EuroLambert (deprecated)",GEOGCS["ED50",DATUM["European_Datum_1950",SPHEROID["International 1924",6378388,297,AUTHORITY["EPSG","7022"]],TOWGS84[-87,-98,-121,0,0,0,0],AUTHORITY["EPSG","6230"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4230"]],PROJECTION["Lambert_Conformal_Conic_1SP"],PARAMETER["latitude_of_origin",46.8],PARAMETER["central_meridian",2.337229166666667],PARAMETER["scale_factor",0.99987742],PARAMETER["false_easting",600000],PARAMETER["false_northing",2200000],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["X",EAST],AXIS["Y",NORTH],AUTHORITY["EPSG","2192"]]','+proj=lcc +lat_1=46.8 +lat_0=46.8 +lon_0=2.337229166666667 +k_0=0.99987742 +x_0=600000 +y_0=2200000 +ellps=intl +towgs84=-87,-98,-121,0,0,0,0 +units=m +no_defs '),
--	 (2309,'EPSG',2309,'PROJCS["WGS 84 / TM 116 SE",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",116],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",10000000],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","2309"]]','+proj=tmerc +lat_0=0 +lon_0=116 +k=0.9996 +x_0=500000 +y_0=10000000 +datum=WGS84 +units=m +no_defs ');