name: Build Lint Test
on: [push]
jobs:
  # ===== Build & test API
  build-test:
    environment: build
    runs-on: ubuntu-latest

    # PostGreSQL test database init
    services:
      postgres:
        image: postgis/postgis
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: grottoce
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: npm
      - run: npm ci
      - run: npm run build:info
      - run: npm run lint
      - run: npm run coverage
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
