name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.15.2'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - run: npm install
      - run: npm run-script build
      - if: github.ref == 'refs/heads/master'
        run: tar --exclude-vcs --exclude=latest.tar.gz -czf latest.tar.gz .
      - name: store artifact for 1 day in github
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: latest.tar.gz
          path: latest.tar.gz
          retention-days: 1
      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/master'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Copy tar.gz to S3
        if: github.ref == 'refs/heads/master'
        run: |
          aws s3 sync . s3://appgrottocenter3 --exclude='*' --include='*/latest.tar.gz'
