name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.15.2'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - run: npm install
      - run: npm run-script build
      - run: npm test  
      - run: npm run-script coverage  
      - run: npm run-script coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_SERVICE_NAME: "Github Actions" 
          COVERALLS_GIT_BRANCH: ${{ github.ref }}
      - name: Create artefact latest.tar.gz file
        if: github.ref == 'refs/heads/master'
        run: |
          mkdir artefact
          tar --exclude-vcs --exclude=./artefact -czf artefact/latest.tar.gz .
      - name: store artifact for 1 day in github
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: latest.tar.gz
          path: artefact/latest.tar.gz
          retention-days: 1
      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/master'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Copy latest.tar.gz to S3
        if: github.ref == 'refs/heads/master'
        run: aws s3 cp ./artefact/latest.tar.gz s3://appgrottocenter3
